#!/bin/bash
# Script to copy the spaceapi json object generated by home assistant to our webserver
# Set up a cron job to run this script every couple minutes
#
# See https://community.home-assistant.io/t/running-a-shell-command-from-home-assistant-to-remote-linux-pc/135221/59
# for details on getting all of this set up with ssh keys and whatnot. All instructions are required
# Your ssh key must be in /config/ssh, trying to access it in ~/.ssh did not work
#
# Get our home assistant api token
TOKEN=$(cat /config/shell/hass.token)
# Get the space api json and format it pretty
cd /tmp
curl -X GET http://10.13.0.22/api/spaceapi -H 'Authorization: Bearer '$TOKEN | python3 -m json.tool > status.json
# Fix mangled characters
sed -i 's/\\u00b0/°/g' status.json
# Put the json file on the webserver
# On the webserver, /home/spaceapi/json is symlinked to /home/i3/www/spaceapi
# In the nginx site conf we add 'location /spaceapi/status.json' {} to make it available
sftp -i /config/ssh/id_rsa -o 'StrictHostKeyChecking=no' spaceapi@i3detroit.org: <<EOF
pwd
ls
cd json
put /tmp/status.json
exit
EOF
