#!/bin/bash
set -euo pipefail
set -x
# Script to copy the spaceapi json object generated by home assistant to our webserver
# Set up a cron job to run this script every couple minutes
#
# See https://community.home-assistant.io/t/running-a-shell-command-from-home-assistant-to-remote-linux-pc/135221/59
# for details on getting all of this set up with ssh keys and whatnot. All instructions are required
# Your ssh key must be in /config/ssh, trying to access it in ~/.ssh did not work

# Get the space api json and format it pretty
curl -s https://ha.i3.lc/api/spaceapi > /tmp/status.json

# Fix mangled characters
# TODO: do we need this?
sed -i 's/\\u00b0/°/g' /tmp/status.json

# Put the json file on the webserver
# On the webserver, /home/spaceapi/json is symlinked to /home/i3/www/spaceapi
# In the nginx site conf we add 'location /spaceapi/status.json' {} to make it available
scp -i /config/.ssh/spaceapi_ed25519 -o 'StrictHostKeyChecking=no' /tmp/status.json spaceapi@i3detroit.org:json/status.json
