- id: '1623327623174'
  alias: MQTT Query On Boot
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/classroom/glass-door/lock
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/classroom/glass-door/open
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/snapple-vending-light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/accent/chandelier-01/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/accent/chandelier-02/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/classroom/sign/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/cnc/vent/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/cnc/light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/disco/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/ceiling-fans/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/garage-door/lock
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/front-door/lock
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/south-vent/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/fablab/vent/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/infrastructure/compressor-valve/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/large-bathroom/light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/large-bathroom/vent/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/infrastructure/air-compressor/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/ceiling-fan/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/vent-fan/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/machine-shop/ceiling-fan/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/media-lab/lights/POWER
  - service: mqtt.publish
    data:
      topic: tele/i3/inside/commons/openevse/query
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/paint-box/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/traffic-light/POWER1
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/traffic-light/POWER2
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/traffic-light/POWER3
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/bumblebee/chiller/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/wolverine/chiller/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/blast-gate-monitor/query
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/craftroom/light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/elab/light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/hallway/light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/bumblebee/laser/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/wolverine/laser/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/classroom/lights-east/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/classroom/lights-west/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/dooridor/lights/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/notification-lights/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/small-bathroom/vent/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/small-bathroom/shower-light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/elab/accent/arch-north/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/elab/accent/arch-south/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/office/thermostat/target
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/genie-charging/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/siren/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/accent/lanterns/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/fairy-lights/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/fablab/chinesium/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/office/thermostat/query
  mode: single
- id: '1627008032755'
  alias: SpaceAPI Upload
  description: upload our spaceapi output to the i3detroit.org webserver
  trigger:
  - platform: time_pattern
    minutes: /2
  condition: []
  action:
  - service: shell_command.spaceapi_upload
  mode: single
- id: '1628099784943'
  alias: Large Bathroom Motion ON
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.large_bathroom_motion_sensor
    to: 'on'
  condition:
  - condition: device
    type: is_off
    device_id: 535a24966a688f9ddabfd042b92ad6a3
    entity_id: light.large_bathroom_light
    domain: light
    for:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  action:
  - type: turn_on
    device_id: 535a24966a688f9ddabfd042b92ad6a3
    entity_id: light.large_bathroom_light
    domain: light
  mode: single
- id: '1628099880959'
  alias: Large Bathroom Motion OFF
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.large_bathroom_motion_sensor
    to: 'off'
    for: 00:10:00
  condition: []
  action:
  - type: turn_off
    device_id: 535a24966a688f9ddabfd042b92ad6a3
    entity_id: light.large_bathroom_light
    domain: light
  mode: single
- id: '1628099948333'
  alias: Large Bathroom Fan Timeout
  description: ''
  triggers: []
  conditions: []
  actions: []
  mode: single
- id: '1628203562056'
  alias: Small Bathroom Motion ON
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.small_bathroom_motion_sensor
    to: 'on'
  condition:
  - condition: device
    type: is_off
    device_id: 698058789b64ea8af8cb2c0f0fc2a5c6
    entity_id: light.small_bathroom_light
    domain: light
  action:
  - type: turn_on
    device_id: 698058789b64ea8af8cb2c0f0fc2a5c6
    entity_id: light.small_bathroom_light
    domain: light
  mode: single
- id: '1628203629710'
  alias: Small Bathroom Motion OFF
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.small_bathroom_motion_sensor
    to: 'off'
    for: 0:10:00
  condition: []
  action:
  - type: turn_off
    device_id: 698058789b64ea8af8cb2c0f0fc2a5c6
    entity_id: light.small_bathroom_light
    domain: light
  mode: single
- id: '1628203747980'
  alias: Small Bathroom Fan Timeout
  description: ''
  triggers:
  - type: turned_on
    device_id: b9d21c33e17b82294cf7249ffe34c02b
    entity_id: aef868112cc9a79e59bf204d7bb04b81
    domain: switch
    trigger: device
    for:
      hours: 0
      minutes: 20
      seconds: 0
  conditions: []
  actions:
  - type: turn_off
    device_id: b9d21c33e17b82294cf7249ffe34c02b
    entity_id: aef868112cc9a79e59bf204d7bb04b81
    domain: switch
  mode: single
- id: '1638201213002'
  alias: Complain if genie not plugged in
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.genie_charge_state
    for:
      hours: 6
      minutes: 0
      seconds: 0
    to: unavailable
  - platform: state
    entity_id:
    - sensor.genie_charge_state
    to: not plugged in
    for:
      hours: 6
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.i3detroit
    data:
      message: The genie has been unplugged for over 6 hours
  - service: automation.turn_on
    target:
      entity_id: automation.notify_that_genie_is_plugged_in_again
    data: {}
  mode: single
- id: '1638201355599'
  alias: Notify that genie is plugged in again
  trigger:
  - platform: state
    entity_id: sensor.genie_charge_state
    to: Plugged in
  - platform: state
    entity_id: sensor.genie_charge_state
    to: Charging
  condition: []
  action:
  - service: notify.i3detroit
    data:
      message: The genie is plugged in again
  - service: automation.turn_off
    target:
      entity_id: automation.notify_that_genie_is_plugged_in_again
  mode: single
- id: '1638231960434'
  alias: Complain more if genie not plugged in
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.genie_charge_state
    to: Not plugged in
    for: '24:00:00'
  - platform: state
    entity_id:
    - sensor.genie_charge_state
    to: unavailable
    for:
      hours: 24
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.i3detroit
    data:
      message: Seriously, plug in the genie. It's been 24 hours. @mkfink @abzman
  - service: automation.turn_on
    target:
      entity_id: automation.notify_that_genie_is_plugged_in_again
    data: {}
  mode: single
- id: '1649818626943'
  alias: Thermostat Reset A-Side NE
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: climate.a_side_ne_shop_thermostat
    attribute: temperature
    above: '10'
    for:
      hours: 3
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: esphome.thermostat_a_ne_idle_reset
  mode: single
- id: '1651522520211'
  alias: Key monitor
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.a_side_scanned_uid
    to: '3980923'
  - platform: state
    entity_id: sensor.a_side_scanned_uid
    to: '3562045'
  - platform: state
    entity_id: sensor.b_side_scanned_uid
    to: '3980923'
  - platform: state
    entity_id: sensor.b_side_scanned_uid
    to: '3562045'
  condition: []
  action:
  - service: notify.i3detroit
    data:
      target: '@mkfink'
      message: Test message
  mode: single
- id: '1735616484533'
  alias: Turn On Recycle Notification Light
  description: ''
  trigger:
  - platform: time
    at: '18:00:05'
  condition:
  - condition: time
    before: '19:00:00'
    weekday:
    - wed
    after: '17:00:00'
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.recycle_notification_light
  mode: single
- id: '1735616564755'
  alias: Turn Off Recycle Notification Light
  description: ''
  trigger:
  - platform: time
    at: 08:00:05
  condition:
  - condition: time
    before: 09:00:00
    weekday:
    - thu
    after: 08:00:00
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.recycle_notification_light
  mode: single
- id: '1777580048451'
  alias: Laser Cutter Exhaust On
  description: ''
  triggers:
  - entity_id:
    - switch.cyclops_cyclops
    - switch.wolverine_wolverine
    to:
    - 'on'
    trigger: state
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: switch.laser_exhaust_fan_fan
    action: switch.turn_on
  mode: single
- id: '1777580438678'
  alias: Laser Cutter Exhaust Off
  description: ''
  triggers:
  - entity_id:
    - switch.cyclops
    - switch.wolverine
    to: 'off'
    trigger: state
  conditions:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.cyclops_cyclops
        state:
        - 'off'
      - condition: state
        entity_id: switch.cyclops_cyclops
        state:
        - unavailable
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.wolverine_wolverine
        state:
        - 'off'
      - condition: state
        entity_id: switch.wolverine_wolverine
        state:
        - unavailable
  actions:
  - data: {}
    target:
      entity_id: switch.laser_exhaust_fan_fan
    action: switch.turn_off
  mode: single
- id: '1777580550368'
  alias: Laser Cutter Air Compressor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.cyclops
    - switch.wolverine
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.air_compressor
  mode: single
- id: '1777580685213'
  alias: Laser Cutter Chiller On (Cyclops)
  description: ''
  triggers:
  - entity_id:
    - switch.cyclops_cyclops
    to:
    - 'on'
    trigger: state
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: switch.cyclops_chiller_power
    action: switch.turn_on
  mode: single
- id: '1777580687317'
  alias: Laser Cutter Chiller Off (Cyclops)
  description: ''
  triggers:
  - entity_id:
    - switch.cyclops_cyclops
    to:
    - 'off'
    trigger: state
  conditions: []
  actions:
  - data: {}
    action: switch.turn_off
    target:
      entity_id: switch.cyclops_chiller_power
  mode: single
- id: '1777580776765'
  alias: Laser Cutter Chiller Off (Wolverine)
  description: ''
  triggers:
  - entity_id:
    - switch.wolverine_wolverine
    to:
    - 'off'
    trigger: state
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: switch.wolverine_chiller_power
    action: switch.turn_off
  mode: single
- id: '1777581153679'
  alias: Laser Cutter Chiller On (Wolverine)
  description: ''
  triggers:
  - entity_id:
    - switch.wolverine_wolverine
    to:
    - 'on'
    trigger: state
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: switch.wolverine_chiller_power
    action: switch.turn_on
  mode: single
