- id: '1623327623174'
  alias: MQTT query on boot
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/classroom/glass-door/lock
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/classroom/glass-door/open
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/snapple-vending-light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/accent/chandelier-01/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/accent/chandelier-02/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/classroom/sign/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/cnc/vent/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/cnc/light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/disco/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/ceiling-fans/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/garage-door/lock
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/front-door/lock
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/south-vent/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/fablab/vent/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/infrastructure/compressor-valve/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/large-bathroom/light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/large-bathroom/vent/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/001/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/002/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/003/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/004/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/005/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/006/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/007/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/008/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/009/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/010/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/011/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/012/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/013/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/014/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/015/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/016/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/017/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/018/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/019/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/020/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/021/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/022/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/023/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/024/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/025/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/026/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/027/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/028/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/029/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/030/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/031/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/032/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/033/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/034/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/035/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/036/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/037/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/038/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/039/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/040/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/041/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/042/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/043/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/044/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/045/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/046/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/047/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/048/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/049/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/050/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/051/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/052/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/053/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/054/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/055/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/056/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/057/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/058/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/059/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/060/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/061/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/062/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/063/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/064/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/065/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/066/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/lights/067/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/infrastructure/air-compressor/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/ceiling-fan/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/vent-fan/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/machine-shop/ceiling-fan/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/media-lab/lights/POWER
  - service: mqtt.publish
    data:
      topic: tele/i3/inside/commons/openevse/query
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/paint-box/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/traffic-light/POWER1
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/traffic-light/POWER2
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/traffic-light/POWER3
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/bumblebee/chiller/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/wolverine/chiller/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/blast-gate-monitor/query
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/craftroom/light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/elab/light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/hallway/light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/bumblebee/laser/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/wolverine/laser/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/classroom/lights-east/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/classroom/lights-west/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/dooridor/lights/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/notification-lights/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/small-bathroom/vent/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/small-bathroom/shower-light/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/elab/accent/arch-north/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/elab/accent/arch-south/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/office/thermostat/target
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/genie-charging/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/siren/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/laser-zone/accent/lanterns/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/commons/fairy-lights/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/fablab/chinesium/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/i3/inside/office/thermostat/query
  mode: single
- id: '1627008032755'
  alias: SpaceAPI Upload
  description: upload our spaceapi output to the i3detroit.org webserver
  trigger:
  - platform: time_pattern
    minutes: /2
  condition: []
  action:
  - service: shell_command.spaceapi_upload
  mode: single
- id: '1628099784943'
  alias: Large Bathroom Motion ON
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.large_bathroom_motion_sensor
    to: 'on'
  condition:
  - condition: device
    type: is_off
    device_id: 535a24966a688f9ddabfd042b92ad6a3
    entity_id: light.large_bathroom_light
    domain: light
    for:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  action:
  - type: turn_on
    device_id: 535a24966a688f9ddabfd042b92ad6a3
    entity_id: light.large_bathroom_light
    domain: light
  mode: single
- id: '1628099880959'
  alias: Large Bathroom Motion OFF
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.large_bathroom_motion_sensor
    to: 'off'
    for: 00:10:00
  condition: []
  action:
  - type: turn_off
    device_id: 535a24966a688f9ddabfd042b92ad6a3
    entity_id: light.large_bathroom_light
    domain: light
  mode: single
- id: '1628099948333'
  alias: Large Bathroom Fan Timeout
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 9934d59d904e351e98e5a4316e2569f7
    entity_id: switch.large_bathroom_exhaust_fan
    domain: switch
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 9934d59d904e351e98e5a4316e2569f7
    entity_id: switch.large_bathroom_exhaust_fan
    domain: switch
  mode: single
- id: '1628115715834'
  alias: Dooridor and Hall Lights Sync
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: b5f81dc5a6ecf22d42a2d360866a13a4
    entity_id: light.classroom_east_lights
    domain: light
  - platform: device
    type: turned_off
    device_id: b5f81dc5a6ecf22d42a2d360866a13a4
    entity_id: light.classroom_east_lights
    domain: light
  condition: []
  action:
  - service: light.turn_{{ trigger.to_state.state }}
    target:
      entity_id: light.dooridor_light
  mode: single
- id: '1628116035884'
  alias: Classroom Lights Sync
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 96c207da5a46f5aa1a9bb0389635181d
    entity_id: binary_sensor.classroom_east_alt_switch_button
    domain: binary_sensor
  condition: []
  action:
  - choose:
    - conditions:
      - condition: device
        type: is_on
        device_id: b5f81dc5a6ecf22d42a2d360866a13a4
        entity_id: light.classroom_east_lights
        domain: light
      sequence:
      - type: turn_off
        device_id: 6236b48b4ccbaae89aa7ee6b525d2210
        entity_id: light.hallway_lights
        domain: light
      - type: turn_off
        device_id: d6ad15cf2b2f2802c956b427dddd9191
        entity_id: light.classroom_west_lights
        domain: light
      - type: turn_off
        device_id: b5f81dc5a6ecf22d42a2d360866a13a4
        entity_id: light.classroom_east_lights
        domain: light
    - conditions:
      - condition: device
        type: is_off
        device_id: b5f81dc5a6ecf22d42a2d360866a13a4
        entity_id: light.classroom_east_lights
        domain: light
      sequence:
      - type: turn_on
        device_id: d6ad15cf2b2f2802c956b427dddd9191
        entity_id: light.classroom_west_lights
        domain: light
      - type: turn_on
        device_id: 6236b48b4ccbaae89aa7ee6b525d2210
        entity_id: light.hallway_lights
        domain: light
      - type: turn_on
        device_id: b5f81dc5a6ecf22d42a2d360866a13a4
        entity_id: light.classroom_east_lights
        domain: light
    default: []
  mode: single
- id: '1628116933429'
  alias: Disco Mode
  description: ''
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/commons/disco/POWER
    payload: 'ON'
  - platform: mqtt
    topic: stat/i3/inside/commons/disco/POWER
    payload: 'OFF'
  condition: []
  action:
  - service: light.turn_{{ trigger.payload }}
    target:
      entity_id:
      - light.swirly_lights_01
      - light.swirly_lights_02
      - light.lanterns
      - light.chandelier01
      - light.chandelier02
      - light.fairy_lights
  - service: switch.turn_{{ trigger.payload }}
    target:
      entity_id: switch.disco_spotlights
  mode: single
- id: '1628117264623'
  alias: Craft Room Lights Button
  description: ''
  trigger:
  - platform: mqtt
    topic: cmnd/i3/inside/craftroom/light/power
    payload: '2'
  condition: []
  action:
  - type: toggle
    device_id: e8dbe6d72d480979dea9f4cdbc8e2582
    entity_id: light.craft_room_lights
    domain: light
  mode: single
- id: '1628203562056'
  alias: Small Bathroom Motion ON
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.small_bathroom_motion_sensor
    to: 'on'
  condition:
  - condition: device
    type: is_off
    device_id: 698058789b64ea8af8cb2c0f0fc2a5c6
    entity_id: light.small_bathroom_light_2
    domain: light
    for:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  action:
  - type: turn_on
    device_id: 698058789b64ea8af8cb2c0f0fc2a5c6
    entity_id: light.small_bathroom_light_2
    domain: light
  mode: single
- id: '1628203629710'
  alias: Small Bathroom Motion OFF
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.small_bathroom_motion_sensor
    to: 'off'
    for: 00:10:00
  condition: []
  action:
  - type: turn_off
    device_id: 698058789b64ea8af8cb2c0f0fc2a5c6
    entity_id: light.small_bathroom_light_2
    domain: light
  mode: single
- id: '1628203747980'
  alias: Small bathroom fan timeout
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 98e2b3734333f134187dcd38172f7aeb
    entity_id: switch.small_bathroom_exhaust_fan
    domain: switch
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 98e2b3734333f134187dcd38172f7aeb
    entity_id: switch.small_bathroom_exhaust_fan
    domain: switch
  mode: single
