- alias: Emergency lights on at noon
  trigger:
  - platform: time
    at: '12:00:00'
  action:
    service: light.turn_on
    entity_id: group.emergency_lights

- alias: Classroom sign on at sunset
  trigger:
  - platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.classroom_sign

- alias: Classroom sign off at sunrise
  trigger:
  - platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: switch.classroom_sign

- alias: Machine Shop Motion Sensor ON
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/machineShop/motion-sensor/motion
  action:
    service: light.turn_on
    entity_id: group.machine_shop_lights

- alias: Air Compressor Valve ON
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/infrastructure/air-compressor/POWER
    payload: "ON"
  action:
    service: switch.turn_on
    entity_id: switch.Air_Compressor_Valve

- alias: Air Compressor Valve OFF
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/infrastructure/air-compressor/POWER
    payload: "OFF"
  action:
    service: switch.turn_off
    entity_id: switch.Air_Compressor_Valve

- alias: Disco Chandelier ON
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/commons/disco/POWER
    payload: "ON"
  action:
    service: light.turn_on
    entity_id: 
      - light.Chandelier01
      - light.Chandelier02

- alias: Disco Chandelier OFF
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/commons/disco/POWER
    payload: "OFF"
  action:
    service: light.turn_off
    entity_id: 
      - light.Chandelier01
      - light.Chandelier02