- alias: Emergency lights on at noon
  trigger:
  - platform: time
    at: '12:00:00'
  action:
    service: light.turn_on
    entity_id: group.emergency_lights

- alias: Classroom sign on at sunset
  trigger:
  - platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.classroom_sign

- alias: Classroom sign off at sunrise
  trigger:
  - platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: switch.classroom_sign

- alias: Turn on machine shop lights when motion is detected 
  trigger:
    platform: state
    entity_id: sensor.Machine_Shop_Motion_Sensor
    from: 'OFF'
    to: 'ON'
  action:
    - service: light.turn_on
      entity_id: group.machine_shop_lights
    - service: mqtt.publish
      data:
        topic: "cmnd/i3/commons/ledMatrix/display"
        payload: "^SI see you there"

- alias: Turn of machine shop lights when motion is not detected for 60 min 
  trigger:
    platform: state
    entity_id: sensor.Machine_Shop_Motion_Sensor
    from: 'ON'
    to: 'OFF'
    for:
      hours: 1
  action:
    service: light.turn_off
    entity_id: group.machine_shop_lights

- alias: Air Compressor Valve ON
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/infrastructure/air-compressor/POWER
    payload: "ON"
  action:
    service: switch.turn_on
    entity_id: switch.Air_Compressor_Valve

- alias: Air Compressor Valve OFF
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/infrastructure/air-compressor/POWER
    payload: "OFF"
  action:
    service: switch.turn_off
    entity_id: switch.Air_Compressor_Valve

- alias: Disco Chandelier ON
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/commons/disco/POWER
    payload: "ON"
  action:
    service: light.turn_on
    entity_id: 
      - light.Chandelier01
      - light.Chandelier02

- alias: Disco Chandelier OFF
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/commons/disco/POWER
    payload: "OFF"
  action:
    service: light.turn_off
    entity_id: 
      - light.Chandelier01
      - light.Chandelier02

- alias: Who turned out the lights?
  trigger:
    - platform: state
      entity_id: group.shop_lights
      from: 'on'
      to: 'off'
  action:
    service: notify.slack_home_automation
    data:
      message: "Hey! Who turned out the lights?"

- alias: Fab lab fan status sign on
  trigger:
    - platform: state
      entity_id: fan.flv_fan
      to: 'on'
  action:
    service: mqtt.publish
    data:
      topic: "cmnd/i3/commons/16seg/display"
      payload: "FAB LAB FAN ON"

- alias: Fab lab fan status sign off
  trigger:
    - platform: state
      entity_id: fan.flv_fan
      to: 'off'
  action:
    service: mqtt.publish
    data:
      topic: "cmnd/i3/commons/16seg/display"
      payload: "FAB LAB FAN OFF"