- id: '1627008032755'
  alias: SpaceAPI Upload
  description: upload our spaceapi output to the i3detroit.org webserver
  trigger:
  - platform: time_pattern
    minutes: /2
  condition: []
  action:
  - service: shell_command.spaceapi_upload
  mode: single
- id: '1628099784943'
  alias: Large Bathroom Motion ON
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.large_bathroom_motion_sensor
    to: 'on'
  condition:
  - condition: device
    type: is_off
    device_id: 535a24966a688f9ddabfd042b92ad6a3
    entity_id: light.large_bathroom_light
    domain: light
    for:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  action:
  - type: turn_on
    device_id: 535a24966a688f9ddabfd042b92ad6a3
    entity_id: light.large_bathroom_light
    domain: light
  mode: single
- id: '1628099880959'
  alias: Large Bathroom Motion OFF
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.large_bathroom_motion_sensor
    to: 'off'
    for: 00:10:00
  condition: []
  action:
  - type: turn_off
    device_id: 535a24966a688f9ddabfd042b92ad6a3
    entity_id: light.large_bathroom_light
    domain: light
  mode: single
- id: '1628099948333'
  alias: Large Bathroom Fan Timeout
  description: ''
  triggers:
  - type: turned_on
    device_id: 63dc87c9aa968153af473c8b1322e097
    entity_id: 5f19a1d0a86adc2a01c5d705503d863e
    domain: switch
    trigger: device
    for:
      hours: 0
      minutes: 20
      seconds: 0
  conditions: []
  actions:
  - type: turn_off
    device_id: 63dc87c9aa968153af473c8b1322e097
    entity_id: 5f19a1d0a86adc2a01c5d705503d863e
    domain: switch
  mode: single
- id: '1628203562056'
  alias: Small Bathroom Motion ON
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.small_bathroom_motion_sensor
    to: 'on'
  condition:
  - condition: device
    type: is_off
    device_id: 698058789b64ea8af8cb2c0f0fc2a5c6
    entity_id: light.small_bathroom_light
    domain: light
  action:
  - type: turn_on
    device_id: 698058789b64ea8af8cb2c0f0fc2a5c6
    entity_id: light.small_bathroom_light
    domain: light
  mode: single
- id: '1628203629710'
  alias: Small Bathroom Motion OFF
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.small_bathroom_motion_sensor
    to: 'off'
    for: 0:10:00
  condition: []
  action:
  - type: turn_off
    device_id: 698058789b64ea8af8cb2c0f0fc2a5c6
    entity_id: light.small_bathroom_light
    domain: light
  mode: single
- id: '1628203747980'
  alias: Small Bathroom Fan Timeout
  description: ''
  triggers:
  - type: turned_on
    device_id: b9d21c33e17b82294cf7249ffe34c02b
    entity_id: aef868112cc9a79e59bf204d7bb04b81
    domain: switch
    trigger: device
    for:
      hours: 0
      minutes: 20
      seconds: 0
  conditions: []
  actions:
  - type: turn_off
    device_id: b9d21c33e17b82294cf7249ffe34c02b
    entity_id: aef868112cc9a79e59bf204d7bb04b81
    domain: switch
  mode: single
- id: '1638201355599'
  alias: Notify that genie is plugged in again
  trigger:
  - platform: state
    entity_id: sensor.genie_charge_state
    to: Plugged in
  - platform: state
    entity_id: sensor.genie_charge_state
    to: Charging
  condition: []
  action:
  - service: notify.i3detroit
    data:
      message: The genie is plugged in again
  - service: automation.turn_off
    target:
      entity_id: automation.notify_that_genie_is_plugged_in_again
  mode: single
- id: '1638231960434'
  alias: Complain more if genie not plugged in
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.genie_charge_state
    to: Not plugged in
    for: '24:00:00'
  - platform: state
    entity_id:
    - sensor.genie_charge_state
    to: unavailable
    for:
      hours: 24
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.i3detroit
    data:
      message: Seriously, plug in the genie. It's been 24 hours. @mkfink @abzman
  - service: automation.turn_on
    target:
      entity_id: automation.notify_that_genie_is_plugged_in_again
    data: {}
  mode: single
- id: '1735616484533'
  alias: Recycle Status Light On
  description: ''
  triggers:
  - at: '18:00:00'
    trigger: time
    weekday:
    - wed
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id: light.recycle_status_light_light_1
    data: {}
  mode: single
- id: '1735616564755'
  alias: Recycle Status Light Off
  description: ''
  triggers:
  - at: 08:00:00
    trigger: time
    weekday:
    - thu
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    target:
      entity_id: light.recycle_status_light_light_1
    data: {}
  mode: single
- id: '1777580048451'
  alias: Laser Cutter Exhaust On
  description: ''
  triggers:
  - entity_id:
    - switch.cyclops_relay
    - switch.wolverine_relay
    to:
    - 'on'
    trigger: state
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: switch.laser_exhaust_fan_fan
    action: switch.turn_on
  mode: single
- id: '1777580438678'
  alias: Laser Cutter Exhaust Off
  description: ''
  triggers:
  - entity_id:
    - switch.cyclops
    - switch.wolverine
    to: 'off'
    trigger: state
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.cyclops_cyclops
      state:
      - 'off'
    - condition: state
      entity_id: switch.wolverine_wolverine
      state:
      - 'off'
  actions:
  - data: {}
    target:
      entity_id: switch.laser_exhaust_fan_fan
    action: switch.turn_off
  mode: single
- id: '1777580550368'
  alias: Laser Cutter Air Compressor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.cyclops
    - switch.wolverine
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.air_compressor
  mode: single
- id: '1777580685213'
  alias: Laser Cutter Chiller On (Cyclops)
  description: ''
  triggers:
  - entity_id:
    - switch.cyclops_relay
    to:
    - 'on'
    trigger: state
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: switch.cyclops_chiller_power
    action: switch.turn_on
  mode: single
- id: '1777580687317'
  alias: Laser Cutter Chiller Off (Cyclops)
  description: ''
  triggers:
  - entity_id:
    - switch.cyclops_relay
    to:
    - 'off'
    trigger: state
  conditions: []
  actions:
  - data: {}
    action: switch.turn_off
    target:
      entity_id: switch.cyclops_chiller_power
  mode: single
- id: '1777580776765'
  alias: Laser Cutter Chiller Off (Wolverine)
  description: ''
  triggers:
  - entity_id:
    - switch.wolverine_relay
    to:
    - 'off'
    trigger: state
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: switch.wolverine_chiller_power
    action: switch.turn_off
  mode: single
- id: '1777581153679'
  alias: Laser Cutter Chiller On (Wolverine)
  description: ''
  triggers:
  - entity_id:
    - switch.wolverine_relay
    to:
    - 'on'
    trigger: state
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: switch.wolverine_chiller_power
    action: switch.turn_on
  mode: single
- id: '1778440316741'
  alias: Keep Genie Relay On
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - switch.genie_relay
    to:
    - 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    target:
      entity_id: switch.genie_relay
    data: {}
  mode: single
- id: '1778440877192'
  alias: Emergency Lights Reset
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - light.all_normal_light_groups
    to:
    - 'off'
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id: light.emergency_lights
    data: {}
  mode: single
