# - platform: mqtt
#     name: ""
#     state_topic: ""
#     # on means open, off means closed
#     payload_on: "ON"
#     payload_off: "OFF"
#     availability_topic: ""
#     payload_available: "online"
#     payload_not_available: "offline"
#     device_class: opening, plug, motion, etc see https://home-assistant.io/components/binary_sensor/


- platform: mqtt
  name: "Glass Door Lock Sensor"
  state_topic: "stat/i3/classroom/glassDoor/lock"
  # on means open, off means closed
  payload_on: "UNLOCKED"
  payload_off: "LOCKED"
  # availability_topic: ""
  # payload_available: "online"
  # payload_not_available: "offline"
  device_class: opening


- platform: mqtt
  name: "Glass Door Open Sensor"
  state_topic: "stat/i3/classroom/glassDoor/open"
  # on means open, off means closed
  payload_on: "OPEN"
  payload_off: "CLOSED"
  # availability_topic: "stat/i3/classroom/glassDoor/lock"
  # payload_available: "online"
  # payload_not_available: "offline"
  device_class: opening


- platform: mqtt
  name: "Garage Door Lock Sensor"
  state_topic: "stat/i3/inside/commons/garage-door/lock"
  # on means open, off means closed
  payload_on: "UNLOCKED"
  payload_off: "LOCKED"
  # availability_topic: ""
  # payload_available: "online"
  # payload_not_available: "offline"
  device_class: opening


- platform: mqtt
  name: "Machine Shop Motion Sensor"
  state_topic: "stat/i3/inside/machine-shop/motion-sensor/motion"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion

- platform: mqtt
  name: "Large Bathroom Motion Sensor"
  state_topic: "stat/i3/inside/large-bathroom/motion-sensor/motion"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion

- platform: mqtt
  name: "Small Bathroom Motion Sensor"
  state_topic: "stat/i3/inside/small-bathroom/motion-sensor/motion"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion

- platform: mqtt
  name: "Snapple Vending Compressor Power"
  state_topic: "tele/i3/inside/commons/snapple-vending-compress/STATE"
  value_template: '{{ value_json.POWER }}'
  payload_on: "ON"
  payload_off: "OFF"
  device_class: power

