- platform: mqtt
  name: Office
  modes:
    - 'off'
    - heat
    - cool
  # swing_modes:
  #   - 0
  #   - 1
  #   - 2
  #   - 3
  fan_modes:
    - auto
    - 'on'
    - 'off'
  availability_topic: "tele/i3/inside/office/thermostat/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  current_temperature_topic: "tele/i3/inside/office/thermostat/sensors"
  current_temperature_template: "{{value_json.temperature}}"
  mode_command_topic: "cmnd/i3/inside/office/thermostat/mode"
  mode_state_topic: "tele/i3/inside/office/thermostat/output"
  mode_state_template: "{{value_json.state}}"
  temperature_command_topic: "cmnd/i3/inside/office/thermostat/target"
  temperature_state_topic: "tele/i3/inside/office/thermostat/input"
  temperature_state_template: "{{value_json.target}}"
  fan_mode_command_topic: "cmnd/i3/inside/office/thermostat/fan"
  fan_mode_state_topic: "tele/i3/inside/office/thermostat/output"
  fan_mode_state_template: "{{value_json.fan}}"
  # swing_mode_command_topic: "cmnd/i3/inside/office/thermostat/swing"
  # swing_mode_state_topic: "tele/i3/inside/office/thermostat/input"
  # swing_mode_state_template: "{{value_json.swing}}"
  min_temp: 5
  max_temp: 30
