homeassistant:
  name: i3Detroit
  
  #location info
  latitude: 42.453828
  longitude: -83.113769
  elevation: 197

  # metric for Metric, imperial for Imperial
  unit_system: metric

  time_zone: America/Detroit

  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
    
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

influxdb:
  host: 10.13.0.22
  port: 8086
  database: hass
  username: homeassistant
  password: homeassistant
  include:
    domains:
      - light
      - fan
      - sensor
      - binary_sensor
      - switch
      - yr
      - sun
      - group

mqtt:
  broker: 10.13.0.22
  port: 1883
  client_id: homeassistant

media_player:
  - platform: cast

# included configs
group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
notify: !include notify.yaml
scene: !include scenes.yaml

# include device configs
light: !include lights.yaml
fan: !include fans.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
shell_command: !include shell_commands.yaml
# Extra panel for configurator plugin
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://10.13.0.22:3218