# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  server_port: 80

# Text to speech
tts:
  - platform: google_translate

mqtt:
  broker: 10.13.0.22
  birth_message:
    topic: "tele/homeassistant/hass/LWT"
    payload: "Online"
  will_message:
    topic: "tele/homeassistant/hass/LWT"
    payload: "Offline"

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
script: !include scripts.yaml
script old: !include_dir_merge_list scripts
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
light: !include_dir_merge_list lights
switch: !include_dir_merge_list switches
fan: !include_dir_merge_list fans
climate: !include climate.yaml
template: !include_dir_merge_list templates

notify: !include notify.yaml
# spaceapi: !include spaceapi.yaml

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 10.13.0.0/22
      trusted_users:
        10.13.0.0/22: !secret i3_member_userid
    - type: homeassistant

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state
