# - platform: mqtt
#   name: ""
#   state_topic: ""
#   command_topic: ""
#   payload_on: "ON"
#   payload_off: "OFF"

#Ceiling Fans
- platform: mqtt
  name: "CommonsCeilingFans"
  state_topic: "stat/i3/inside/commons/ceiling-fans/POWER"
  command_topic: "cmnd/i3/inside/commons/ceiling-fans/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/i3/inside/commons/ceiling-fans/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "LaserCeilingFan"
  state_topic: "stat/i3/inside/laser-zone/ceiling-fan/POWER"
  command_topic: "cmnd/i3/inside/laser-zone/ceiling-fan/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/i3/inside/laser-zone/ceiling-fan/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "MachineShopCeilingFan"
  state_topic: "stat/i3/inside/machine-shop/ceiling-fan/POWER"
  command_topic: "cmnd/i3/inside/machine-shop/ceiling-fan/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/i3/inside/machine-shop/ceiling-fan/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

# Exhaust Fans
- platform: mqtt
  name: "FLV_Fan"
  state_topic: "stat/i3/inside/fablab/vent/POWER"
  command_topic: "cmnd/i3/inside/fablab/vent/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/i3/inside/fablab/vent/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "LaserZoneExhaustFan"
  state_topic: "stat/i3/inside/laser-zone/vent-fan/POWER"
  command_topic: "cmnd/i3/inside/laser-zone/vent-fan/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/i3/inside/laser-zone/vent-fan/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "CNCCeilingExhaust"
  state_topic: "stat/i3/inside/cnc/vent/POWER"
  command_topic: "cmnd/i3/inside/cnc/vent/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/i3/inside/cnc/vent/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "SouthCeilingExhaust"
  state_topic: "stat/i3/inside/commons/south-vent/POWER"
  command_topic: "cmnd/i3/inside/commons/south-vent/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/i3/inside/commons/south-vent/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  