# Generated on 11/20/17 15:41:20
# by C:\Users\michael\Documents\GitHub\homeassistant-config\generating scripts\lights.py

- platform: mqtt
  name: "light001"
  state_topic: "stat/i3/inside/lights/001/POWER"
  command_topic: "cmnd/i3/inside/lights/001/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light002"
  state_topic: "stat/i3/inside/lights/002/POWER"
  command_topic: "cmnd/i3/inside/lights/002/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light003"
  state_topic: "stat/i3/inside/lights/003/POWER"
  command_topic: "cmnd/i3/inside/lights/003/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light004"
  state_topic: "stat/i3/inside/lights/004/POWER"
  command_topic: "cmnd/i3/inside/lights/004/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light005"
  state_topic: "stat/i3/inside/lights/005/POWER"
  command_topic: "cmnd/i3/inside/lights/005/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light006"
  state_topic: "stat/i3/inside/lights/006/POWER"
  command_topic: "cmnd/i3/inside/lights/006/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light007"
  state_topic: "stat/i3/inside/lights/007/POWER"
  command_topic: "cmnd/i3/inside/lights/007/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light008"
  state_topic: "stat/i3/inside/lights/008/POWER"
  command_topic: "cmnd/i3/inside/lights/008/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light009"
  state_topic: "stat/i3/inside/lights/009/POWER"
  command_topic: "cmnd/i3/inside/lights/009/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light010"
  state_topic: "stat/i3/inside/lights/010/POWER"
  command_topic: "cmnd/i3/inside/lights/010/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light011"
  state_topic: "stat/i3/inside/lights/011/POWER"
  command_topic: "cmnd/i3/inside/lights/011/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light012"
  state_topic: "stat/i3/inside/lights/012/POWER"
  command_topic: "cmnd/i3/inside/lights/012/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light013"
  state_topic: "stat/i3/inside/lights/013/POWER"
  command_topic: "cmnd/i3/inside/lights/013/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light014"
  state_topic: "stat/i3/inside/lights/014/POWER"
  command_topic: "cmnd/i3/inside/lights/014/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light015"
  state_topic: "stat/i3/inside/lights/015/POWER"
  command_topic: "cmnd/i3/inside/lights/015/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light016"
  state_topic: "stat/i3/inside/lights/016/POWER"
  command_topic: "cmnd/i3/inside/lights/016/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light017"
  state_topic: "stat/i3/inside/lights/017/POWER"
  command_topic: "cmnd/i3/inside/lights/017/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light018"
  state_topic: "stat/i3/inside/lights/018/POWER"
  command_topic: "cmnd/i3/inside/lights/018/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light019"
  state_topic: "stat/i3/inside/lights/019/POWER"
  command_topic: "cmnd/i3/inside/lights/019/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light020"
  state_topic: "stat/i3/inside/lights/020/POWER"
  command_topic: "cmnd/i3/inside/lights/020/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light021"
  state_topic: "stat/i3/inside/lights/021/POWER"
  command_topic: "cmnd/i3/inside/lights/021/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light022"
  state_topic: "stat/i3/inside/lights/022/POWER"
  command_topic: "cmnd/i3/inside/lights/022/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light023"
  state_topic: "stat/i3/inside/lights/023/POWER"
  command_topic: "cmnd/i3/inside/lights/023/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light024"
  state_topic: "stat/i3/inside/lights/024/POWER"
  command_topic: "cmnd/i3/inside/lights/024/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light025"
  state_topic: "stat/i3/inside/lights/025/POWER"
  command_topic: "cmnd/i3/inside/lights/025/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light026"
  state_topic: "stat/i3/inside/lights/026/POWER"
  command_topic: "cmnd/i3/inside/lights/026/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light027"
  state_topic: "stat/i3/inside/lights/027/POWER"
  command_topic: "cmnd/i3/inside/lights/027/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "LightWelding"
  state_topic: "stat/i3/inside/lights/028/POWER"
  command_topic: "cmnd/i3/inside/lights/028/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light029"
  state_topic: "stat/i3/inside/lights/029/POWER"
  command_topic: "cmnd/i3/inside/lights/029/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light030"
  state_topic: "stat/i3/inside/lights/030/POWER"
  command_topic: "cmnd/i3/inside/lights/030/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light031"
  state_topic: "stat/i3/inside/lights/031/POWER"
  command_topic: "cmnd/i3/inside/lights/031/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light032"
  state_topic: "stat/i3/inside/lights/032/POWER"
  command_topic: "cmnd/i3/inside/lights/032/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light033"
  state_topic: "stat/i3/inside/lights/033/POWER"
  command_topic: "cmnd/i3/inside/lights/033/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light034"
  state_topic: "stat/i3/inside/lights/034/POWER"
  command_topic: "cmnd/i3/inside/lights/034/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light035"
  state_topic: "stat/i3/inside/lights/035/POWER"
  command_topic: "cmnd/i3/inside/lights/035/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "LightVinyl"
  state_topic: "stat/i3/inside/lights/036/POWER"
  command_topic: "cmnd/i3/inside/lights/036/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "LightTreehouse"
  state_topic: "stat/i3/inside/lights/037/POWER"
  command_topic: "cmnd/i3/inside/lights/037/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "light038"
  state_topic: "stat/i3/inside/lights/038/POWER"
  command_topic: "cmnd/i3/inside/lights/038/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  brightness_scale: 50
  brightness_command_topic: "cmnd/i3/inside/lights/038/Dimmer"
  brightness_state_topic: "stat/i3/inside/lights/038/Dimmer"
  brightness_value_template: '{{value_json.Dimmer}}'

- platform: mqtt
  name: "LightLargeBathroom"
  state_topic: "stat/i3/inside/large-bathroom/light/POWER"
  command_topic: "cmnd/i3/inside/large-bathroom/light/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "LightMediaLab"
  state_topic: "stat/i3/inside/media-lab/lights/POWER"
  command_topic: "cmnd/i3/inside/media-lab/lights/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "LightSnappleVending"
  state_topic: "stat/i3/inside/commons/snapple-vending-light/POWER"
  command_topic: "cmnd/i3/inside/commons/snapple-vending-light/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "LightTrafficRed"
  state_topic: "stat/i3/inside/commons/traffic-light/POWER1"
  command_topic: "cmnd/i3/inside/commons/traffic-light/POWER1"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "LightTrafficYellow"
  state_topic: "stat/i3/inside/commons/traffic-light/POWER2"
  command_topic: "cmnd/i3/inside/commons/traffic-light/POWER2"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "LightTrafficGreen"
  state_topic: "stat/i3/inside/commons/traffic-light/POWER3"
  command_topic: "cmnd/i3/inside/commons/traffic-light/POWER3"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Chandelier01"
  state_topic: "stat/i3/inside/accent/chandelier-01/POWER"
  command_topic: "cmnd/i3/inside/accent/chandelier-01/POWER"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Chandelier02"
  state_topic: "stat/i3/inside/accent/chandelier-02/POWER"
  command_topic: "cmnd/i3/inside/accent/chandelier-02/POWER"
  payload_on: "ON"
  payload_off: "OFF"

