# - platform: mqtt
#   name: ""
#   state_topic: ""
#   unit_of_measurement: ""
#   value_template: '{{ value_json.thing }}' or '{{ value_json["thing"]["nestedthing"] }}' for nested json

# Weather prediction
- platform: yr

- platform: mqtt
  name: "Machine Shop Motion Sensor"
  state_topic: "stat/i3/inside/machineShop/motion-sensor/motion"

- platform: mqtt
  name: "Doorbell"
  state_topic: "stat/i3/inside/commons/normal-doorbell"
  
- platform: mqtt
  name: "openEVSE Amps"
  state_topic: "tele/i3/inside/commons/openevse/amp"
  unit_of_measurement: "milliamps"
  
- platform: mqtt
  name: "openEVSE Watt-Seconds"
  state_topic: "tele/i3/inside/commons/openevse/wh"
  unit_of_measurement: "Watt-seconds"
  
- platform: mqtt
  name: "openEVSE State"
  state_topic: "tele/i3/inside/commons/openevse/state"
  
- platform: mqtt
  name: "sonoff_RSSI"
  state_topic: "tele/i3/inside/commons/traffic-light/STATE"
  unit_of_measurement: "%"
  value_template: '{{ value_json["Wifi"]["RSSI"] }}'
  
- platform: mqtt
  name: "sonoff_humid"
  state_topic: "tele/i3/inside/commons/traffic-light/SENSOR"
  unit_of_measurement: "%"
  value_template: '{{ value_json["DHT22"]["Humidity"] }}'
  
- platform: mqtt
  name: "sonoff_temp"
  state_topic: "tele/i3/inside/commons/traffic-light/SENSOR"
  unit_of_measurement: "°C"
  value_template: '{{ value_json["DHT22"]["Temperature"] }}'
  
- platform: mqtt
  name: "portable_temp"
  state_topic: "stat/i3/inside/portable-temp/temp"
  unit_of_measurement: "°C"

