# - platform: mqtt
#   name: ""
#   state_topic: ""
#   unit_of_measurement: ""
#   value_template: '{{ value_json.thing }}' or '{{ value_json["thing"]["nestedthing"] }}' for nested json

# Weather prediction
- platform: yr
  name: "Weather"
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    #- fog
    - cloudiness
    #- lowClouds
    #- mediumClouds
    #- highClouds
    - dewpointTemperature

- platform: mqtt
  name: "Doorbell"
  state_topic: "stat/i3/inside/commons/normal-doorbell"
  
- platform: mqtt
  name: "openEVSE Amps"
  state_topic: "tele/i3/inside/commons/openevse/amp"
  unit_of_measurement: "milliamps"
  
- platform: mqtt
  name: "openEVSE Watt Seconds"
  state_topic: "tele/i3/inside/commons/openevse/wh"
  unit_of_measurement: "Watt seconds"
  
- platform: mqtt
  name: "openEVSE State"
  state_topic: "tele/i3/inside/commons/openevse/state"
  
- platform: mqtt
  name: "sonoff_RSSI"
  state_topic: "tele/i3/inside/commons/traffic-light/STATE"
  unit_of_measurement: "%"
  value_template: '{{ value_json["Wifi"]["RSSI"] }}'
  
- platform: mqtt
  name: "sonoff_humid"
  state_topic: "tele/i3/inside/commons/traffic-light/SENSOR"
  unit_of_measurement: "%"
  value_template: '{{ value_json["DHT22"]["Humidity"] }}'
  
- platform: mqtt
  name: "sonoff_temp"
  state_topic: "tele/i3/inside/commons/traffic-light/SENSOR"
  unit_of_measurement: "°C"
  value_template: '{{ value_json["DHT22"]["Temperature"] }}'
  
- platform: mqtt
  name: "portable_temp"
  state_topic: "stat/i3/inside/portable-temp/temp"
  unit_of_measurement: "°C"

- platform: template
  sensors:
    ev_charger_state:
      friendly_name: "EV Charger Status"
      value_template: >-
        {% if is_state('sensor.openEVSE_State', '1') %}
          Unplugged
        {% elif is_state('sensor.openEVSE_State', '2') %}
          Plugged_in
        {% elif is_state('sensor.openEVSE_State', '3') %}
          Charging
        {% else %}
          Unknown
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.openEVSE_State', '1') %}
          mdi:power-plug-off
        {% elif is_state('sensor.openEVSE_State', '2') %}
          mdi:power-plug
        {% elif is_state('sensor.openEVSE_State', '3') %}
          mdi:battery-charging
        {% else %}
          mdi:help-circle
        {% endif %}
    ev_charger_amps:
      friendly_name: "EV Charger Amps"
      unit_of_measurement: 'Amps'
      value_template: "{{ states('sensor.openEVSE_Amps')|float / 1000 | round(1) }}"
      icon_template: >-
         {% if states('sensor.openEVSE_Amps')|float > 0 %}
            mdi:battery-charging
          {% else %}
            mdi:power-plug-off
          {% endif %}
    ev_charger_wh:
      friendly_name: "EV Charger kWh"
      unit_of_measurement: 'kWh'
      value_template: "{{ states('sensor.openEVSE_Watt_Seconds') | multiply(1/3600000) | round(2) }}"

    weather_pressure_kpa:
      friendly_name: "Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.Weather_pressure') | multiply(1/10) | round(1) }}"

- platform: command_line
  name: "i3 Power Meter"
  command: "python3 /home/homeassistant/.homeassistant/power_meter.py"
  unit_of_measurement: "kWh"
  scan_interval: "60"

- platform: mqtt
  name: "Ground Cluster bmp280 Temperature"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/bmp280"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'

- platform: mqtt
  name: "Ground Cluster bmp280 Pressure"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/bmp280"
  unit_of_measurement: "Pa"
  value_template: '{{ value_json.Pressure }}'

- platform: mqtt
  name: "Ground Cluster Lux"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/lux"
  unit_of_measurement: "lux"
  value_template: '{{ value_json.Lux }}'

- platform: mqtt
  name: "Ground Cluster dht22 Temperature"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/dht22"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'

- platform: mqtt
  name: "Ground Cluster dht22 Humidity"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/dht22"
  unit_of_measurement: "%"
  value_template: '{{ value_json.Humidity }}'

- platform: mqtt
  name: "Ceiling Cluster bmp280 Temperature"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/bmp280"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'

- platform: mqtt
  name: "Ceiling Cluster bmp280 Pressure"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/bmp280"
  unit_of_measurement: "Pa"
  value_template: '{{ value_json.Pressure }}'

- platform: mqtt
  name: "Ceiling Cluster Lux"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/lux"
  unit_of_measurement: "lux"
  value_template: '{{ value_json.Lux }}'

- platform: mqtt
  name: "Ceiling Cluster dht22 Temperature"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/dht22"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'

- platform: mqtt
  name: "Ceiling Cluster dht22 Humidity"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/dht22"
  unit_of_measurement: "%"
  value_template: '{{ value_json.Humidity }}'

- platform: mqtt
  name: "Fablab Cluster bmp280 Temperature"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/bmp280"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'

- platform: mqtt
  name: "Fablab Cluster bmp280 Pressure"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/bmp280"
  unit_of_measurement: "Pa"
  value_template: '{{ value_json.Pressure }}'

- platform: mqtt
  name: "Fablab Cluster Lux"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/lux"
  unit_of_measurement: "lux"
  value_template: '{{ value_json.Lux }}'

- platform: mqtt
  name: "Fablab Cluster dht22 Temperature"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/dht22"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'

- platform: mqtt
  name: "Fablab Cluster dht22 Humidity"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/dht22"
  unit_of_measurement: "%"
  value_template: '{{ value_json.Humidity }}'

- platform: mqtt
  name: "Bumblebee Tube Time"
  state_topic: "stat/i3/laserZone/bumblebee_timer/laserTubeTime"
  unit_of_measurement: "millisecond"
