# 
#   - platform: mqtt
#     name: ""
#     state_topic: "stat"
#     command_topic: "cmnd"
#     availability_topic: "tele"
#     payload_on: "ON"
#     payload_off: "OFF"
#     payload_available: "online"
#     payload_not_available: "offline"

- platform: mqtt
  name: "Air Compressor"
  state_topic: "stat/i3/inside/infrastructure/air-compressor/POWER"
  command_topic: "cmnd/i3/inside/infrastructure/air-compressor/POWER"
  # availability_topic: "tele"
  payload_on: "ON"
  payload_off: "OFF"
  # payload_available: "online"
  # payload_not_available: "offline"

- platform: mqtt
  name: "Air Compressor Valve"
  state_topic: "stat/i3/inside/infrastructure/compressor-valve/POWER"
  command_topic: "cmnd/i3/inside/infrastructure/compressor-valve/POWER"
  # availability_topic: "tele/i3/inside/infrastructure/compressor-valve/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  # payload_available: "online"
  # payload_not_available: "offline"

- platform: mqtt
  name: "Classroom Sign"
  state_topic: "stat/i3/inside/classroom/sign/POWER"
  command_topic: "cmnd/i3/inside/classroom/sign/POWER"
  # availability_topic: "tele/i3/inside/classroom/sign/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  # payload_available: "online"
  # payload_not_available: "offline"

- platform: mqtt
  name: "Disco Ball"
  state_topic: "stat/i3/inside/commons/disco/POWER"
  command_topic: "cmnd/i3/inside/commons/disco/POWER"
  # availability_topic: "tele/i3/inside/commons/disco/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  # payload_available: "online"
  # payload_not_available: "offline"

- platform: mqtt
  name: "Paint Box Vent"
  state_topic: "stat/i3/inside/commons/paint-box/POWER"
  command_topic: "cmnd/i3/inside/commons/paint-box/POWER"
  # availability_topic: "tele/i3/inside/commons/paint-box/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  # payload_available: "online"
  # payload_not_available: "offline"

- platform: mqtt
  name: "Large Bathroom Vent Fan"
  state_topic: "stat/i3/inside/large-bathroom/vent/POWER"
  command_topic: "cmnd/i3/inside/large-bathroom/vent/POWER"
  payload_on: "ON"
  payload_off: "OFF"
