packages:
  package: !include common/button_box_4.yaml

substitutions:
  device_name: "machine-shop-switch-2"
  pretty_name: "Machine Shop Switch 2"
  target_1: "group.machine_shop_lights"
  target_2: "switch.machine_shop_ceiling_fan"
