- platform: mqtt
  name: 'Lanterns'
  state_topic: 'stat/i3/inside/laser-zone/accent/lanterns/POWER'
  command_topic: 'cmnd/i3/inside/laser-zone/accent/lanterns/POWER'
  json_attributes_topic: 'tele/i3/inside/laser-zone/accent/lanterns/STATE'
  availability_topic: 'tele/i3/inside/laser-zone/accent/lanterns/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
  payload_on: 'ON'
  payload_off: 'OFF'
