- platform: mqtt
  name: 'Light 029'
  state_topic: 'stat/i3/inside/lights/029/POWER'
  command_topic: 'cmnd/i3/inside/lights/029/POWER'
  json_attributes_topic: 'tele/i3/inside/lights/029/STATE'
  availability_topic: 'tele/i3/inside/lights/029/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
  payload_on: 'ON'
  payload_off: 'OFF'
