- platform: mqtt
  name: 'Light 035'
  state_topic: 'stat/i3/inside/lights/035/POWER'
  command_topic: 'cmnd/i3/inside/lights/035/POWER'
  json_attributes_topic: 'tele/i3/inside/lights/035/STATE'
  availability_topic: 'tele/i3/inside/lights/035/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
  payload_on: 'ON'
  payload_off: 'OFF'
