- platform: mqtt
  name: 'Swirly Lights 02'
  state_topic: 'stat/i3/inside/commons/accent/swirly-lights-02/POWER'
  command_topic: 'cmnd/i3/inside/commons/accent/swirly-lights-02/POWER'
  json_attributes_topic: 'tele/i3/inside/commons/accent/swirly-lights-02/STATE'
  availability_topic: 'tele/i3/inside/commons/accent/swirly-lights-02/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
  payload_on: 'ON'
  payload_off: 'OFF'
