- platform: mqtt
  name: 'Vinyl Light'
  state_topic: 'stat/i3/inside/lights/036/POWER'
  command_topic: 'cmnd/i3/inside/lights/036/POWER'
  json_attributes_topic: 'tele/i3/inside/lights/036/STATE'
  availability_topic: 'tele/i3/inside/lights/036/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
  payload_on: 'ON'
  payload_off: 'OFF'
