- platform: apcupsd
  resources:
    - status
    - linev
    - loadpct
    - bcharge
    - timeleft
    - outputv
    - retpct
    - itemp
    - battv
    - linefreq
    - lastxfer
    - numxfers
    - tonbatt
    - cumonbatt
