########################################################################
### Sensor Cluster 006
########################################################################
- platform: mqtt
  name: "Cluster 006 Temperature"
  state_topic: "tele/i3/inside/sensors/cluster-006/SENSOR"
  unit_of_measurement: "°C"
  value_template: '{{ value_json["BME280"]["Temperature"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-006/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 006 Pressure"
  state_topic: "tele/i3/inside/sensors/cluster-006/SENSOR"
  unit_of_measurement: "hPa"
  value_template: '{{ value_json["BME280"]["Pressure"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-006/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 006 Humidity"
  state_topic: "tele/i3/inside/sensors/cluster-006/SENSOR"
  unit_of_measurement: "%"
  value_template: '{{ value_json["BME280"]["Humidity"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-006/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 006 Lux"
  state_topic: "tele/i3/inside/sensors/cluster-006/SENSOR"
  unit_of_measurement: "lux"
  value_template: '{{ value_json["BH1750"]["Illuminance"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-006/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

########################################################################
### Sensor Cluster 007
########################################################################
- platform: mqtt
  name: "Cluster 007 Temperature"
  state_topic: "tele/i3/inside/sensors/cluster-007/SENSOR"
  unit_of_measurement: "°C"
  value_template: '{{ value_json["BME280"]["Temperature"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-007/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 007 Pressure"
  state_topic: "tele/i3/inside/sensors/cluster-007/SENSOR"
  unit_of_measurement: "hPa"
  value_template: '{{ value_json["BME280"]["Pressure"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-007/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 007 Humidity"
  state_topic: "tele/i3/inside/sensors/cluster-007/SENSOR"
  unit_of_measurement: "%"
  value_template: '{{ value_json["BME280"]["Humidity"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-007/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 007 Lux"
  state_topic: "tele/i3/inside/sensors/cluster-007/SENSOR"
  unit_of_measurement: "lux"
  value_template: '{{ value_json["BH1750"]["Illuminance"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-007/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

########################################################################
### Sensor Cluster 008
########################################################################
- platform: mqtt
  name: "Cluster 008 Temperature"
  state_topic: "tele/i3/inside/sensors/cluster-008/SENSOR"
  unit_of_measurement: "°C"
  value_template: '{{ value_json["BME280"]["Temperature"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-008/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 008 Pressure"
  state_topic: "tele/i3/inside/sensors/cluster-008/SENSOR"
  unit_of_measurement: "hPa"
  value_template: '{{ value_json["BME280"]["Pressure"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-008/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 008 Humidity"
  state_topic: "tele/i3/inside/sensors/cluster-008/SENSOR"
  unit_of_measurement: "%"
  value_template: '{{ value_json["BME280"]["Humidity"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-008/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 008 Lux"
  state_topic: "tele/i3/inside/sensors/cluster-008/SENSOR"
  unit_of_measurement: "lux"
  value_template: '{{ value_json["BH1750"]["Illuminance"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-008/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

########################################################################
### Display pressure in proper units
########################################################################
- platform: template
  sensors:
    cluster_006_pressure_kpa:
      friendly_name: "Cluster 006 Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.cluster_006_pressure') | multiply(1/10) | round(1) }}"
    cluster_007_pressure_kpa:
      friendly_name: "Cluster 007 Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.cluster_007_pressure') | multiply(1/10) | round(1) }}"
    cluster_008_pressure_kpa:
      friendly_name: "Cluster 008 Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.cluster_008_pressure') | multiply(1/10) | round(1) }}"
