########################################################################
### Ground Sensor Cluster
########################################################################
- platform: mqtt
  name: "Ground Cluster Temperature"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/bme280"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'
  force_update: True
  availability_topic: "tele/i3/inside/commons/ground-sensor-cluster/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Ground Cluster Pressure"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/bme280"
  unit_of_measurement: "Pa"
  value_template: '{{ value_json.Pressure }}'
  force_update: True
  availability_topic: "tele/i3/inside/commons/ground-sensor-cluster/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Ground Cluster Humidity"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/bme280"
  unit_of_measurement: "%"
  value_template: '{{ value_json.Humidity }}'
  force_update: True
  availability_topic: "tele/i3/inside/commons/ground-sensor-cluster/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Ground Cluster Lux"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/lux"
  unit_of_measurement: "lux"
  value_template: '{{ value_json.Lux }}'
  force_update: True

########################################################################
### Ceiling Sensor Cluster
########################################################################
- platform: mqtt
  name: "Ceiling Cluster Temperature"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/bme280"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'
  force_update: True
  availability_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Ceiling Cluster Pressure"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/bme280"
  unit_of_measurement: "Pa"
  value_template: '{{ value_json.Pressure }}'
  force_update: True
  availability_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Ceiling Cluster Humidity"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/bme280"
  unit_of_measurement: "%"
  value_template: '{{ value_json.Humidity }}'
  force_update: True
  availability_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Ceiling Cluster Lux"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/lux"
  unit_of_measurement: "lux"
  value_template: '{{ value_json.Lux }}'
  force_update: True
  availability_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

########################################################################
### Fab Lab Sensor Cluster
########################################################################
- platform: mqtt
  name: "Fablab Cluster Temperature"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/bme280"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'
  force_update: True
  availability_topic: "tele/i3/inside/fablab/sensor-cluster/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Fablab Cluster Pressure"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/bme280"
  unit_of_measurement: "Pa"
  value_template: '{{ value_json.Pressure }}'
  force_update: True
  availability_topic: "tele/i3/inside/fablab/sensor-cluster/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Fablab Cluster Humidity"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/bme280"
  unit_of_measurement: "%"
  value_template: '{{ value_json.Humidity }}'
  force_update: True
  availability_topic: "tele/i3/inside/fablab/sensor-cluster/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Fablab Cluster Lux"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/lux"
  unit_of_measurement: "lux"
  value_template: '{{ value_json.Lux }}'
  force_update: True
  availability_topic: "tele/i3/inside/fablab/sensor-cluster/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"


########################################################################
### Sensor Cluster 006
########################################################################
- platform: mqtt
  name: "Cluster 006 Temperature"
  state_topic: "tele/i3/inside/sensors/cluster-006/SENSOR"
  unit_of_measurement: "°C"
  value_template: '{{ value_json["BME280"]["Temperature"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-006/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 006 Pressure"
  state_topic: "tele/i3/inside/sensors/cluster-006/SENSOR"
  unit_of_measurement: "hPa"
  value_template: '{{ value_json["BME280"]["Pressure"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-006/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 006 Humidity"
  state_topic: "tele/i3/inside/sensors/cluster-006/SENSOR"
  unit_of_measurement: "%"
  value_template: '{{ value_json["BME280"]["Humidity"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-006/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 006 Lux"
  state_topic: "tele/i3/inside/sensors/cluster-006/SENSOR"
  unit_of_measurement: "lux"
  value_template: '{{ value_json["BH1750"]["Illuminance"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-006/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

########################################################################
### Sensor Cluster 007
########################################################################
- platform: mqtt
  name: "Cluster 007 Temperature"
  state_topic: "tele/i3/inside/sensors/cluster-007/SENSOR"
  unit_of_measurement: "°C"
  value_template: '{{ value_json["BME280"]["Temperature"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-007/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 007 Pressure"
  state_topic: "tele/i3/inside/sensors/cluster-007/SENSOR"
  unit_of_measurement: "hPa"
  value_template: '{{ value_json["BME280"]["Pressure"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-007/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 007 Humidity"
  state_topic: "tele/i3/inside/sensors/cluster-007/SENSOR"
  unit_of_measurement: "%"
  value_template: '{{ value_json["BME280"]["Humidity"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-007/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cluster 007 Lux"
  state_topic: "tele/i3/inside/sensors/cluster-007/SENSOR"
  unit_of_measurement: "lux"
  value_template: '{{ value_json["BH1750"]["Illuminance"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/sensors/cluster-007/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

########################################################################
### Display pressure in proper units
########################################################################
- platform: template
  sensors:
    ground_cluster_pressure_kpa:
      friendly_name: "Ground Cluster Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.ground_cluster_pressure') | multiply(1/1000) | round(1) }}"
    ceiling_cluster_pressure_kpa:
      friendly_name: "Ceiling Cluster Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.ceiling_cluster_pressure') | multiply(1/1000) | round(1) }}"
    fablab_cluster_pressure_kpa:
      friendly_name: "Fablab Cluster Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.fablab_cluster_pressure') | multiply(1/1000) | round(1) }}"
    cluster_006_pressure_kpa:
      friendly_name: "Cluster 006 Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.cluster_006_pressure') | multiply(1/10) | round(1) }}"
    cluster_007_pressure_kpa:
      friendly_name: "Cluster 007 Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.cluster_007_pressure') | multiply(1/10) | round(1) }}"
