- platform: mqtt
  name: "Commons light switches east"
  state_topic: "info/i3/inside/commons/light-switches-east/pressed"
  force_update: True

- platform: mqtt
  name: "Commons light switches west"
  state_topic: "info/i3/inside/commons/light-switches-west/pressed"
  force_update: True

- platform: mqtt
  name: "Machine shop light switches west"
  state_topic: "info/i3/inside/machine-shop/light-switches-west/pressed"
  force_update: True

- platform: mqtt
  name: "Machine shop light switches south"
  state_topic: "info/i3/inside/machine-shop/light-switches-south/pressed"
  force_update: True

- platform: mqtt
  name: "Middle east light switches south"
  state_topic: "info/i3/inside/commons/middle-east-light-switches-south/pressed"
  force_update: True

- platform: mqtt
  name: "Middle east light switches north"
  state_topic: "info/i3/inside/commons/middle-east-light-switches-north/pressed"
  force_update: True

- platform: mqtt
  name: "Disco button"
  state_topic: "info/i3/inside/commons/disco-button/pressed"
  force_update: True

- platform: mqtt
  name: "Air compressor requet button 001"
  state_topic: "info/i3/inside/air-compressor-request-001/pressed"
  force_update: True

- platform: mqtt
  name: "Air compressor request button 002"
  state_topic: "info/i3/inside/air-compressor-request-002/pressed"
  force_update: True

- platform: mqtt
  name: "Air compressor request button 003"
  state_topic: "info/i3/inside/air-compressor-request-003/pressed"
  force_update: True

- platform: mqtt
  name: "Welding light button"
  state_topic: "info/i3/inside/lights/028-button/pressed"
  force_update: True

- platform: mqtt
  name: "Fab lab control buttons"
  state_topic: "info/i3/inside/fablab-control-buttons/pressed"
  force_update: True
