- platform: mqtt
  name: 'Fablab Sensor Cluster'
  state_topic: 'stat/i3/inside/fablab/sensor-cluster/SENSOR'
  json_attributes_topic: 'tele/i3/inside/fablab/sensor-cluster/STATE'
  availability_topic: 'tele/i3/inside/fablab/sensor-cluster/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
- platform: template
  sensors:
    fablab_sensor_cluster_time:
      friendly_name: 'Fablab Sensor Cluster Time'
      value_template: '{{ states.sensor.fablab_sensor_cluster.attributes.Time }}'
    fablab_sensor_cluster_uptime:
      friendly_name: 'Fablab Sensor Cluster Uptime'
      value_template: '{{ states.sensor.fablab_sensor_cluster.attributes.Uptime }}'
    fablab_sensor_cluster_vcc:
      friendly_name: 'Fablab Sensor Cluster Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.sensor.fablab_sensor_cluster.attributes.Vcc }}'
    fablab_sensor_cluster_heap:
      friendly_name: 'Fablab Sensor Cluster Heap'
      value_template: '{{ states.sensor.fablab_sensor_cluster.attributes.Heap }}'
    fablab_sensor_cluster_sleepmode:
      friendly_name: 'Fablab Sensor Cluster SleepMode'
      value_template: '{{ states.sensor.fablab_sensor_cluster.attributes.SleepMode }}'
    fablab_sensor_cluster_sleep:
      friendly_name: 'Fablab Sensor Cluster Sleep'
      value_template: '{{ states.sensor.fablab_sensor_cluster.attributes.Sleep }}'
    fablab_sensor_cluster_loadavg:
      friendly_name: 'Fablab Sensor Cluster LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.sensor.fablab_sensor_cluster.attributes.LoadAvg }}'
    fablab_sensor_cluster_wifi_ssid:
      friendly_name: 'Fablab Sensor Cluster Wifi SSId'
      value_template: "{{ state_attr('sensor.fablab_sensor_cluster', 'Wifi')['SSId'] }}"
    fablab_sensor_cluster_wifi_bssid:
      friendly_name: 'Fablab Sensor Cluster Wifi BSSId'
      value_template: "{{ state_attr('sensor.fablab_sensor_cluster', 'Wifi')['BSSId'] }}"
    fablab_sensor_cluster_wifi_channel:
      friendly_name: 'Fablab Sensor Cluster Wifi Channel'
      value_template: "{{ state_attr('sensor.fablab_sensor_cluster', 'Wifi')['Channel'] }}"
    fablab_sensor_cluster_wifi_rssi:
      friendly_name: 'Fablab Sensor Cluster Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('sensor.fablab_sensor_cluster', 'Wifi')['RSSI'] }}"
    fablab_sensor_cluster_wifi_linkcount:
      friendly_name: 'Fablab Sensor Cluster Wifi Link Count'
      value_template: "{{ state_attr('sensor.fablab_sensor_cluster', 'Wifi')['LinkCount'] }}"
    fablab_sensor_cluster_wifi_downtime:
      friendly_name: 'Fablab Sensor Cluster Wifi Downtime'
      value_template: "{{ state_attr('sensor.fablab_sensor_cluster', 'Wifi')['Downtime'] }}"
    fablab_sensor_cluster_wifi_ap:
      friendly_name: 'Fablab Sensor Cluster Wifi AP'
      value_template: >-
        {% if state_attr('sensor.fablab_sensor_cluster', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('sensor.fablab_sensor_cluster', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('sensor.fablab_sensor_cluster', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('sensor.fablab_sensor_cluster', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('sensor.fablab_sensor_cluster', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('sensor.fablab_sensor_cluster', 'Wifi')['BSSId'] }}
        {% endif %}
- platform: mqtt
  name: 'Fablab Cluster Temperature'
  state_topic: 'tele/i3/inside/fablab/sensor-cluster/SENSOR'
  unit_of_measurement: '°C'
  value_template: "{{ value_json['BME280']['Temperature'] }}"
  force_update: True
  availability_topic: 'tele/i3/inside/fablab/sensor-cluster/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab Cluster Pressure'
  state_topic: 'tele/i3/inside/fablab/sensor-cluster/SENSOR'
  unit_of_measurement: 'hPa'
  value_template: "{{ value_json['BME280']['Pressure'] }}"
  force_update: True
  availability_topic: 'tele/i3/inside/fablab/sensor-cluster/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab Cluster Humidity'
  state_topic: 'tele/i3/inside/fablab/sensor-cluster/SENSOR'
  unit_of_measurement: '%'
  value_template: "{{ value_json['BME280']['Humidity'] }}"
  force_update: True
  availability_topic: 'tele/i3/inside/fablab/sensor-cluster/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab Cluster Lux'
  state_topic: 'tele/i3/inside/fablab/sensor-cluster/SENSOR'
  unit_of_measurement: 'lux'
  value_template: "{{ value_json['BH1750']['Illuminance'] }}"
  force_update: True
  availability_topic: 'tele/i3/inside/fablab/sensor-cluster/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: template
  sensors:
    fablab_cluster_pressure_kpa:
      friendly_name: "Fablab Cluster Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.fablab_cluster_pressure') | multiply(1/10) | round(1) }}"
