- platform: mqtt
  name: 'Fablab AC Total Start Time'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["TotalStartTime"] }}'
  force_update: True
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Total Energy'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  force_update: True
  unit_of_measurement: 'kilowatt hours'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Energy Use Yesterday'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  force_update: True
  unit_of_measurement: 'kilowatt hours'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Energy Use Today'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  force_update: True
  unit_of_measurement: 'kilowatt hours'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Energy Use Delta'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Period"] }}'
  force_update: True
  unit_of_measurement: 'Watt hours'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Power Draw'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  force_update: True
  unit_of_measurement: 'Watts'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Apparent Power Draw'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["ApparentPower"] }}'
  force_update: True
  unit_of_measurement: 'Watts'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Reactive Power Draw'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["ReactivePower"] }}'
  force_update: True
  unit_of_measurement: 'Watts'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Power Factor'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Factor"] }}'
  force_update: True
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Voltage'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  force_update: True
  unit_of_measurement: 'Volts'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Current'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  force_update: True
  unit_of_measurement: 'Amps'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

