
- platform: mqtt
  name: 'Fablab AC Total Start Time'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["TotalStartTime"] }}'
  force_update: True
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Total Energy'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  force_update: True
  unit_of_measurement: 'kilowatt hours'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Energy Use Yesterday'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  force_update: True
  unit_of_measurement: 'kilowatt hours'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Energy Use Today'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  force_update: True
  unit_of_measurement: 'kilowatt hours'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Energy Use Delta'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Period"] }}'
  force_update: True
  unit_of_measurement: 'Watt hours'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Power Draw'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  force_update: True
  unit_of_measurement: 'Watts'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Apparent Power Draw'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["ApparentPower"] }}'
  force_update: True
  unit_of_measurement: 'Watts'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Reactive Power Draw'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["ReactivePower"] }}'
  force_update: True
  unit_of_measurement: 'Watts'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Power Factor'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Factor"] }}'
  force_update: True
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Voltage'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  force_update: True
  unit_of_measurement: 'Volts'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: mqtt
  name: 'Fablab AC Current'
  state_topic: 'tele/i3/inside/fablab/ac/SENSOR'
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  force_update: True
  unit_of_measurement: 'Amps'
  availability_topic: 'tele/i3/inside/fablab/ac/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'

- platform: template
  sensors:
    fablab_ac_time:
      friendly_name: 'Fablab AC Time'
      value_template: '{{ states.switch.fablab_ac.attributes.Time }}'
    fablab_ac_uptime:
      friendly_name: 'Fablab AC Uptime'
      value_template: '{{ states.switch.fablab_ac.attributes.Uptime }}'
    fablab_ac_vcc:
      friendly_name: 'Fablab AC Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.switch.fablab_ac.attributes.Vcc }}'
    fablab_ac_heap:
      friendly_name: 'Fablab AC Heap'
      value_template: '{{ states.light.fablab_ac.attributes.Heap }}'
    fablab_ac_sleepmode:
      friendly_name: 'Fablab AC SleepMode'
      value_template: '{{ states.switch.fablab_ac.attributes.SleepMode }}'
    fablab_ac_sleep:
      friendly_name: 'Fablab AC Sleep'
      value_template: '{{ states.switch.fablab_ac.attributes.Sleep }}'
    fablab_ac_loadavg:
      friendly_name: 'Fablab AC LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.switch.fablab_ac.attributes.LoadAvg }}'
    fablab_ac_power:
      friendly_name: 'Fablab AC Power'
      value_template: '{{ states.switch.fablab_ac.attributes.POWER }}'
    fablab_ac_wifi_ssid:
      friendly_name: 'Fablab AC Wifi SSId'
      value_template: '{{ states.switch.fablab_ac.attributes.Wifi.SSId }}'
    fablab_ac_wifi_bssid:
      friendly_name: 'Fablab AC Wifi BSSId'
      value_template: >-
        {% if states.switch.fablab_ac.attributes.Wifi.BSSId | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif states.switch.fablab_ac.attributes.Wifi.BSSId | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif states.switch.fablab_ac.attributes.Wifi.BSSId | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif states.switch.fablab_ac.attributes.Wifi.BSSId | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif states.switch.fablab_ac.attributes.Wifi.BSSId | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ states.switch.fablab_ac.attributes.Wifi.BSSId }}
        {% endif %}
    fablab_ac_wifi_channel:
      friendly_name: 'Fablab AC Wifi Channel'
      value_template: '{{ states.switch.fablab_ac.attributes.Wifi.Channel }}'
    fablab_ac_wifi_rssi:
      friendly_name: 'Fablab AC Wifi RSSI'
      unit_of_measurement: '%'
      value_template: '{{ states.switch.fablab_ac.attributes.Wifi.RSSI }}'
    fablab_ac_wifi_linkcount:
      friendly_name: 'Fablab AC Wifi Link Count'
      value_template: '{{ states.switch.fablab_ac.attributes.Wifi.LinkCount }}'
    fablab_ac_wifi_downtime:
      friendly_name: 'Fablab AC Wifi Downtime'
      value_template: '{{ states.switch.fablab_ac.attributes.Wifi.Downtime }}'
