- platform: mqtt
  name: "Genie Power Draw"
  state_topic: "tele/i3/inside/commons/genie-charging/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  force_update: True
  unit_of_measurement: "Watts"
  availability_topic: "tele/i3/inside/commons/genie-charging/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  
- platform: mqtt
  name: "Genie Voltage"
  state_topic: "tele/i3/inside/commons/genie-charging/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  force_update: True
  unit_of_measurement: "Volts"
  availability_topic: "tele/i3/inside/commons/genie-charging/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Genie Current"
  state_topic: "tele/i3/inside/commons/genie-charging/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  force_update: True
  unit_of_measurement: "Amps"
  availability_topic: "tele/i3/inside/commons/genie-charging/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Genie Energy Use Delta"
  state_topic: "tele/i3/inside/commons/genie-charging/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Period"] }}'
  force_update: True
  unit_of_measurement: "Watt hours"
  availability_topic: "tele/i3/inside/commons/genie-charging/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Genie Energy Use Today"
  state_topic: "tele/i3/inside/commons/genie-charging/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/commons/genie-charging/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Genie Energy Use Yesterday"
  state_topic: "tele/i3/inside/commons/genie-charging/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/commons/genie-charging/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Genie Total Power"
  state_topic: "tele/i3/inside/commons/genie-charging/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/commons/genie-charging/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Genie Power Factor"
  state_topic: "tele/i3/inside/commons/genie-charging/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Factor"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/commons/Genie-charging/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: template
  sensors:
    genie_charge_state:
      friendly_name: "Genie Charger State"
      value_template: >-
        {% if states('sensor.genie_current') | float > 0.5 %}
          Charging
        {% elif (states('sensor.genie_current') | float <= 0.5) and (states('sensor.genie_current') | float > 0.1) %}
          Plugged in, not charging
        {% else %}
          Not plugged in
        {% endif %}
