- platform: mqtt
  name: "Network Rack Power Draw"
  state_topic: "tele/i3/inside/infrastructure/network-ra/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  force_update: True
  unit_of_measurement: "Watts"
  availability_topic: "tele/i3/inside/infrastructure/network-ra/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  
- platform: mqtt
  name: "Network Rack Voltage"
  state_topic: "tele/i3/inside/infrastructure/network-ra/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  force_update: True
  unit_of_measurement: "Volts"
  availability_topic: "tele/i3/inside/infrastructure/network-ra/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Network Rack Current"
  state_topic: "tele/i3/inside/infrastructure/network-ra/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  force_update: True
  unit_of_measurement: "Amps"
  availability_topic: "tele/i3/inside/infrastructure/network-ra/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Network Rack Energy Use Delta"
  state_topic: "tele/i3/inside/infrastructure/network-ra/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Period"] }}'
  force_update: True
  unit_of_measurement: "Watt hours"
  availability_topic: "tele/i3/inside/infrastructure/network-ra/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Network Rack Energy Use Today"
  state_topic: "tele/i3/inside/infrastructure/network-ra/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/infrastructure/network-ra/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Network Rack Energy Use Yesterday"
  state_topic: "tele/i3/inside/infrastructure/network-ra/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/infrastructure/network-ra/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Network Rack Total Power"
  state_topic: "tele/i3/inside/infrastructure/network-ra/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/infrastructure/network-ra/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Network Rack Power Factor"
  state_topic: "tele/i3/inside/infrastructure/network-ra/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Factor"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/infrastructure/network-ra/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Hardac Power Draw"
  state_topic: "tele/i3/inside/infrastructure/hardac-pow/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  force_update: True
  unit_of_measurement: "Watts"
  availability_topic: "tele/i3/inside/infrastructure/hardac-pow/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  
- platform: mqtt
  name: "Hardac Voltage"
  state_topic: "tele/i3/inside/infrastructure/hardac-pow/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  force_update: True
  unit_of_measurement: "Volts"
  availability_topic: "tele/i3/inside/infrastructure/hardac-pow/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Hardac Current"
  state_topic: "tele/i3/inside/infrastructure/hardac-pow/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  force_update: True
  unit_of_measurement: "Amps"
  availability_topic: "tele/i3/inside/infrastructure/hardac-pow/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Hardac Energy Use Delta"
  state_topic: "tele/i3/inside/infrastructure/hardac-pow/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Period"] }}'
  force_update: True
  unit_of_measurement: "Watt hours"
  availability_topic: "tele/i3/inside/infrastructure/hardac-pow/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Hardac Energy Use Today"
  state_topic: "tele/i3/inside/infrastructure/hardac-pow/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/infrastructure/hardac-pow/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Hardac Energy Use Yesterday"
  state_topic: "tele/i3/inside/infrastructure/hardac-pow/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/infrastructure/hardac-pow/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Hardac Total Power"
  state_topic: "tele/i3/inside/infrastructure/hardac-pow/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/infrastructure/hardac-pow/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Hardac Power Factor"
  state_topic: "tele/i3/inside/infrastructure/hardac-pow/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Factor"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/infrastructure/hardac-pow/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
