########################################################################
### Bumblebee Power
########################################################################
- platform: mqtt
  name: "Bumblebee Power Draw"
  state_topic: "tele/i3/inside/laser-zone/bumblebee/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  force_update: True
  unit_of_measurement: "Watts"
  availability_topic: "tele/i3/inside/laser-zone/bumblebee/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bumblebee Voltage"
  state_topic: "tele/i3/inside/laser-zone/bumblebee/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  force_update: True
  unit_of_measurement: "Volts"
  availability_topic: "tele/i3/inside/laser-zone/bumblebee/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bumblebee Current"
  state_topic: "tele/i3/inside/laser-zone/bumblebee/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  force_update: True
  unit_of_measurement: "Amps"
  availability_topic: "tele/i3/inside/laser-zone/bumblebee/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bumblebee Energy Use Delta"
  state_topic: "tele/i3/inside/laser-zone/bumblebee/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Period"] }}'
  force_update: True
  unit_of_measurement: "Watt hours"
  availability_topic: "tele/i3/inside/laser-zone/bumblebee/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bumblebee Energy Use Today"
  state_topic: "tele/i3/inside/laser-zone/bumblebee/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/laser-zone/bumblebee/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bumblebee Energy Use Yesterday"
  state_topic: "tele/i3/inside/laser-zone/bumblebee/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/laser-zone/bumblebee/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bumblebee Total Power"
  state_topic: "tele/i3/inside/laser-zone/bumblebee/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/laser-zone/bumblebee/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bumblebee Power Factor"
  state_topic: "tele/i3/inside/laser-zone/bumblebee/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Factor"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/commons/Snapple-charging/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

########################################################################
### Wolverine Power
########################################################################
- platform: mqtt
  name: "Wolverine Power Draw"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  force_update: True
  unit_of_measurement: "Watts"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Voltage"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  force_update: True
  unit_of_measurement: "Volts"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Current"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  force_update: True
  unit_of_measurement: "Amps"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Energy Use Delta"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Period"] }}'
  force_update: True
  unit_of_measurement: "Watt hours"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Energy Use Today"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Energy Use Yesterday"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Total Power"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Power Factor"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Factor"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/commons/Snapple-charging/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

########################################################################
### MISC
########################################################################
- platform: template
  sensors:
    bumblebee_power:
      friendly_name: "Bumblebee"
      value_template: "{{ states('switch.bumblebee') }}"
      icon_template: mdi:flash
    bumblebee_chiller_power:
      friendly_name: "Bumblebee Chiller"
      value_template: "{{ states('switch.bumblebee_chiller') }}"
      icon_template: mdi:flash
    wolverine_power:
      friendly_name: "Wolverine"
      value_template: "{{ states('switch.wolverine') }}"
      icon_template: mdi:flash
    wolverine_chiller_power:
      friendly_name: "Wolverine Chiller"
      value_template: "{{ states('switch.wolverine_chiller') }}"
      icon_template: mdi:flash
    laser_exhaust_power:
      friendly_name: "Laser Cutter Exhaust Fan"
      value_template: "{{ states('switch.LaserZoneExhaustFan') }}"
      icon_template: mdi:fan
    air_compressor_power:
      friendly_name: "Air Compressor"
      value_template: "{{ states('switch.air_compressor') }}"
    air_compressor_valve_state:
      friendly_name: "Air Compressor Valve"
      value_template: "{{ states('switch.air_compressor_valve') }}"

- platform: mqtt
  name: "Bumblebee Blast Gate"
  state_topic: "stat/i3/inside/laser-zone/bumblebee/vent-fan-gate"
  force_update: True
  availability_topic: "tele/i3/inside/laser-zone/bumblebee/vent-fan-gate/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Blast Gate"
  state_topic: "stat/i3/inside/laser-zone/wolverine/vent-fan-gate"
  force_update: True
  availability_topic: "tele/i3/inside/laser-zone/wolverine/vent-fan-gate/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bumblebee Tube Time"
  state_topic: "stat/i3/inside/laser-zone/bumblebee-timer/laser-tube-time"
  unit_of_measurement: "millisecond"
  force_update: True

- platform: mqtt
  name: "Wolverine Tube Time"
  state_topic: "stat/i3/inside/laser-zone/wolverine-timer/laser-tube-time"
  unit_of_measurement: "millisecond"
  force_update: True
