########################################################################
### Wolverine Power
########################################################################
- platform: mqtt
  name: "Wolverine Power Draw"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  force_update: True
  unit_of_measurement: "Watts"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Voltage"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  force_update: True
  unit_of_measurement: "Volts"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Current"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  force_update: True
  unit_of_measurement: "Amps"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Energy Use Delta"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Period"] }}'
  force_update: True
  unit_of_measurement: "Watt hours"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Energy Use Today"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Energy Use Yesterday"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Total Power"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  force_update: True
  unit_of_measurement: "kilowatt hours"
  availability_topic: "tele/i3/inside/laser-zone/wolverine/laser/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Power Factor"
  state_topic: "tele/i3/inside/laser-zone/wolverine/laser/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Factor"] }}'
  force_update: True
  availability_topic: "tele/i3/inside/commons/Snapple-charging/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Cyclops Blast Gate"
  state_topic: "stat/i3/inside/laser-zone/cyclops/vent-fan-gate"
  force_update: True
  availability_topic: "tele/i3/inside/laser-zone/blast-gate-monitor/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Wolverine Blast Gate"
  state_topic: "stat/i3/inside/laser-zone/wolverine/vent-fan-gate"
  force_update: True
  availability_topic: "tele/i3/inside/laser-zone/blast-gate-monitor/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
