- platform: template
  sensors:
    light_010_time:
      friendly_name: 'Light 010 Time'
      value_template: '{{ states.light.light_010.attributes.Time }}'
    light_010_uptime:
      friendly_name: 'Light 010 Uptime'
      value_template: '{{ states.light.light_010.attributes.Uptime }}'
    light_010_vcc:
      friendly_name: 'Light 010 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_010.attributes.Vcc }}'
    light_010_heap:
      friendly_name: 'Light 010 Heap'
      value_template: '{{ states.light.light_010.attributes.Heap }}'
    light_010_sleepmode:
      friendly_name: 'Light 010 SleepMode'
      value_template: '{{ states.light.light_010.attributes.SleepMode }}'
    light_010_sleep:
      friendly_name: 'Light 010 Sleep'
      value_template: '{{ states.light.light_010.attributes.Sleep }}'
    light_010_loadavg:
      friendly_name: 'Light 010 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_010.attributes.LoadAvg }}'
    light_010_wifi_ssid:
      friendly_name: 'Light 010 Wifi SSId'
      value_template: "{{ state_attr('light.light_010', 'Wifi')['SSId'] }}"
    light_010_wifi_ap:
      friendly_name: 'Light 010 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_010', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_010', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_010', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_010', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_010', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_010', 'Wifi')['BSSId'] }}
        {% endif %}
    light_010_wifi_bssid:
      friendly_name: 'Light 010 Wifi BSSId'
      value_template: "{{ state_attr('light.light_010', 'Wifi')['BSSId'] }}"
    light_010_wifi_channel:
      friendly_name: 'Light 010 Wifi Channel'
      value_template: "{{ state_attr('light.light_010', 'Wifi')['Channel'] }}"
    light_010_wifi_rssi:
      friendly_name: 'Light 010 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_010', 'Wifi')['RSSI'] }}"
    light_010_wifi_linkcount:
      friendly_name: 'Light 010 Wifi Link Count'
      value_template: "{{ state_attr('light.light_010', 'Wifi')['LinkCount'] }}"
    light_010_wifi_downtime:
      friendly_name: 'Light 010 Wifi Downtime'
      value_template: "{{ state_attr('light.light_010', 'Wifi')['Downtime'] }}"
    light_010_power:
      friendly_name: 'Light 010 Power'
      value_template: '{{ states.light.light_010.attributes.POWER }}'
