- platform: template
  sensors:
    light_049_time:
      friendly_name: 'Light 049 Time'
      value_template: '{{ states.light.light_049.attributes.Time }}'
    light_049_uptime:
      friendly_name: 'Light 049 Uptime'
      value_template: '{{ states.light.light_049.attributes.Uptime }}'
    light_049_vcc:
      friendly_name: 'Light 049 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_049.attributes.Vcc }}'
    light_049_heap:
      friendly_name: 'Light 049 Heap'
      value_template: '{{ states.light.light_049.attributes.Heap }}'
    light_049_sleepmode:
      friendly_name: 'Light 049 SleepMode'
      value_template: '{{ states.light.light_049.attributes.SleepMode }}'
    light_049_sleep:
      friendly_name: 'Light 049 Sleep'
      value_template: '{{ states.light.light_049.attributes.Sleep }}'
    light_049_loadavg:
      friendly_name: 'Light 049 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_049.attributes.LoadAvg }}'
    light_049_wifi_ssid:
      friendly_name: 'Light 049 Wifi SSId'
      value_template: "{{ state_attr('light.light_049', 'Wifi')['SSId'] }}"
    light_049_wifi_ap:
      friendly_name: 'Light 049 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_049', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_049', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_049', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_049', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_049', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_049', 'Wifi')['BSSId'] }}
        {% endif %}
    light_049_wifi_bssid:
      friendly_name: 'Light 049 Wifi BSSId'
      value_template: "{{ state_attr('light.light_049', 'Wifi')['BSSId'] }}"
    light_049_wifi_channel:
      friendly_name: 'Light 049 Wifi Channel'
      value_template: "{{ state_attr('light.light_049', 'Wifi')['Channel'] }}"
    light_049_wifi_rssi:
      friendly_name: 'Light 049 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_049', 'Wifi')['RSSI'] }}"
    light_049_wifi_linkcount:
      friendly_name: 'Light 049 Wifi Link Count'
      value_template: "{{ state_attr('light.light_049', 'Wifi')['LinkCount'] }}"
    light_049_wifi_downtime:
      friendly_name: 'Light 049 Wifi Downtime'
      value_template: "{{ state_attr('light.light_049', 'Wifi')['Downtime'] }}"
    light_049_power:
      friendly_name: 'Light 049 Power'
      value_template: '{{ states.light.light_049.attributes.POWER }}'
