- platform: template
  sensors:
    light_042_time:
      friendly_name: 'Light 042 Time'
      value_template: '{{ states.light.light_042.attributes.Time }}'
    light_042_uptime:
      friendly_name: 'Light 042 Uptime'
      value_template: '{{ states.light.light_042.attributes.Uptime }}'
    light_042_vcc:
      friendly_name: 'Light 042 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_042.attributes.Vcc }}'
    light_042_heap:
      friendly_name: 'Light 042 Heap'
      value_template: '{{ states.light.light_042.attributes.Heap }}'
    light_042_sleepmode:
      friendly_name: 'Light 042 SleepMode'
      value_template: '{{ states.light.light_042.attributes.SleepMode }}'
    light_042_sleep:
      friendly_name: 'Light 042 Sleep'
      value_template: '{{ states.light.light_042.attributes.Sleep }}'
    light_042_loadavg:
      friendly_name: 'Light 042 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_042.attributes.LoadAvg }}'
    light_042_wifi_ssid:
      friendly_name: 'Light 042 Wifi SSId'
      value_template: "{{ state_attr('light.light_042', 'Wifi')['SSId'] }}"
    light_042_wifi_ap:
      friendly_name: 'Light 042 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_042', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_042', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_042', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_042', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_042', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_042', 'Wifi')['BSSId'] }}
        {% endif %}
    light_042_wifi_bssid:
      friendly_name: 'Light 042 Wifi BSSId'
      value_template: "{{ state_attr('light.light_042', 'Wifi')['BSSId'] }}"
    light_042_wifi_channel:
      friendly_name: 'Light 042 Wifi Channel'
      value_template: "{{ state_attr('light.light_042', 'Wifi')['Channel'] }}"
    light_042_wifi_rssi:
      friendly_name: 'Light 042 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_042', 'Wifi')['RSSI'] }}"
    light_042_wifi_linkcount:
      friendly_name: 'Light 042 Wifi Link Count'
      value_template: "{{ state_attr('light.light_042', 'Wifi')['LinkCount'] }}"
    light_042_wifi_downtime:
      friendly_name: 'Light 042 Wifi Downtime'
      value_template: "{{ state_attr('light.light_042', 'Wifi')['Downtime'] }}"
    light_042_power:
      friendly_name: 'Light 042 Power'
      value_template: '{{ states.light.light_042.attributes.POWER }}'
