- platform: template
  sensors:
    light_021_time:
      friendly_name: 'Light 021 Time'
      value_template: '{{ states.light.light_021.attributes.Time }}'
    light_021_uptime:
      friendly_name: 'Light 021 Uptime'
      value_template: '{{ states.light.light_021.attributes.Uptime }}'
    light_021_vcc:
      friendly_name: 'Light 021 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_021.attributes.Vcc }}'
    light_021_heap:
      friendly_name: 'Light 021 Heap'
      value_template: '{{ states.light.light_021.attributes.Heap }}'
    light_021_sleepmode:
      friendly_name: 'Light 021 SleepMode'
      value_template: '{{ states.light.light_021.attributes.SleepMode }}'
    light_021_sleep:
      friendly_name: 'Light 021 Sleep'
      value_template: '{{ states.light.light_021.attributes.Sleep }}'
    light_021_loadavg:
      friendly_name: 'Light 021 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_021.attributes.LoadAvg }}'
    light_021_wifi_ssid:
      friendly_name: 'Light 021 Wifi SSId'
      value_template: "{{ state_attr('light.light_021', 'Wifi')['SSId'] }}"
    light_021_wifi_ap:
      friendly_name: 'Light 021 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_021', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_021', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_021', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_021', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_021', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_021', 'Wifi')['BSSId'] }}
        {% endif %}
    light_021_wifi_bssid:
      friendly_name: 'Light 021 Wifi BSSId'
      value_template: "{{ state_attr('light.light_021', 'Wifi')['BSSId'] }}"
    light_021_wifi_channel:
      friendly_name: 'Light 021 Wifi Channel'
      value_template: "{{ state_attr('light.light_021', 'Wifi')['Channel'] }}"
    light_021_wifi_rssi:
      friendly_name: 'Light 021 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_021', 'Wifi')['RSSI'] }}"
    light_021_wifi_linkcount:
      friendly_name: 'Light 021 Wifi Link Count'
      value_template: "{{ state_attr('light.light_021', 'Wifi')['LinkCount'] }}"
    light_021_wifi_downtime:
      friendly_name: 'Light 021 Wifi Downtime'
      value_template: "{{ state_attr('light.light_021', 'Wifi')['Downtime'] }}"
    light_021_power:
      friendly_name: 'Light 021 Power'
      value_template: '{{ states.light.light_021.attributes.POWER }}'
