- platform: template
  sensors:
    light_014_time:
      friendly_name: 'Light 014 Time'
      value_template: '{{ states.light.light_014.attributes.Time }}'
    light_014_uptime:
      friendly_name: 'Light 014 Uptime'
      value_template: '{{ states.light.light_014.attributes.Uptime }}'
    light_014_vcc:
      friendly_name: 'Light 014 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_014.attributes.Vcc }}'
    light_014_heap:
      friendly_name: 'Light 014 Heap'
      value_template: '{{ states.light.light_014.attributes.Heap }}'
    light_014_sleepmode:
      friendly_name: 'Light 014 SleepMode'
      value_template: '{{ states.light.light_014.attributes.SleepMode }}'
    light_014_sleep:
      friendly_name: 'Light 014 Sleep'
      value_template: '{{ states.light.light_014.attributes.Sleep }}'
    light_014_loadavg:
      friendly_name: 'Light 014 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_014.attributes.LoadAvg }}'
    light_014_wifi_ssid:
      friendly_name: 'Light 014 Wifi SSId'
      value_template: "{{ state_attr('light.light_014', 'Wifi')['SSId'] }}"
    light_014_wifi_ap:
      friendly_name: 'Light 014 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_014', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_014', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_014', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_014', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_014', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_014', 'Wifi')['BSSId'] }}
        {% endif %}
    light_014_wifi_bssid:
      friendly_name: 'Light 014 Wifi BSSId'
      value_template: "{{ state_attr('light.light_014', 'Wifi')['BSSId'] }}"
    light_014_wifi_channel:
      friendly_name: 'Light 014 Wifi Channel'
      value_template: "{{ state_attr('light.light_014', 'Wifi')['Channel'] }}"
    light_014_wifi_rssi:
      friendly_name: 'Light 014 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_014', 'Wifi')['RSSI'] }}"
    light_014_wifi_linkcount:
      friendly_name: 'Light 014 Wifi Link Count'
      value_template: "{{ state_attr('light.light_014', 'Wifi')['LinkCount'] }}"
    light_014_wifi_downtime:
      friendly_name: 'Light 014 Wifi Downtime'
      value_template: "{{ state_attr('light.light_014', 'Wifi')['Downtime'] }}"
    light_014_power:
      friendly_name: 'Light 014 Power'
      value_template: '{{ states.light.light_014.attributes.POWER }}'
