- platform: template
  sensors:
    light_043_time:
      friendly_name: 'Light 043 Time'
      value_template: '{{ states.light.light_043.attributes.Time }}'
    light_043_uptime:
      friendly_name: 'Light 043 Uptime'
      value_template: '{{ states.light.light_043.attributes.Uptime }}'
    light_043_vcc:
      friendly_name: 'Light 043 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_043.attributes.Vcc }}'
    light_043_heap:
      friendly_name: 'Light 043 Heap'
      value_template: '{{ states.light.light_043.attributes.Heap }}'
    light_043_sleepmode:
      friendly_name: 'Light 043 SleepMode'
      value_template: '{{ states.light.light_043.attributes.SleepMode }}'
    light_043_sleep:
      friendly_name: 'Light 043 Sleep'
      value_template: '{{ states.light.light_043.attributes.Sleep }}'
    light_043_loadavg:
      friendly_name: 'Light 043 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_043.attributes.LoadAvg }}'
    light_043_wifi_ssid:
      friendly_name: 'Light 043 Wifi SSId'
      value_template: "{{ state_attr('light.light_043', 'Wifi')['SSId'] }}"
    light_043_wifi_ap:
      friendly_name: 'Light 043 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_043', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_043', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_043', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_043', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_043', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_043', 'Wifi')['BSSId'] }}
        {% endif %}
    light_043_wifi_bssid:
      friendly_name: 'Light 043 Wifi BSSId'
      value_template: "{{ state_attr('light.light_043', 'Wifi')['BSSId'] }}"
    light_043_wifi_channel:
      friendly_name: 'Light 043 Wifi Channel'
      value_template: "{{ state_attr('light.light_043', 'Wifi')['Channel'] }}"
    light_043_wifi_rssi:
      friendly_name: 'Light 043 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_043', 'Wifi')['RSSI'] }}"
    light_043_wifi_linkcount:
      friendly_name: 'Light 043 Wifi Link Count'
      value_template: "{{ state_attr('light.light_043', 'Wifi')['LinkCount'] }}"
    light_043_wifi_downtime:
      friendly_name: 'Light 043 Wifi Downtime'
      value_template: "{{ state_attr('light.light_043', 'Wifi')['Downtime'] }}"
    light_043_power:
      friendly_name: 'Light 043 Power'
      value_template: '{{ states.light.light_043.attributes.POWER }}'
