- platform: template
  sensors:
    light_011_time:
      friendly_name: 'Light 011 Time'
      value_template: '{{ states.light.light_011.attributes.Time }}'
    light_011_uptime:
      friendly_name: 'Light 011 Uptime'
      value_template: '{{ states.light.light_011.attributes.Uptime }}'
    light_011_vcc:
      friendly_name: 'Light 011 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_011.attributes.Vcc }}'
    light_011_heap:
      friendly_name: 'Light 011 Heap'
      value_template: '{{ states.light.light_011.attributes.Heap }}'
    light_011_sleepmode:
      friendly_name: 'Light 011 SleepMode'
      value_template: '{{ states.light.light_011.attributes.SleepMode }}'
    light_011_sleep:
      friendly_name: 'Light 011 Sleep'
      value_template: '{{ states.light.light_011.attributes.Sleep }}'
    light_011_loadavg:
      friendly_name: 'Light 011 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_011.attributes.LoadAvg }}'
    light_011_wifi_ssid:
      friendly_name: 'Light 011 Wifi SSId'
      value_template: "{{ state_attr('light.light_011', 'Wifi')['SSId'] }}"
    light_011_wifi_ap:
      friendly_name: 'Light 011 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_011', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_011', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_011', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_011', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_011', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_011', 'Wifi')['BSSId'] }}
        {% endif %}
    light_011_wifi_bssid:
      friendly_name: 'Light 011 Wifi BSSId'
      value_template: "{{ state_attr('light.light_011', 'Wifi')['BSSId'] }}"
    light_011_wifi_channel:
      friendly_name: 'Light 011 Wifi Channel'
      value_template: "{{ state_attr('light.light_011', 'Wifi')['Channel'] }}"
    light_011_wifi_rssi:
      friendly_name: 'Light 011 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_011', 'Wifi')['RSSI'] }}"
    light_011_wifi_linkcount:
      friendly_name: 'Light 011 Wifi Link Count'
      value_template: "{{ state_attr('light.light_011', 'Wifi')['LinkCount'] }}"
    light_011_wifi_downtime:
      friendly_name: 'Light 011 Wifi Downtime'
      value_template: "{{ state_attr('light.light_011', 'Wifi')['Downtime'] }}"
    light_011_power:
      friendly_name: 'Light 011 Power'
      value_template: '{{ states.light.light_011.attributes.POWER }}'
