- platform: template
  sensors:
    light_024_time:
      friendly_name: 'Light 024 Time'
      value_template: '{{ states.light.light_024.attributes.Time }}'
    light_024_uptime:
      friendly_name: 'Light 024 Uptime'
      value_template: '{{ states.light.light_024.attributes.Uptime }}'
    light_024_vcc:
      friendly_name: 'Light 024 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_024.attributes.Vcc }}'
    light_024_heap:
      friendly_name: 'Light 024 Heap'
      value_template: '{{ states.light.light_024.attributes.Heap }}'
    light_024_sleepmode:
      friendly_name: 'Light 024 SleepMode'
      value_template: '{{ states.light.light_024.attributes.SleepMode }}'
    light_024_sleep:
      friendly_name: 'Light 024 Sleep'
      value_template: '{{ states.light.light_024.attributes.Sleep }}'
    light_024_loadavg:
      friendly_name: 'Light 024 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_024.attributes.LoadAvg }}'
    light_024_wifi_ssid:
      friendly_name: 'Light 024 Wifi SSId'
      value_template: "{{ state_attr('light.light_024', 'Wifi')['SSId'] }}"
    light_024_wifi_ap:
      friendly_name: 'Light 024 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_024', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_024', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_024', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_024', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_024', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_024', 'Wifi')['BSSId'] }}
        {% endif %}
    light_024_wifi_bssid:
      friendly_name: 'Light 024 Wifi BSSId'
      value_template: "{{ state_attr('light.light_024', 'Wifi')['BSSId'] }}"
    light_024_wifi_channel:
      friendly_name: 'Light 024 Wifi Channel'
      value_template: "{{ state_attr('light.light_024', 'Wifi')['Channel'] }}"
    light_024_wifi_rssi:
      friendly_name: 'Light 024 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_024', 'Wifi')['RSSI'] }}"
    light_024_wifi_linkcount:
      friendly_name: 'Light 024 Wifi Link Count'
      value_template: "{{ state_attr('light.light_024', 'Wifi')['LinkCount'] }}"
    light_024_wifi_downtime:
      friendly_name: 'Light 024 Wifi Downtime'
      value_template: "{{ state_attr('light.light_024', 'Wifi')['Downtime'] }}"
    light_024_power:
      friendly_name: 'Light 024 Power'
      value_template: '{{ states.light.light_024.attributes.POWER }}'
