- platform: template
  sensors:
    light_025_time:
      friendly_name: 'Light 025 Time'
      value_template: '{{ states.light.light_025.attributes.Time }}'
    light_025_uptime:
      friendly_name: 'Light 025 Uptime'
      value_template: '{{ states.light.light_025.attributes.Uptime }}'
    light_025_vcc:
      friendly_name: 'Light 025 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_025.attributes.Vcc }}'
    light_025_heap:
      friendly_name: 'Light 025 Heap'
      value_template: '{{ states.light.light_025.attributes.Heap }}'
    light_025_sleepmode:
      friendly_name: 'Light 025 SleepMode'
      value_template: '{{ states.light.light_025.attributes.SleepMode }}'
    light_025_sleep:
      friendly_name: 'Light 025 Sleep'
      value_template: '{{ states.light.light_025.attributes.Sleep }}'
    light_025_loadavg:
      friendly_name: 'Light 025 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_025.attributes.LoadAvg }}'
    light_025_wifi_ssid:
      friendly_name: 'Light 025 Wifi SSId'
      value_template: "{{ state_attr('light.light_025', 'Wifi')['SSId'] }}"
    light_025_wifi_ap:
      friendly_name: 'Light 025 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_025', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_025', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_025', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_025', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_025', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_025', 'Wifi')['BSSId'] }}
        {% endif %}
    light_025_wifi_bssid:
      friendly_name: 'Light 025 Wifi BSSId'
      value_template: "{{ state_attr('light.light_025', 'Wifi')['BSSId'] }}"
    light_025_wifi_channel:
      friendly_name: 'Light 025 Wifi Channel'
      value_template: "{{ state_attr('light.light_025', 'Wifi')['Channel'] }}"
    light_025_wifi_rssi:
      friendly_name: 'Light 025 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_025', 'Wifi')['RSSI'] }}"
    light_025_wifi_linkcount:
      friendly_name: 'Light 025 Wifi Link Count'
      value_template: "{{ state_attr('light.light_025', 'Wifi')['LinkCount'] }}"
    light_025_wifi_downtime:
      friendly_name: 'Light 025 Wifi Downtime'
      value_template: "{{ state_attr('light.light_025', 'Wifi')['Downtime'] }}"
    light_025_power:
      friendly_name: 'Light 025 Power'
      value_template: '{{ states.light.light_025.attributes.POWER }}'
