- platform: template
  sensors:
    light_034_time:
      friendly_name: 'Light 034 Time'
      value_template: '{{ states.light.light_034.attributes.Time }}'
    light_034_uptime:
      friendly_name: 'Light 034 Uptime'
      value_template: '{{ states.light.light_034.attributes.Uptime }}'
    light_034_vcc:
      friendly_name: 'Light 034 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_034.attributes.Vcc }}'
    light_034_heap:
      friendly_name: 'Light 034 Heap'
      value_template: '{{ states.light.light_034.attributes.Heap }}'
    light_034_sleepmode:
      friendly_name: 'Light 034 SleepMode'
      value_template: '{{ states.light.light_034.attributes.SleepMode }}'
    light_034_sleep:
      friendly_name: 'Light 034 Sleep'
      value_template: '{{ states.light.light_034.attributes.Sleep }}'
    light_034_loadavg:
      friendly_name: 'Light 034 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_034.attributes.LoadAvg }}'
    light_034_wifi_ssid:
      friendly_name: 'Light 034 Wifi SSId'
      value_template: "{{ state_attr('light.light_034', 'Wifi')['SSId'] }}"
    light_034_wifi_ap:
      friendly_name: 'Light 034 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_034', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_034', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_034', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_034', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_034', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_034', 'Wifi')['BSSId'] }}
        {% endif %}
    light_034_wifi_bssid:
      friendly_name: 'Light 034 Wifi BSSId'
      value_template: "{{ state_attr('light.light_034', 'Wifi')['BSSId'] }}"
    light_034_wifi_channel:
      friendly_name: 'Light 034 Wifi Channel'
      value_template: "{{ state_attr('light.light_034', 'Wifi')['Channel'] }}"
    light_034_wifi_rssi:
      friendly_name: 'Light 034 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_034', 'Wifi')['RSSI'] }}"
    light_034_wifi_linkcount:
      friendly_name: 'Light 034 Wifi Link Count'
      value_template: "{{ state_attr('light.light_034', 'Wifi')['LinkCount'] }}"
    light_034_wifi_downtime:
      friendly_name: 'Light 034 Wifi Downtime'
      value_template: "{{ state_attr('light.light_034', 'Wifi')['Downtime'] }}"
    light_034_power:
      friendly_name: 'Light 034 Power'
      value_template: '{{ states.light.light_034.attributes.POWER }}'
