- platform: template
  sensors:
    light_054_time:
      friendly_name: 'Light 054 Time'
      value_template: '{{ states.light.light_054.attributes.Time }}'
    light_054_uptime:
      friendly_name: 'Light 054 Uptime'
      value_template: '{{ states.light.light_054.attributes.Uptime }}'
    light_054_vcc:
      friendly_name: 'Light 054 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_054.attributes.Vcc }}'
    light_054_heap:
      friendly_name: 'Light 054 Heap'
      value_template: '{{ states.light.light_054.attributes.Heap }}'
    light_054_sleepmode:
      friendly_name: 'Light 054 SleepMode'
      value_template: '{{ states.light.light_054.attributes.SleepMode }}'
    light_054_sleep:
      friendly_name: 'Light 054 Sleep'
      value_template: '{{ states.light.light_054.attributes.Sleep }}'
    light_054_loadavg:
      friendly_name: 'Light 054 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_054.attributes.LoadAvg }}'
    light_054_wifi_ssid:
      friendly_name: 'Light 054 Wifi SSId'
      value_template: "{{ state_attr('light.light_054', 'Wifi')['SSId'] }}"
    light_054_wifi_ap:
      friendly_name: 'Light 054 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_054', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_054', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_054', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_054', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_054', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_054', 'Wifi')['BSSId'] }}
        {% endif %}
    light_054_wifi_bssid:
      friendly_name: 'Light 054 Wifi BSSId'
      value_template: "{{ state_attr('light.light_054', 'Wifi')['BSSId'] }}"
    light_054_wifi_channel:
      friendly_name: 'Light 054 Wifi Channel'
      value_template: "{{ state_attr('light.light_054', 'Wifi')['Channel'] }}"
    light_054_wifi_rssi:
      friendly_name: 'Light 054 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_054', 'Wifi')['RSSI'] }}"
    light_054_wifi_linkcount:
      friendly_name: 'Light 054 Wifi Link Count'
      value_template: "{{ state_attr('light.light_054', 'Wifi')['LinkCount'] }}"
    light_054_wifi_downtime:
      friendly_name: 'Light 054 Wifi Downtime'
      value_template: "{{ state_attr('light.light_054', 'Wifi')['Downtime'] }}"
    light_054_power:
      friendly_name: 'Light 054 Power'
      value_template: '{{ states.light.light_054.attributes.POWER }}'
