- platform: template
  sensors:
    light_039_time:
      friendly_name: 'Light 039 Time'
      value_template: '{{ states.light.light_039.attributes.Time }}'
    light_039_uptime:
      friendly_name: 'Light 039 Uptime'
      value_template: '{{ states.light.light_039.attributes.Uptime }}'
    light_039_vcc:
      friendly_name: 'Light 039 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_039.attributes.Vcc }}'
    light_039_heap:
      friendly_name: 'Light 039 Heap'
      value_template: '{{ states.light.light_039.attributes.Heap }}'
    light_039_sleepmode:
      friendly_name: 'Light 039 SleepMode'
      value_template: '{{ states.light.light_039.attributes.SleepMode }}'
    light_039_sleep:
      friendly_name: 'Light 039 Sleep'
      value_template: '{{ states.light.light_039.attributes.Sleep }}'
    light_039_loadavg:
      friendly_name: 'Light 039 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_039.attributes.LoadAvg }}'
    light_039_wifi_ssid:
      friendly_name: 'Light 039 Wifi SSId'
      value_template: "{{ state_attr('light.light_039', 'Wifi')['SSId'] }}"
    light_039_wifi_ap:
      friendly_name: 'Light 039 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_039', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_039', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_039', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_039', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_039', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_039', 'Wifi')['BSSId'] }}
        {% endif %}
    light_039_wifi_bssid:
      friendly_name: 'Light 039 Wifi BSSId'
      value_template: "{{ state_attr('light.light_039', 'Wifi')['BSSId'] }}"
    light_039_wifi_channel:
      friendly_name: 'Light 039 Wifi Channel'
      value_template: "{{ state_attr('light.light_039', 'Wifi')['Channel'] }}"
    light_039_wifi_rssi:
      friendly_name: 'Light 039 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_039', 'Wifi')['RSSI'] }}"
    light_039_wifi_linkcount:
      friendly_name: 'Light 039 Wifi Link Count'
      value_template: "{{ state_attr('light.light_039', 'Wifi')['LinkCount'] }}"
    light_039_wifi_downtime:
      friendly_name: 'Light 039 Wifi Downtime'
      value_template: "{{ state_attr('light.light_039', 'Wifi')['Downtime'] }}"
    light_039_power:
      friendly_name: 'Light 039 Power'
      value_template: '{{ states.light.light_039.attributes.POWER }}'
    light_039_dimmer:
      friendly_name: 'Light 039 Dimmer'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_039.attributes.Dimmer }}'
    light_039_fade:
      friendly_name: 'Light 039 Fade'
      value_template: '{{ states.light.light_039.attributes.Fade }}'
    light_039_speed:
      friendly_name: 'Light 039 Speed'
      value_template: '{{ states.light.light_039.attributes.Speed }}'
    light_039_led_table:
      friendly_name: 'Light 039 LED Table'
      value_template: '{{ states.light.light_039.attributes.LedTable }}'
