- platform: template
  sensors:
    light_015_time:
      friendly_name: 'Light 015 Time'
      value_template: '{{ states.light.light_015.attributes.Time }}'
    light_015_uptime:
      friendly_name: 'Light 015 Uptime'
      value_template: '{{ states.light.light_015.attributes.Uptime }}'
    light_015_vcc:
      friendly_name: 'Light 015 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_015.attributes.Vcc }}'
    light_015_heap:
      friendly_name: 'Light 015 Heap'
      value_template: '{{ states.light.light_015.attributes.Heap }}'
    light_015_sleepmode:
      friendly_name: 'Light 015 SleepMode'
      value_template: '{{ states.light.light_015.attributes.SleepMode }}'
    light_015_sleep:
      friendly_name: 'Light 015 Sleep'
      value_template: '{{ states.light.light_015.attributes.Sleep }}'
    light_015_loadavg:
      friendly_name: 'Light 015 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_015.attributes.LoadAvg }}'
    light_015_wifi_ssid:
      friendly_name: 'Light 015 Wifi SSId'
      value_template: "{{ state_attr('light.light_015', 'Wifi')['SSId'] }}"
    light_015_wifi_ap:
      friendly_name: 'Light 015 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_015', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_015', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_015', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_015', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_015', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_015', 'Wifi')['BSSId'] }}
        {% endif %}
    light_015_wifi_bssid:
      friendly_name: 'Light 015 Wifi BSSId'
      value_template: "{{ state_attr('light.light_015', 'Wifi')['BSSId'] }}"
    light_015_wifi_channel:
      friendly_name: 'Light 015 Wifi Channel'
      value_template: "{{ state_attr('light.light_015', 'Wifi')['Channel'] }}"
    light_015_wifi_rssi:
      friendly_name: 'Light 015 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_015', 'Wifi')['RSSI'] }}"
    light_015_wifi_linkcount:
      friendly_name: 'Light 015 Wifi Link Count'
      value_template: "{{ state_attr('light.light_015', 'Wifi')['LinkCount'] }}"
    light_015_wifi_downtime:
      friendly_name: 'Light 015 Wifi Downtime'
      value_template: "{{ state_attr('light.light_015', 'Wifi')['Downtime'] }}"
    light_015_power:
      friendly_name: 'Light 015 Power'
      value_template: '{{ states.light.light_015.attributes.POWER }}'
