- platform: template
  sensors:
    light_046_time:
      friendly_name: 'Light 046 Time'
      value_template: '{{ states.light.light_046.attributes.Time }}'
    light_046_uptime:
      friendly_name: 'Light 046 Uptime'
      value_template: '{{ states.light.light_046.attributes.Uptime }}'
    light_046_vcc:
      friendly_name: 'Light 046 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_046.attributes.Vcc }}'
    light_046_heap:
      friendly_name: 'Light 046 Heap'
      value_template: '{{ states.light.light_046.attributes.Heap }}'
    light_046_sleepmode:
      friendly_name: 'Light 046 SleepMode'
      value_template: '{{ states.light.light_046.attributes.SleepMode }}'
    light_046_sleep:
      friendly_name: 'Light 046 Sleep'
      value_template: '{{ states.light.light_046.attributes.Sleep }}'
    light_046_loadavg:
      friendly_name: 'Light 046 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_046.attributes.LoadAvg }}'
    light_046_wifi_ssid:
      friendly_name: 'Light 046 Wifi SSId'
      value_template: "{{ state_attr('light.light_046', 'Wifi')['SSId'] }}"
    light_046_wifi_ap:
      friendly_name: 'Light 046 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_046', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_046', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_046', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_046', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_046', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_046', 'Wifi')['BSSId'] }}
        {% endif %}
    light_046_wifi_bssid:
      friendly_name: 'Light 046 Wifi BSSId'
      value_template: "{{ state_attr('light.light_046', 'Wifi')['BSSId'] }}"
    light_046_wifi_channel:
      friendly_name: 'Light 046 Wifi Channel'
      value_template: "{{ state_attr('light.light_046', 'Wifi')['Channel'] }}"
    light_046_wifi_rssi:
      friendly_name: 'Light 046 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_046', 'Wifi')['RSSI'] }}"
    light_046_wifi_linkcount:
      friendly_name: 'Light 046 Wifi Link Count'
      value_template: "{{ state_attr('light.light_046', 'Wifi')['LinkCount'] }}"
    light_046_wifi_downtime:
      friendly_name: 'Light 046 Wifi Downtime'
      value_template: "{{ state_attr('light.light_046', 'Wifi')['Downtime'] }}"
    light_046_power:
      friendly_name: 'Light 046 Power'
      value_template: '{{ states.light.light_046.attributes.POWER }}'
