- platform: template
  sensors:
    light_020_time:
      friendly_name: 'Light 020 Time'
      value_template: '{{ states.light.light_020.attributes.Time }}'
    light_020_uptime:
      friendly_name: 'Light 020 Uptime'
      value_template: '{{ states.light.light_020.attributes.Uptime }}'
    light_020_vcc:
      friendly_name: 'Light 020 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_020.attributes.Vcc }}'
    light_020_heap:
      friendly_name: 'Light 020 Heap'
      value_template: '{{ states.light.light_020.attributes.Heap }}'
    light_020_sleepmode:
      friendly_name: 'Light 020 SleepMode'
      value_template: '{{ states.light.light_020.attributes.SleepMode }}'
    light_020_sleep:
      friendly_name: 'Light 020 Sleep'
      value_template: '{{ states.light.light_020.attributes.Sleep }}'
    light_020_loadavg:
      friendly_name: 'Light 020 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_020.attributes.LoadAvg }}'
    light_020_wifi_ssid:
      friendly_name: 'Light 020 Wifi SSId'
      value_template: "{{ state_attr('light.light_020', 'Wifi')['SSId'] }}"
    light_020_wifi_ap:
      friendly_name: 'Light 020 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_020', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_020', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_020', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_020', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_020', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_020', 'Wifi')['BSSId'] }}
        {% endif %}
    light_020_wifi_bssid:
      friendly_name: 'Light 020 Wifi BSSId'
      value_template: "{{ state_attr('light.light_020', 'Wifi')['BSSId'] }}"
    light_020_wifi_channel:
      friendly_name: 'Light 020 Wifi Channel'
      value_template: "{{ state_attr('light.light_020', 'Wifi')['Channel'] }}"
    light_020_wifi_rssi:
      friendly_name: 'Light 020 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_020', 'Wifi')['RSSI'] }}"
    light_020_wifi_linkcount:
      friendly_name: 'Light 020 Wifi Link Count'
      value_template: "{{ state_attr('light.light_020', 'Wifi')['LinkCount'] }}"
    light_020_wifi_downtime:
      friendly_name: 'Light 020 Wifi Downtime'
      value_template: "{{ state_attr('light.light_020', 'Wifi')['Downtime'] }}"
    light_020_power:
      friendly_name: 'Light 020 Power'
      value_template: '{{ states.light.light_020.attributes.POWER }}'
