- platform: template
  sensors:
    light_013_time:
      friendly_name: 'Light 013 Time'
      value_template: '{{ states.light.light_013.attributes.Time }}'
    light_013_uptime:
      friendly_name: 'Light 013 Uptime'
      value_template: '{{ states.light.light_013.attributes.Uptime }}'
    light_013_vcc:
      friendly_name: 'Light 013 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_013.attributes.Vcc }}'
    light_013_heap:
      friendly_name: 'Light 013 Heap'
      value_template: '{{ states.light.light_013.attributes.Heap }}'
    light_013_sleepmode:
      friendly_name: 'Light 013 SleepMode'
      value_template: '{{ states.light.light_013.attributes.SleepMode }}'
    light_013_sleep:
      friendly_name: 'Light 013 Sleep'
      value_template: '{{ states.light.light_013.attributes.Sleep }}'
    light_013_loadavg:
      friendly_name: 'Light 013 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_013.attributes.LoadAvg }}'
    light_013_wifi_ssid:
      friendly_name: 'Light 013 Wifi SSId'
      value_template: "{{ state_attr('light.light_013', 'Wifi')['SSId'] }}"
    light_013_wifi_ap:
      friendly_name: 'Light 013 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_013', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_013', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_013', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_013', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_013', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_013', 'Wifi')['BSSId'] }}
        {% endif %}
    light_013_wifi_bssid:
      friendly_name: 'Light 013 Wifi BSSId'
      value_template: "{{ state_attr('light.light_013', 'Wifi')['BSSId'] }}"
    light_013_wifi_channel:
      friendly_name: 'Light 013 Wifi Channel'
      value_template: "{{ state_attr('light.light_013', 'Wifi')['Channel'] }}"
    light_013_wifi_rssi:
      friendly_name: 'Light 013 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_013', 'Wifi')['RSSI'] }}"
    light_013_wifi_linkcount:
      friendly_name: 'Light 013 Wifi Link Count'
      value_template: "{{ state_attr('light.light_013', 'Wifi')['LinkCount'] }}"
    light_013_wifi_downtime:
      friendly_name: 'Light 013 Wifi Downtime'
      value_template: "{{ state_attr('light.light_013', 'Wifi')['Downtime'] }}"
    light_013_power:
      friendly_name: 'Light 013 Power'
      value_template: '{{ states.light.light_013.attributes.POWER }}'
