- platform: template
  sensors:
    light_023_time:
      friendly_name: 'Light 023 Time'
      value_template: '{{ states.light.light_023.attributes.Time }}'
    light_023_uptime:
      friendly_name: 'Light 023 Uptime'
      value_template: '{{ states.light.light_023.attributes.Uptime }}'
    light_023_vcc:
      friendly_name: 'Light 023 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_023.attributes.Vcc }}'
    light_023_heap:
      friendly_name: 'Light 023 Heap'
      value_template: '{{ states.light.light_023.attributes.Heap }}'
    light_023_sleepmode:
      friendly_name: 'Light 023 SleepMode'
      value_template: '{{ states.light.light_023.attributes.SleepMode }}'
    light_023_sleep:
      friendly_name: 'Light 023 Sleep'
      value_template: '{{ states.light.light_023.attributes.Sleep }}'
    light_023_loadavg:
      friendly_name: 'Light 023 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_023.attributes.LoadAvg }}'
    light_023_wifi_ssid:
      friendly_name: 'Light 023 Wifi SSId'
      value_template: "{{ state_attr('light.light_023', 'Wifi')['SSId'] }}"
    light_023_wifi_ap:
      friendly_name: 'Light 023 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_023', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_023', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_023', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_023', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_023', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_023', 'Wifi')['BSSId'] }}
        {% endif %}
    light_023_wifi_bssid:
      friendly_name: 'Light 023 Wifi BSSId'
      value_template: "{{ state_attr('light.light_023', 'Wifi')['BSSId'] }}"
    light_023_wifi_channel:
      friendly_name: 'Light 023 Wifi Channel'
      value_template: "{{ state_attr('light.light_023', 'Wifi')['Channel'] }}"
    light_023_wifi_rssi:
      friendly_name: 'Light 023 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_023', 'Wifi')['RSSI'] }}"
    light_023_wifi_linkcount:
      friendly_name: 'Light 023 Wifi Link Count'
      value_template: "{{ state_attr('light.light_023', 'Wifi')['LinkCount'] }}"
    light_023_wifi_downtime:
      friendly_name: 'Light 023 Wifi Downtime'
      value_template: "{{ state_attr('light.light_023', 'Wifi')['Downtime'] }}"
    light_023_power:
      friendly_name: 'Light 023 Power'
      value_template: '{{ states.light.light_023.attributes.POWER }}'
