- platform: template
  sensors:
    light_048_time:
      friendly_name: 'Light 048 Time'
      value_template: '{{ states.light.light_048.attributes.Time }}'
    light_048_uptime:
      friendly_name: 'Light 048 Uptime'
      value_template: '{{ states.light.light_048.attributes.Uptime }}'
    light_048_vcc:
      friendly_name: 'Light 048 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_048.attributes.Vcc }}'
    light_048_heap:
      friendly_name: 'Light 048 Heap'
      value_template: '{{ states.light.light_048.attributes.Heap }}'
    light_048_sleepmode:
      friendly_name: 'Light 048 SleepMode'
      value_template: '{{ states.light.light_048.attributes.SleepMode }}'
    light_048_sleep:
      friendly_name: 'Light 048 Sleep'
      value_template: '{{ states.light.light_048.attributes.Sleep }}'
    light_048_loadavg:
      friendly_name: 'Light 048 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_048.attributes.LoadAvg }}'
    light_048_wifi_ssid:
      friendly_name: 'Light 048 Wifi SSId'
      value_template: "{{ state_attr('light.light_048', 'Wifi')['SSId'] }}"
    light_048_wifi_ap:
      friendly_name: 'Light 048 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_048', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_048', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_048', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_048', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_048', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_048', 'Wifi')['BSSId'] }}
        {% endif %}
    light_048_wifi_bssid:
      friendly_name: 'Light 048 Wifi BSSId'
      value_template: "{{ state_attr('light.light_048', 'Wifi')['BSSId'] }}"
    light_048_wifi_channel:
      friendly_name: 'Light 048 Wifi Channel'
      value_template: "{{ state_attr('light.light_048', 'Wifi')['Channel'] }}"
    light_048_wifi_rssi:
      friendly_name: 'Light 048 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_048', 'Wifi')['RSSI'] }}"
    light_048_wifi_linkcount:
      friendly_name: 'Light 048 Wifi Link Count'
      value_template: "{{ state_attr('light.light_048', 'Wifi')['LinkCount'] }}"
    light_048_wifi_downtime:
      friendly_name: 'Light 048 Wifi Downtime'
      value_template: "{{ state_attr('light.light_048', 'Wifi')['Downtime'] }}"
    light_048_power:
      friendly_name: 'Light 048 Power'
      value_template: '{{ states.light.light_048.attributes.POWER }}'
