- platform: template
  sensors:
    light_029_time:
      friendly_name: 'Light 029 Time'
      value_template: '{{ states.light.light_029.attributes.Time }}'
    light_029_uptime:
      friendly_name: 'Light 029 Uptime'
      value_template: '{{ states.light.light_029.attributes.Uptime }}'
    light_029_vcc:
      friendly_name: 'Light 029 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_029.attributes.Vcc }}'
    light_029_heap:
      friendly_name: 'Light 029 Heap'
      value_template: '{{ states.light.light_029.attributes.Heap }}'
    light_029_sleepmode:
      friendly_name: 'Light 029 SleepMode'
      value_template: '{{ states.light.light_029.attributes.SleepMode }}'
    light_029_sleep:
      friendly_name: 'Light 029 Sleep'
      value_template: '{{ states.light.light_029.attributes.Sleep }}'
    light_029_loadavg:
      friendly_name: 'Light 029 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_029.attributes.LoadAvg }}'
    light_029_wifi_ssid:
      friendly_name: 'Light 029 Wifi SSId'
      value_template: "{{ state_attr('light.light_029', 'Wifi')['SSId'] }}"
    light_029_wifi_ap:
      friendly_name: 'Light 029 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_029', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_029', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_029', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_029', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_029', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_029', 'Wifi')['BSSId'] }}
        {% endif %}
    light_029_wifi_bssid:
      friendly_name: 'Light 029 Wifi BSSId'
      value_template: "{{ state_attr('light.light_029', 'Wifi')['BSSId'] }}"
    light_029_wifi_channel:
      friendly_name: 'Light 029 Wifi Channel'
      value_template: "{{ state_attr('light.light_029', 'Wifi')['Channel'] }}"
    light_029_wifi_rssi:
      friendly_name: 'Light 029 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_029', 'Wifi')['RSSI'] }}"
    light_029_wifi_linkcount:
      friendly_name: 'Light 029 Wifi Link Count'
      value_template: "{{ state_attr('light.light_029', 'Wifi')['LinkCount'] }}"
    light_029_wifi_downtime:
      friendly_name: 'Light 029 Wifi Downtime'
      value_template: "{{ state_attr('light.light_029', 'Wifi')['Downtime'] }}"
    light_029_power:
      friendly_name: 'Light 029 Power'
      value_template: '{{ states.light.light_029.attributes.POWER }}'
