- platform: template
  sensors:
    light_031_time:
      friendly_name: 'Light 031 Time'
      value_template: '{{ states.light.light_031.attributes.Time }}'
    light_031_uptime:
      friendly_name: 'Light 031 Uptime'
      value_template: '{{ states.light.light_031.attributes.Uptime }}'
    light_031_vcc:
      friendly_name: 'Light 031 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_031.attributes.Vcc }}'
    light_031_heap:
      friendly_name: 'Light 031 Heap'
      value_template: '{{ states.light.light_031.attributes.Heap }}'
    light_031_sleepmode:
      friendly_name: 'Light 031 SleepMode'
      value_template: '{{ states.light.light_031.attributes.SleepMode }}'
    light_031_sleep:
      friendly_name: 'Light 031 Sleep'
      value_template: '{{ states.light.light_031.attributes.Sleep }}'
    light_031_loadavg:
      friendly_name: 'Light 031 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_031.attributes.LoadAvg }}'
    light_031_wifi_ssid:
      friendly_name: 'Light 031 Wifi SSId'
      value_template: "{{ state_attr('light.light_031', 'Wifi')['SSId'] }}"
    light_031_wifi_ap:
      friendly_name: 'Light 031 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_031', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_031', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_031', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_031', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_031', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_031', 'Wifi')['BSSId'] }}
        {% endif %}
    light_031_wifi_bssid:
      friendly_name: 'Light 031 Wifi BSSId'
      value_template: "{{ state_attr('light.light_031', 'Wifi')['BSSId'] }}"
    light_031_wifi_channel:
      friendly_name: 'Light 031 Wifi Channel'
      value_template: "{{ state_attr('light.light_031', 'Wifi')['Channel'] }}"
    light_031_wifi_rssi:
      friendly_name: 'Light 031 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_031', 'Wifi')['RSSI'] }}"
    light_031_wifi_linkcount:
      friendly_name: 'Light 031 Wifi Link Count'
      value_template: "{{ state_attr('light.light_031', 'Wifi')['LinkCount'] }}"
    light_031_wifi_downtime:
      friendly_name: 'Light 031 Wifi Downtime'
      value_template: "{{ state_attr('light.light_031', 'Wifi')['Downtime'] }}"
    light_031_power:
      friendly_name: 'Light 031 Power'
      value_template: '{{ states.light.light_031.attributes.POWER }}'
