- platform: template
  sensors:
    light_047_time:
      friendly_name: 'Light 047 Time'
      value_template: '{{ states.light.light_047.attributes.Time }}'
    light_047_uptime:
      friendly_name: 'Light 047 Uptime'
      value_template: '{{ states.light.light_047.attributes.Uptime }}'
    light_047_vcc:
      friendly_name: 'Light 047 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_047.attributes.Vcc }}'
    light_047_heap:
      friendly_name: 'Light 047 Heap'
      value_template: '{{ states.light.light_047.attributes.Heap }}'
    light_047_sleepmode:
      friendly_name: 'Light 047 SleepMode'
      value_template: '{{ states.light.light_047.attributes.SleepMode }}'
    light_047_sleep:
      friendly_name: 'Light 047 Sleep'
      value_template: '{{ states.light.light_047.attributes.Sleep }}'
    light_047_loadavg:
      friendly_name: 'Light 047 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_047.attributes.LoadAvg }}'
    light_047_wifi_ssid:
      friendly_name: 'Light 047 Wifi SSId'
      value_template: "{{ state_attr('light.light_047', 'Wifi')['SSId'] }}"
    light_047_wifi_ap:
      friendly_name: 'Light 047 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_047', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_047', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_047', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_047', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_047', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_047', 'Wifi')['BSSId'] }}
        {% endif %}
    light_047_wifi_bssid:
      friendly_name: 'Light 047 Wifi BSSId'
      value_template: "{{ state_attr('light.light_047', 'Wifi')['BSSId'] }}"
    light_047_wifi_channel:
      friendly_name: 'Light 047 Wifi Channel'
      value_template: "{{ state_attr('light.light_047', 'Wifi')['Channel'] }}"
    light_047_wifi_rssi:
      friendly_name: 'Light 047 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_047', 'Wifi')['RSSI'] }}"
    light_047_wifi_linkcount:
      friendly_name: 'Light 047 Wifi Link Count'
      value_template: "{{ state_attr('light.light_047', 'Wifi')['LinkCount'] }}"
    light_047_wifi_downtime:
      friendly_name: 'Light 047 Wifi Downtime'
      value_template: "{{ state_attr('light.light_047', 'Wifi')['Downtime'] }}"
    light_047_power:
      friendly_name: 'Light 047 Power'
      value_template: '{{ states.light.light_047.attributes.POWER }}'
