- platform: template
  sensors:
    light_041_time:
      friendly_name: 'Light 041 Time'
      value_template: '{{ states.light.light_041.attributes.Time }}'
    light_041_uptime:
      friendly_name: 'Light 041 Uptime'
      value_template: '{{ states.light.light_041.attributes.Uptime }}'
    light_041_vcc:
      friendly_name: 'Light 041 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_041.attributes.Vcc }}'
    light_041_heap:
      friendly_name: 'Light 041 Heap'
      value_template: '{{ states.light.light_041.attributes.Heap }}'
    light_041_sleepmode:
      friendly_name: 'Light 041 SleepMode'
      value_template: '{{ states.light.light_041.attributes.SleepMode }}'
    light_041_sleep:
      friendly_name: 'Light 041 Sleep'
      value_template: '{{ states.light.light_041.attributes.Sleep }}'
    light_041_loadavg:
      friendly_name: 'Light 041 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_041.attributes.LoadAvg }}'
    light_041_wifi_ssid:
      friendly_name: 'Light 041 Wifi SSId'
      value_template: "{{ state_attr('light.light_041', 'Wifi')['SSId'] }}"
    light_041_wifi_ap:
      friendly_name: 'Light 041 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_041', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_041', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_041', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_041', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_041', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_041', 'Wifi')['BSSId'] }}
        {% endif %}
    light_041_wifi_bssid:
      friendly_name: 'Light 041 Wifi BSSId'
      value_template: "{{ state_attr('light.light_041', 'Wifi')['BSSId'] }}"
    light_041_wifi_channel:
      friendly_name: 'Light 041 Wifi Channel'
      value_template: "{{ state_attr('light.light_041', 'Wifi')['Channel'] }}"
    light_041_wifi_rssi:
      friendly_name: 'Light 041 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_041', 'Wifi')['RSSI'] }}"
    light_041_wifi_linkcount:
      friendly_name: 'Light 041 Wifi Link Count'
      value_template: "{{ state_attr('light.light_041', 'Wifi')['LinkCount'] }}"
    light_041_wifi_downtime:
      friendly_name: 'Light 041 Wifi Downtime'
      value_template: "{{ state_attr('light.light_041', 'Wifi')['Downtime'] }}"
    light_041_power:
      friendly_name: 'Light 041 Power'
      value_template: '{{ states.light.light_041.attributes.POWER }}'
