- platform: template
  sensors:
    light_019_time:
      friendly_name: 'Light 019 Time'
      value_template: '{{ states.light.light_019.attributes.Time }}'
    light_019_uptime:
      friendly_name: 'Light 019 Uptime'
      value_template: '{{ states.light.light_019.attributes.Uptime }}'
    light_019_vcc:
      friendly_name: 'Light 019 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_019.attributes.Vcc }}'
    light_019_heap:
      friendly_name: 'Light 019 Heap'
      value_template: '{{ states.light.light_019.attributes.Heap }}'
    light_019_sleepmode:
      friendly_name: 'Light 019 SleepMode'
      value_template: '{{ states.light.light_019.attributes.SleepMode }}'
    light_019_sleep:
      friendly_name: 'Light 019 Sleep'
      value_template: '{{ states.light.light_019.attributes.Sleep }}'
    light_019_loadavg:
      friendly_name: 'Light 019 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_019.attributes.LoadAvg }}'
    light_019_wifi_ssid:
      friendly_name: 'Light 019 Wifi SSId'
      value_template: "{{ state_attr('light.light_019', 'Wifi')['SSId'] }}"
    light_019_wifi_ap:
      friendly_name: 'Light 019 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_019', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_019', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_019', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_019', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_019', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_019', 'Wifi')['BSSId'] }}
        {% endif %}
    light_019_wifi_bssid:
      friendly_name: 'Light 019 Wifi BSSId'
      value_template: "{{ state_attr('light.light_019', 'Wifi')['BSSId'] }}"
    light_019_wifi_channel:
      friendly_name: 'Light 019 Wifi Channel'
      value_template: "{{ state_attr('light.light_019', 'Wifi')['Channel'] }}"
    light_019_wifi_rssi:
      friendly_name: 'Light 019 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_019', 'Wifi')['RSSI'] }}"
    light_019_wifi_linkcount:
      friendly_name: 'Light 019 Wifi Link Count'
      value_template: "{{ state_attr('light.light_019', 'Wifi')['LinkCount'] }}"
    light_019_wifi_downtime:
      friendly_name: 'Light 019 Wifi Downtime'
      value_template: "{{ state_attr('light.light_019', 'Wifi')['Downtime'] }}"
    light_019_power:
      friendly_name: 'Light 019 Power'
      value_template: '{{ states.light.light_019.attributes.POWER }}'
