- platform: template
  sensors:
    light_002_time:
      friendly_name: 'Light 002 Time'
      value_template: '{{ states.light.light_002.attributes.Time }}'
    light_002_uptime:
      friendly_name: 'Light 002 Uptime'
      value_template: '{{ states.light.light_002.attributes.Uptime }}'
    light_002_vcc:
      friendly_name: 'Light 002 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_002.attributes.Vcc }}'
    light_002_heap:
      friendly_name: 'Light 002 Heap'
      value_template: '{{ states.light.light_002.attributes.Heap }}'
    light_002_sleepmode:
      friendly_name: 'Light 002 SleepMode'
      value_template: '{{ states.light.light_002.attributes.SleepMode }}'
    light_002_sleep:
      friendly_name: 'Light 002 Sleep'
      value_template: '{{ states.light.light_002.attributes.Sleep }}'
    light_002_loadavg:
      friendly_name: 'Light 002 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_002.attributes.LoadAvg }}'
    light_002_wifi_ssid:
      friendly_name: 'Light 002 Wifi SSId'
      value_template: "{{ state_attr('light.light_002', 'Wifi')['SSId'] }}"
    light_002_wifi_ap:
      friendly_name: 'Light 002 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_002', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_002', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_002', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_002', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_002', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_002', 'Wifi')['BSSId'] }}
        {% endif %}
    light_002_wifi_bssid:
      friendly_name: 'Light 002 Wifi BSSId'
      value_template: "{{ state_attr('light.light_002', 'Wifi')['BSSId'] }}"
    light_002_wifi_channel:
      friendly_name: 'Light 002 Wifi Channel'
      value_template: "{{ state_attr('light.light_002', 'Wifi')['Channel'] }}"
    light_002_wifi_rssi:
      friendly_name: 'Light 002 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_002', 'Wifi')['RSSI'] }}"
    light_002_wifi_linkcount:
      friendly_name: 'Light 002 Wifi Link Count'
      value_template: "{{ state_attr('light.light_002', 'Wifi')['LinkCount'] }}"
    light_002_wifi_downtime:
      friendly_name: 'Light 002 Wifi Downtime'
      value_template: "{{ state_attr('light.light_002', 'Wifi')['Downtime'] }}"
    light_002_power:
      friendly_name: 'Light 002 Power'
      value_template: '{{ states.light.light_002.attributes.POWER }}'
