- platform: template
  sensors:
    light_005_time:
      friendly_name: 'Light 005 Time'
      value_template: '{{ states.light.light_005.attributes.Time }}'
    light_005_uptime:
      friendly_name: 'Light 005 Uptime'
      value_template: '{{ states.light.light_005.attributes.Uptime }}'
    light_005_vcc:
      friendly_name: 'Light 005 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.light_005.attributes.Vcc }}'
    light_005_heap:
      friendly_name: 'Light 005 Heap'
      value_template: '{{ states.light.light_005.attributes.Heap }}'
    light_005_sleepmode:
      friendly_name: 'Light 005 SleepMode'
      value_template: '{{ states.light.light_005.attributes.SleepMode }}'
    light_005_sleep:
      friendly_name: 'Light 005 Sleep'
      value_template: '{{ states.light.light_005.attributes.Sleep }}'
    light_005_loadavg:
      friendly_name: 'Light 005 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.light_005.attributes.LoadAvg }}'
    light_005_wifi_ssid:
      friendly_name: 'Light 005 Wifi SSId'
      value_template: "{{ state_attr('light.light_005', 'Wifi')['SSId'] }}"
    light_005_wifi_ap:
      friendly_name: 'Light 005 Wifi AP'
      value_template: >-
        {% if state_attr('light.light_005', 'Wifi')['BSSId'] | string == '02:9F:C2:24:32:82' %}
          Office AP
        {% elif state_attr('light.light_005', 'Wifi')['BSSId'] | string == '02:9F:C2:24:30:D7' %}
          Mezzanine AP
        {% elif state_attr('light.light_005', 'Wifi')['BSSId'] | string == '02:9F:C2:24:2D:F1' %}
          Tool Crib AP
        {% elif state_attr('light.light_005', 'Wifi')['BSSId'] | string == '0E:EC:DA:B7:E0:7D' %}
          B-Side South AP
        {% elif state_attr('light.light_005', 'Wifi')['BSSId'] | string == 'C6:FB:E4:44:66:C4' %}
          B-Side North AP
        {% else %}
          {{ state_attr('light.light_005', 'Wifi')['BSSId'] }}
        {% endif %}
    light_005_wifi_bssid:
      friendly_name: 'Light 005 Wifi BSSId'
      value_template: "{{ state_attr('light.light_005', 'Wifi')['BSSId'] }}"
    light_005_wifi_channel:
      friendly_name: 'Light 005 Wifi Channel'
      value_template: "{{ state_attr('light.light_005', 'Wifi')['Channel'] }}"
    light_005_wifi_rssi:
      friendly_name: 'Light 005 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.light_005', 'Wifi')['RSSI'] }}"
    light_005_wifi_linkcount:
      friendly_name: 'Light 005 Wifi Link Count'
      value_template: "{{ state_attr('light.light_005', 'Wifi')['LinkCount'] }}"
    light_005_wifi_downtime:
      friendly_name: 'Light 005 Wifi Downtime'
      value_template: "{{ state_attr('light.light_005', 'Wifi')['Downtime'] }}"
    light_005_power:
      friendly_name: 'Light 005 Power'
      value_template: '{{ states.light.light_005.attributes.POWER }}'
