- platform: mqtt
  name: "Elab Arch North IR Receiver"
  state_topic: "stat/i3/inside/elab/accent/arch-north/RESULT"
  availability_topic: "tele/i3/inside/elab/accent/arch-north/LWT"
  payload_available: "Online"
  payload_unavailable: "Offline"
  value_template: >
    {% if "Irreceived" in value_json %}
      {{ value_json["Irreceived"]["Data"] }}
    {% endif %}
  force_update: True

- platform: mqtt
  name: "Elab Arch South IR Receiver"
  state_topic: "stat/i3/inside/elab/accent/arch-south/RESULT"
  availability_topic: "tele/i3/inside/elab/accent/arch-south/LWT"
  payload_available: "Online"
  payload_unavailable: "Offline"
  value_template: >
    {% if "Irreceived" in value_json %}
      {{ value_json["Irreceived"]["Data"] }}
    {% endif %}
  force_update: True