# - platform: mqtt
#   name: ""
#   state_topic: ""
#   unit_of_measurement: ""
#   value_template: '{{ value_json.thing }}' or '{{ value_json["thing"]["nestedthing"] }}' for nested json

# Weather prediction
- platform: yr
  name: "Weather"
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    #- fog
    - cloudiness
    #- lowClouds
    #- mediumClouds
    #- highClouds
    - dewpointTemperature

- platform: mqtt
  name: "Doorbell"
  state_topic: "stat/i3/inside/commons/normal-doorbell/press"
  force_update: True

- platform: mqtt
  name: "sonoff_RSSI"
  state_topic: "tele/i3/inside/commons/traffic-light/STATE"
  unit_of_measurement: "%"
  value_template: '{{ value_json["Wifi"]["RSSI"] }}'
  force_update: True
  
- platform: mqtt
  name: "sonoff_humid"
  state_topic: "tele/i3/inside/commons/traffic-light/SENSOR"
  unit_of_measurement: "%"
  value_template: '{{ value_json["AM2301"]["Humidity"] }}'
  force_update: True
  
- platform: mqtt
  name: "sonoff_temp"
  state_topic: "tele/i3/inside/commons/traffic-light/SENSOR"
  unit_of_measurement: "°C"
  value_template: '{{ value_json["AM2301"]["Temperature"] }}'
  force_update: True

- platform: command_line
  name: "i3 Power Meter"
  command: "python3 /home/homeassistant/.homeassistant/power_meter.py"
  unit_of_measurement: "kWh"
  scan_interval: "60"

- platform: template
  sensors:
    commons_temp_diff:
      friendly_name: "Commons ceiling-ground temp diff"
      unit_of_measurement: "°C"
      value_template: >-
        {% if states.sensor.ceiling_cluster_temperature.state | string == "unknown" or states.sensor.ground_cluster_temperature.state | string == "unknown" %}
          0.0
        {% else %}
          {{((states.sensor.ceiling_cluster_temperature.state | float) - (states.sensor.ground_cluster_temperature.state | float)) | round(2)}}
        {% endif %}
    weather_pressure_kpa:
      friendly_name: "Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.Weather_pressure') | multiply(1/10) | round(1) }}"

- platform: mqtt
  name: "Garage Door Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/13690294"
  force_update: True

- platform: mqtt
  name: "Window Elab Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/10359814"
  force_update: True

- platform: mqtt
  name: "Window Craft Room Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/3923078"
  force_update: True

- platform: mqtt
  name: "Window 1 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/14343686"
  force_update: True

- platform: mqtt
  name: "Window 2 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/4780358"
  force_update: True

- platform: mqtt
  name: "Window 3 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/16269958"
  force_update: True

- platform: mqtt
  name: "Window 4 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/663390"
  force_update: True

- platform: mqtt
  name: "Window 5 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/6415366"
  force_update: True

- platform: mqtt
  name: "Window 6 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/15124278"
  force_update: True

- platform: mqtt
  name: "Window 7 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/10228742"
  force_update: True

- platform: mqtt
  name: "Window 8 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/15100166"
  force_update: True

- platform: mqtt
  name: "Window 9 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/11974662"
  force_update: True

- platform: mqtt
  name: "Window 10 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/16758790"
  force_update: True

- platform: mqtt
  name: "Shutdown button"
  state_topic: "cmnd/i3/automation/shutdown"
  force_update: True

- platform: mqtt
  name: "Classroom East Light Switch"
  state_topic: "cmnd/i3/inside/classroom/lights-east/POWER"
  force_update: True

- platform: template
  sensors:
    recycle_day:
      entity_id: sensor.time_date
      friendly_name: "Recycle Day?"
      value_template: >-
        {% if ((now().weekday() == 2) and now().time().hour >= 12) or ((now().weekday() == 3) and now().time().hour <= 3) %}
          Yes
        {% else %}
          No
        {%- endif %}
    meeting_time:
      entity_id: sensor.time_date
      friendly_name: "Meeting time?"
      value_template: >-
        {% if (now().weekday() == 1) and (now().date().day <= 22) and (now().time().hour >= 19) and (now().time().hour < 21) %}
          Yes
        {% else %}
          No
        {%- endif %}

- platform: template
  sensors:
    ceiling_outside_temp_diff:
      friendly_name: "Commons ceiling-outside temp diff"
      unit_of_measurement: "°C"
      value_template: >-
        {% if states.sensor.ceiling_cluster_temperature.state | string == "unknown" or states.sensor.weather_temperature.state | string == "unknown" %}
          0.0
        {% else %}
          {{((states.sensor.ceiling_cluster_temperature.state | float) - (states.sensor.weather_temperature.state | float)) | round(2)}}
        {% endif %}

- platform: mqtt
  name: "Water Cooler Flow Counts"
  state_topic: "stat/i3/inside/commons/water-cooler/flow"
  force_update: True

- platform: mqtt
  name: "Front Door Panel Battery Voltage"
  state_topic: "tele/i3/inside/commons/front-door-indicator/batteryVoltage"
  unit_of_measurement: "V"
  force_update: True

- platform: template
  sensors:
    open_for_tours:
      friendly_name: "Open For Tours"
      entity_id: sensor.time_date
      value_template: >-
        {% if ((now().weekday() == 4) and now().time().hour >= 18 and now().time().hour <= 20) %}
          on
        {% else %}
          off
        {%- endif %}

- platform: mqtt
  name: "Emergency Lights Reset Button"
  state_topic: "cmnd/i3/automation/emergencyLightsOn"
  force_update: True

- platform: mqtt
  name: "Compressed Air Line Pressure 01"
  state_topic: "stat/i3/inside/sensors/air-line-pressure-01/pressure"
  unit_of_measurement: "psi"
  force_update: True
  availability_topic: "tele/i3/inside/sensors/air-line-pressure-01/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Compressed Air Line Pressure 02"
  state_topic: "stat/i3/inside/sensors/air-line-pressure-02/pressure"
  unit_of_measurement: "psi"
  force_update: True
  availability_topic: "tele/i3/inside/sensors/air-line-pressure-02/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'
