# - platform: mqtt
#   name: ""
#   state_topic: ""
#   unit_of_measurement: ""
#   value_template: '{{ value_json.thing }}' or '{{ value_json["thing"]["nestedthing"] }}' for nested json

# Weather prediction
- platform: yr
  name: "Weather"
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    #- fog
    - cloudiness
    #- lowClouds
    #- mediumClouds
    #- highClouds
    - dewpointTemperature

- platform: mqtt
  name: "Doorbell"
  state_topic: "stat/i3/inside/commons/normal-doorbell/press"
  force_update: True
  
- platform: mqtt
  name: "openEVSE Amps"
  state_topic: "tele/i3/inside/commons/openevse/amp"
  unit_of_measurement: "milliamps"
  force_update: True
  
- platform: mqtt
  name: "openEVSE Watt Seconds"
  state_topic: "tele/i3/inside/commons/openevse/wh"
  unit_of_measurement: "Watt seconds"
  force_update: True
  
- platform: mqtt
  name: "openEVSE State"
  state_topic: "tele/i3/inside/commons/openevse/state"
  force_update: True
  
- platform: mqtt
  name: "sonoff_RSSI"
  state_topic: "tele/i3/inside/commons/traffic-light/STATE"
  unit_of_measurement: "%"
  value_template: '{{ value_json["Wifi"]["RSSI"] }}'
  force_update: True
  
- platform: mqtt
  name: "sonoff_humid"
  state_topic: "tele/i3/inside/commons/traffic-light/SENSOR"
  unit_of_measurement: "%"
  value_template: '{{ value_json["DHT22"]["Humidity"] }}'
  force_update: True
  
- platform: mqtt
  name: "sonoff_temp"
  state_topic: "tele/i3/inside/commons/traffic-light/SENSOR"
  unit_of_measurement: "°C"
  value_template: '{{ value_json["DHT22"]["Temperature"] }}'
  force_update: True
  
- platform: template
  sensors:
    ev_charger_state:
      friendly_name: "EV Charger Status"
      value_template: >-
        {% if is_state('sensor.openEVSE_State', '1') %}
          Unplugged
        {% elif is_state('sensor.openEVSE_State', '2') %}
          Plugged_in
        {% elif is_state('sensor.openEVSE_State', '3') %}
          Charging
        {% else %}
          Unknown
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.openEVSE_State', '1') %}
          mdi:power-plug-off
        {% elif is_state('sensor.openEVSE_State', '2') %}
          mdi:power-plug
        {% elif is_state('sensor.openEVSE_State', '3') %}
          mdi:battery-charging
        {% else %}
          mdi:help-circle
        {% endif %}
    ev_charger_amps:
      friendly_name: "EV Charger Amps"
      unit_of_measurement: 'Amps'
      value_template: "{{ states('sensor.openEVSE_Amps')|float / 1000 | round(1) }}"
      icon_template: >-
         {% if states('sensor.openEVSE_Amps')|float > 0 %}
            mdi:battery-charging
          {% else %}
            mdi:power-plug-off
          {% endif %}
    ev_charger_wh:
      friendly_name: "EV Charger kWh"
      unit_of_measurement: 'kWh'
      value_template: "{{ states('sensor.openEVSE_Watt_Seconds') | multiply(1/3600000) | round(2) }}"

    weather_pressure_kpa:
      friendly_name: "Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ states('sensor.Weather_pressure') | multiply(1/10) | round(1) }}"

- platform: command_line
  name: "i3 Power Meter"
  command: "python3 /home/homeassistant/.homeassistant/power_meter.py"
  unit_of_measurement: "kWh"
  scan_interval: "60"

- platform: mqtt
  name: "Ground Cluster Temperature"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/bme280"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'
  force_update: True

- platform: mqtt
  name: "Ground Cluster Pressure"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/bme280"
  unit_of_measurement: "Pa"
  value_template: '{{ value_json.Pressure }}'
  force_update: True

- platform: mqtt
  name: "Ground Cluster Humidity"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/bme280"
  unit_of_measurement: "%"
  value_template: '{{ value_json.Humidity }}'
  force_update: True                                                   

- platform: mqtt
  name: "Ground Cluster Lux"
  state_topic: "tele/i3/inside/commons/ground-sensor-cluster/lux"
  unit_of_measurement: "lux"
  value_template: '{{ value_json.Lux }}'
  force_update: True

- platform: mqtt
  name: "Ceiling Cluster Temperature"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/bme280"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'
  force_update: True

- platform: mqtt
  name: "Ceiling Cluster Pressure"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/bme280"
  unit_of_measurement: "Pa"
  value_template: '{{ value_json.Pressure }}'
  force_update: True

- platform: mqtt
  name: "Ceiling Cluster Humidity"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/bme280"
  unit_of_measurement: "%"
  value_template: '{{ value_json.Humidity }}'
  force_update: True

- platform: mqtt
  name: "Ceiling Cluster Lux"
  state_topic: "tele/i3/inside/commons/ceiling-sensor-cluster/lux"
  unit_of_measurement: "lux"
  value_template: '{{ value_json.Lux }}'
  force_update: True

- platform: mqtt
  name: "Fablab Cluster Temperature"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/bme280"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'
  force_update: True

- platform: mqtt
  name: "Fablab Cluster Pressure"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/bme280"
  unit_of_measurement: "Pa"
  value_template: '{{ value_json.Pressure }}'
  force_update: True

- platform: mqtt
  name: "Fablab Cluster Humidity"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/bme280"
  unit_of_measurement: "%"
  value_template: '{{ value_json.Humidity }}'
  force_update: True

- platform: mqtt
  name: "Fablab Cluster Lux"
  state_topic: "tele/i3/inside/fablab/sensor-cluster/lux"
  unit_of_measurement: "lux"
  value_template: '{{ value_json.Lux }}'
  force_update: True

- platform: mqtt
  name: "Bumblebee Tube Time"
  state_topic: "stat/i3/inside/laser-zone/bumblebee-timer/laser-tube-time"
  unit_of_measurement: "millisecond"
  force_update: True

- platform: mqtt
  name: "Wolverine Tube Time"
  state_topic: "stat/i3/inside/laser-zone/wolverine-timer/laser-tube-time"
  unit_of_measurement: "millisecond"
  force_update: True

- platform: mqtt
  name: "Snapple Vending Temperature"
  state_topic: "tele/i3/inside/commons/snapple-vending-compress/SENSOR"
  unit_of_measurement: "°C"
  value_template: '{{ value_json["DS18B20"]["Temperature"] }}'
  force_update: True

- platform: mqtt
  name: "Snapple Vending Compressor Amps"
  state_topic: "tele/i3/inside/commons/snapple-vending-compress/ENERGY"
  unit_of_measurement: "Amps"
  value_template: '{{ value_json.Current }}'
  force_update: True

- platform: mqtt
  name: "Snapple Vending Compressor Voltage"
  state_topic: "tele/i3/inside/commons/snapple-vending-compress/ENERGY"
  unit_of_measurement: "Volts"
  value_template: '{{ value_json.Voltage }}'
  force_update: True

- platform: template
  sensors:
    commons_temp_diff:
      friendly_name: "Commons ceiling-ground temp diff"
      unit_of_measurement: "°C"
      value_template: >-
        {% if states.sensor.ceiling_cluster_temperature.state | string == "unknown" or states.sensor.ground_cluster_temperature.state | string == "unknown" %}
          0.0
        {% else %}
          {{((states.sensor.ceiling_cluster_temperature.state | float) - (states.sensor.ground_cluster_temperature.state | float)) | round(2)}}
        {% endif %}

- platform: mqtt
  name: "Garage Door Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/13690294"
  force_update: True

- platform: mqtt
  name: "Window Elab Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/10359814"
  force_update: True

- platform: mqtt
  name: "Window Craft Room Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/3923078"
  force_update: True

- platform: mqtt
  name: "Window 1 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/14343686"
  force_update: True

- platform: mqtt
  name: "Window 2 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/4780358"
  force_update: True

- platform: mqtt
  name: "Window 3 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/16269958"
  force_update: True

- platform: mqtt
  name: "Window 4 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/663390"
  force_update: True

- platform: mqtt
  name: "Window 5 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/6415366"
  force_update: True

- platform: mqtt
  name: "Window 6 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/15124278"
  force_update: True

- platform: mqtt
  name: "Window 7 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/10228742"
  force_update: True

- platform: mqtt
  name: "Window 8 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/15100166"
  force_update: True

- platform: mqtt
  name: "Window 9 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/11974662"
  force_update: True

- platform: mqtt
  name: "Window 10 Open"
  state_topic: "tele/i3/inside/infrastructure/433-rf-echo/16758790"
  force_update: True

- platform: mqtt
  name: "Shutdown button"
  state_topic: "cmnd/i3/automation/shutdown"
  force_update: True

- platform: mqtt
  name: "Office Thermostat Ambient Temperature"
  state_topic: "tele/i3/inside/office/thermostat/bme280"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.Temperature }}'
  force_update: True

- platform: mqtt
  name: "Office Thermostat Ambient Pressure"
  state_topic: "tele/i3/inside/office/thermostat/bme280"
  unit_of_measurement: "Pa"
  value_template: '{{ value_json.Pressure }}'
  force_update: True

- platform: mqtt
  name: "Office Thermostat Ambient Humidity"
  state_topic: "tele/i3/inside/office/thermostat/bme280"
  unit_of_measurement: "%"
  value_template: '{{ value_json.Humidity }}'
  force_update: True

- platform: mqtt
  name: "Office Thermostat Target Temperature"
  state_topic: "tele/i3/inside/office/thermostat/request"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.TargetTemp }}'
  force_update: True

- platform: mqtt
  name: "Office Thermostat Requested State"
  state_topic: "tele/i3/inside/office/thermostat/request"
  value_template: '{{ value_json.requested }}'
  force_update: True

- platform: mqtt
  name: "Office Thermostat Requested Fan State"
  state_topic: "tele/i3/inside/office/thermostat/request"
  value_template: '{{ value_json.fan }}'
  force_update: True

- platform: mqtt
  name: "Office Thermostat Active State"
  state_topic: "tele/i3/inside/office/thermostat/output"
  value_template: '{{ value_json.output }}'
  force_update: True

- platform: mqtt
  name: "Office Thermostat Active Fan State"
  state_topic: "tele/i3/inside/office/thermostat/output"
  value_template: '{{ value_json.fan }}'
  force_update: True

- platform: mqtt
  name: "Classroom East Light Switch"
  state_topic: "cmnd/i3/inside/classroom/lights-east/POWER"
  force_update: True

- platform: template
  sensors:
    full_spectrum:
      friendly_name: "Full Spectrum"
      value_template: >-
        {% if is_state('device_tracker.full_spectrum', 'home') %}
          online
        {% elif is_state('device_tracker.full_spectrum', 'not_home') %}
          offline
        {% endif %}
    asterisk:
      friendly_name: "asterisk"
      value_template: >-
        {% if is_state('device_tracker.asterisk', 'home') %}
          online
        {% elif is_state('device_tracker.asterisk', 'not_home') %}
          offline
        {% endif %}
    skynet:
      friendly_name: "Skynet"
      value_template: >-
        {% if is_state('device_tracker.skynet', 'home') %}
          online
        {% elif is_state('device_tracker.skynet', 'not_home') %}
          offline
        {% endif %}
    minecraft:
      friendly_name: "Minecraft"
      value_template: >-
        {% if is_state('device_tracker.minecraft', 'home') %}
          online
        {% elif is_state('device_tracker.minecraft', 'not_home') %}
          offline
        {% endif %}
    mcclellan:
      friendly_name: "McClellan"
      value_template: >-
        {% if is_state('device_tracker.mcclellan', 'home') %}
          online
        {% elif is_state('device_tracker.mcclellan', 'not_home') %}
          offline
        {% endif %}
    rostock_max:
      friendly_name: "Rostock_MAX"
      value_template: >-
        {% if is_state('device_tracker.rostock_max', 'home') %}
          online
        {% elif is_state('device_tracker.rostock_max', 'not_home') %}
          offline
        {% endif %}

- platform: template
  sensors:
    recycle_day:
      friendly_name: "Recycle Day?"
      value_template: >-
        {% if ((now().weekday() == 2) and now().time().hour >= 12) or ((now().weekday() == 3) and now().time().hour <= 3) %}
          Yes
        {% else %}
          No
        {%- endif %}

- platform: template
  sensors:
    ceiling_outside_temp_diff:
      friendly_name: "Commons ceiling-outside temp diff"
      unit_of_measurement: "°C"
      value_template: >-
        {% if states.sensor.ceiling_cluster_temperature.state | string == "unknown" or states.sensor.weather_temperature.state | string == "unknown" %}
          0.0
        {% else %}
          {{((states.sensor.ceiling_cluster_temperature.state | float) - (states.sensor.weather_temperature.state | float)) | round(2)}}
        {% endif %}

- platform: mqtt
  name: "Water Cooler Flow Counts"
  state_topic: "stat/i3/inside/commons/water-cooler/flow"
  force_update: True

- platform: mqtt
  name: "Front Door Panel Battery Voltage"
  state_topic: "tele/i3/inside/commons/front-door-indicator/batteryVoltage"
  force_update: True

- platform: template
  sensors:
    open_for_tours:
      friendly_name: "Open For Tours"
      value_template: >-
        {% if ((now().weekday() == 4) and now().time().hour >= 18 and now().time().hour <= 21) %}
          on
        {% else %}
          off
        {%- endif %}
