- platform: mqtt
  name: "Glass Door Lock Sensor"
  state_topic: "stat/i3/inside/classroom/glass-door/lock"
  # on means open, off means closed
  payload_on: "UNLOCKED"
  payload_off: "LOCKED"
  # availability_topic: ""
  # payload_available: "online"
  # payload_not_available: "offline"
  device_class: lock
  force_update: True

- platform: mqtt
  name: "Glass Door Open Sensor"
  state_topic: "stat/i3/inside/classroom/glass-door/open"
  # on means open, off means closed
  payload_on: "OPEN"
  payload_off: "CLOSED"
  # availability_topic: "stat/i3/classroom/glassDoor/lock"
  # payload_available: "online"
  # payload_not_available: "offline"
  device_class: door
  force_update: True

# - platform: mqtt
#   name: "Garage Door Lock Sensor"
#   state_topic: "stat/i3/inside/commons/garage-door/lock"
#   # on means open, off means closed
#   payload_on: "UNLOCKED"
#   payload_off: "LOCKED"
#   # availability_topic: ""
#   # payload_available: "online"
#   # payload_not_available: "offline"
#   device_class: opening
#   force_update: True

- platform: mqtt
  name: "Machine Shop Motion Sensor"
  state_topic: "stat/i3/inside/machine-shop/motion-sensor/motion"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
  force_update: True

- platform: mqtt
  name: "Large Bathroom Motion Sensor"
  state_topic: "stat/i3/inside/large-bathroom/motion-sensor/motion"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
  force_update: True

- platform: mqtt
  name: "Small Bathroom Motion Sensor"
  state_topic: "stat/i3/inside/small-bathroom/motion-sensor/motion"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
  force_update: True

- platform: mqtt
  name: "Snapple Vending Compressor Power"
  state_topic: "tele/i3/inside/commons/snapple-vending-compress/STATE"
  availability_topic: "tele/i3/inside/commons/snapple-vending-compress/LWT"
  value_template: '{{ value_json.POWER }}'
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: power
  force_update: True

- platform: mqtt
  name: "Argon Tank Sensor"
  state_topic: "stat/i3/inside/weld-zone/tank-sensors/argon"
  # on means open, off means closed
  payload_on: "OPEN"
  payload_off: "CLOSED"
  device_class: opening
  force_update: True

- platform: mqtt
  name: "Front Door Panel Power"
  state_topic: "tele/i3/inside/commons/front-door-indicator/LWT"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: power
  force_update: True

- platform: mqtt
  name: "Front Door Lock"
  state_topic: "stat/i3/inside/commons/front-door/lock"
  # on means open, off means closed
  payload_on: "UNLOCKED"
  payload_off: "LOCKED"
  # availability_topic: ""
  # payload_available: "online"
  # payload_not_available: "offline"
  device_class: door
  force_update: True
  