if:
  condition:
    binary_sensor.is_on: laser_state
  then:
    if:
      condition:
        binary_sensor.is_on: ${led_type}_state
      then:
        - light.turn_on:
            id: ${led_type}_led
            red: 10%
            green: 60%
            blue: 0%
            brightness: 80%
      else:
        - light.turn_on:
            id: ${led_type}_led
            red: 60%
            green: 10%
            blue: 0%
            brightness: 80%
  else:
    if:
      condition:
        and:
          - binary_sensor.is_on: ${led_type}_state
      then:
        - light.turn_on:
            id: ${led_type}_led
            red: 50%
            green: 0%
            blue: 80%
            brightness: 40%
      else:
        - light.turn_off:
            id: ${led_type}_led
