packages: 
  board: !include packages/board_d1_mini.yaml
  base_components: !include packages/esp_home_components.yaml

substitutions:
  pretty_name: "${laser_name} Status Lights"
  ui_name: "${pretty_name}"
  icon: "mdi:text-box-check"

web_server:
  include_internal: true

light:
  - platform: neopixelbus
    id: led_strip
    type: GRB
    variant: WS2811
    pin: GPIO13
    num_leds: 8
    internal: true
  - platform: partition
    id: chiller_led
    name: "Chiller"
    segments:
      - id: led_strip
        from: 0
        to: 0
    internal: true
  - platform: partition
    id: exhaust_fan_led
    name: "Exhaust Fan"
    segments:
      - id: led_strip
        from: 1
        to: 1
    internal: true
  - platform: partition
    id: exhaust_gate_led
    name: "Exhaust Gate"
    segments:
      - id: led_strip
        from: 2
        to: 2
    internal: true
  - platform: partition
    id: air_compressor_led
    name: "Air Compressor"
    segments:
      - id: led_strip
        from: 3
        to: 3
    internal: true
  - platform: partition
    id: air_compressor_valve_led
    name: "Air Compressor Valve"
    segments:
      - id: led_strip
        from: 4
        to: 4
    restore_mode: ALWAYS_OFF
    internal: true

binary_sensor:
  - id: laser_state
    platform: homeassistant
    entity_id: "switch.${laser_name}_relay"
    on_state:
      - !include { file: laser_cutter_status_lights_subtemplate.yaml, vars: { led_type: chiller } }
      - !include { file: laser_cutter_status_lights_subtemplate.yaml, vars: { led_type: exhaust_fan } }
      - !include { file: laser_cutter_status_lights_subtemplate.yaml, vars: { led_type: exhaust_gate } }
      - !include { file: laser_cutter_status_lights_subtemplate.yaml, vars: { led_type: air_compressor } }
    internal: true
  - id: chiller_state
    platform: homeassistant
    entity_id: "switch.${laser_name}_chiller_power"
    on_state:
      - !include { file: laser_cutter_status_lights_subtemplate.yaml, vars: { led_type: chiller } }
    internal: true
  - id: exhaust_fan_state
    platform: homeassistant
    entity_id: "switch.laser_exhaust_fan_fan"
    on_state:
      - !include { file: laser_cutter_status_lights_subtemplate.yaml, vars: { led_type: exhaust_fan } }
    internal: true
  - id: exhaust_gate_state
    platform: homeassistant
    entity_id: "binary_sensor.laser_exhaust_gates_${laser_name}_gate"
    on_state:
      - !include { file: laser_cutter_status_lights_subtemplate.yaml, vars: { led_type: exhaust_gate } }
    internal: true
  - id: air_compressor_state
    platform: homeassistant
    entity_id: "switch.air_compressor_relay"
    on_state:
      - !include { file: laser_cutter_status_lights_subtemplate.yaml, vars: { led_type: air_compressor } }
    internal: true
