packages:
  package: !include sonoff_basic_switch.yaml

output:
  - platform: gpio
    id: led_1_output
    pin:
      number: GPIO14
      inverted: True

light:
  - platform: binary
    name: "${pretty_name} LED"
    output: led_1_output
    id: led_1

binary_sensor:
  - name: "${pretty_name} Button"
    platform: gpio
    pin:
      number: 4
      mode: INPUT_PULLUP
      inverted: False
    on_press:
      then:
        - switch.toggle: relay_1
        - light.toggle: led_1
