# Need to use this include syntax instead of packages to overwrite the
# default switch with restore_mode: ALWAYS_ON
<<: !include sonoff_s31_switch.yaml

binary_sensor:
  - name: "${pretty_name} Button"
    platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: True

switch:
  - name: "${ui_name}"
    id: relay_1
    icon: "${icon}"
    platform: gpio
    pin:
      number: 12
      inverted: False
    restore_mode: ALWAYS_ON
