packages:
  board: !include packages/board_esp01_1m.yaml
  base_components: !include packages/esp_home_components.yaml

status_led:
  pin:
    number: GPIO14
    inverted: True

output:

binary_sensor:
  - name: "Button"
    platform: gpio
    pin:
      number: 4
      mode: INPUT_PULLUP
      inverted: False
    on_press:
      - switch.toggle: relay_1

switch:
  - platform: gpio
    pin:
      number: 12
      inverted: False
    id: relay_1
    name: "${ui_name}"
    icon: "${icon}"
    restore_mode: RESTORE_DEFAULT_OFF
