wifi:
  ssid: !secret wifi_ssid_i3
  password: !secret wifi_pass_i3
  use_address: "${ip_address}"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${pretty_name} Address"
    ssid:
      name: "${pretty_name} Connected SSID"
    bssid:
      name: "${pretty_name} Connected BSSID"
    mac_address:
      name: "${pretty_name} Mac Wifi Address"

sensor:
  - !include wifi_signal.yaml
  - !include uptime.yaml
