- alias: Emergency lights reset daily
  trigger:
  - platform: time
    at: '12:00:00'
  - platform: time
    at: '00:00:00'
  action:
    - service: script.turn_on
      entity_id: script.emergency_lights_reset

- alias: Emergency lights on when all other lights are off
  trigger:
    platform: state
    entity_id: group.shop_lights
    from: 'on'
    to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.emergency_lights_reset

- alias: Classroom sign on at sunset
  trigger:
  - platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.classroom_sign

- alias: Classroom sign off at sunrise
  trigger:
  - platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: switch.classroom_sign

- alias: Machine Shop Motion ON 
  trigger:
    platform: state
    entity_id: binary_sensor.machine_shop_motion_sensor
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: group.machine_shop_lights
    state: 'off'
    for:
      seconds: 5
  action:
    - service: light.turn_on
      entity_id: group.machine_shop_lights
    - service: mqtt.publish
      data:
        topic: "cmnd/i3/inside/commons/led-matrix/display"
        payload: "^SI see you there"

#- alias: Machine Shop Motion OFF 
#  trigger:
#    platform: state
#    entity_id: binary_sensor.machine_shop_motion_sensor
#    from: 'on'
#    to: 'off'
#    for:
#      hours: 1
#  action:
#    service: light.turn_off
#    entity_id: group.machine_shop_lights

- alias: Air Compressor Valve ON
  trigger:
  - platform: state
    entity_id: switch.Air_Compressor
    from: 'off'
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.Air_Compressor_Valve

- alias: Air Compressor Valve OFF
  trigger:
  - platform: state
    entity_id: switch.Air_Compressor
    from: 'on'
    to: 'off'
    for: 
      seconds: 2
  action:
    service: switch.turn_off
    entity_id: switch.Air_Compressor_Valve

- alias: Disco Mode ON
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/commons/disco/POWER
    payload: "ON"
  action:
    - service: light.turn_on
      entity_id: 
        - light.Chandelier01
        - light.Chandelier02
    - service: switch.turn_on
      entity_id: switch.disco_spotlights

- alias: Disco Mode OFF
  trigger:
  - platform: mqtt
    topic: stat/i3/inside/commons/disco/POWER
    payload: "OFF"
  action:
    - service: light.turn_off
      entity_id: 
        - light.Chandelier01
        - light.Chandelier02
    - service: switch.turn_off
      entity_id: switch.disco_spotlights

# - alias: Who turned out the lights?
#   trigger:
#     - platform: state
#       entity_id: group.shop_lights
#       from: 'on'
#       to: 'off'
#   action:
#     service: notify.slack_statusbots
#     data:
#       message: "Hey! Who turned out the lights?"

- alias: Fab lab fan status sign on
  trigger:
    - platform: state
      entity_id: fan.flv_fan
      to: 'on'
  action:
    service: mqtt.publish
    data:
      topic: "cmnd/i3/commons/16seg/display"
      payload: "FAB LAB FAN ON"

- alias: Fab lab fan status sign off
  trigger:
    - platform: state
      entity_id: fan.flv_fan
      to: 'off'
  action:
    service: mqtt.publish
    data:
      topic: "cmnd/i3/commons/16seg/display"
      payload: "FAB LAB FAN OFF"

- alias: Large Bathroom Motion ON 
  trigger:
    platform: state
    entity_id: binary_sensor.large_bathroom_motion_sensor
    to: 'on'
  condition:
    condition: state
    entity_id: light.LightLargeBathroom
    state: 'off'
    for:
      seconds: 5
  action:
    - service: light.turn_on
      entity_id: light.LightLargeBathroom
    - service: switch.turn_on
      entity_id: switch.Large_Bathroom_Vent_Fan

- alias: Large Bathroom Motion OFF 
  trigger:
    platform: state
    entity_id: binary_sensor.large_bathroom_motion_sensor
    to: 'off'
    for:
      minutes: 10
  action:
    - service: light.turn_off
      entity_id: light.LightLargeBathroom
    - service: switch.turn_off
      entity_id: switch.Large_Bathroom_Vent_Fan

- alias: Small Bathroom Motion ON 
  trigger:
    platform: state
    entity_id: binary_sensor.small_bathroom_motion_sensor
    to: 'on'
  condition:
    condition: state
    entity_id: light.Small_Bathroom_Light
    state: 'off'
    for:
      seconds: 5
  action:
    service: light.turn_on
    entity_id: light.Small_Bathroom_Light

- alias: Small Bathroom Motion OFF 
  trigger:
    platform: state
    entity_id: binary_sensor.small_bathroom_motion_sensor
    to: 'off'
    for:
      minutes: 15
  action:
    service: light.turn_off
    entity_id: light.Small_Bathroom_Light

- alias: Paint box fan timeout
  trigger:
    platform: state
    entity_id: switch.paint_box_vent
    to: 'on'
    for:
      minutes: 60
  action:
    service: switch.turn_off
    entity_id: switch.paint_box_vent

- alias: Ceiling fans ON if Temp Difference
  trigger:
    platform: numeric_state
    entity_id: sensor.commons_temp_diff
    above: 0.5
    for:
      minutes: 1
  condition:
    condition: state
    entity_id: group.shop_lights
    state: 'on'
  action:
    - service: fan.turn_on
      entity_id: fan.CommonsCeilingFans
    - service: fan.turn_on
      entity_id: fan.LaserCeilingFan

- alias: Front door panel off alert
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_panel_power
      to: 'off'
  action:
    service: notify.slack_statusbots
    data:
      message: "Alert! Front door panel is OFFLINE"

- alias: Front door panel back on alert
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_panel_power
      from: 'off'
      to: 'on'
  action:
    service: notify.slack_statusbots
    data:
      message: "Front door panel is back online"

- alias: Front door panel low voltage
  trigger:
    - platform: numeric_state
      entity_id: sensor.front_door_panel_battery_voltage
      below: 12.0
      for:
        minutes: 5
  action:
    service: notify.slack_statusbots
    data:
      message: "Alert! Front door panel voltage is low ({{states.sensor.front_door_panel_battery_voltage.state}} V)"

- alias: Hass notify mqtt on reboot
  trigger: 
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "stat/i3/automation/hass"
        payload: "Home assistant has started"
    - service: shell_command.refresh_mqtt

- alias: Traffic moist
  trigger:
    platform: numeric_state
    entity_id: sensor.Ground_Cluster_bme280_Humidity
    above: 75
    for:
      minutes: 3
  action:
    - service: light.turn_off
      entity_id: light.LightTrafficGreen
    - service: light.turn_off
      entity_id: light.LightTrafficYellow
    - service: light.turn_off
      entity_id: light.LightTrafficRed

- alias: Traffic medium
  trigger:
    platform: numeric_state
    entity_id: sensor.Ground_Cluster_bme280_Humidity
    above: 40
    below: 75
    for:
      minutes: 3
  action:
    - service: light.turn_off
      entity_id: light.LightTrafficGreen
    - service: light.turn_on
      entity_id: light.LightTrafficYellow
    - service: light.turn_off
      entity_id: light.LightTrafficRed

- alias: Traffic dry
  trigger:
    platform: numeric_state
    entity_id: sensor.Ground_Cluster_bme280_Humidity
    below: 40
    for:
      minutes: 3
  action:
    - service: light.turn_on
      entity_id: light.LightTrafficGreen
    - service: light.turn_off
      entity_id: light.LightTrafficYellow
    - service: light.turn_off
      entity_id: light.LightTrafficRed

- alias: Dooridor and Hall Lights Sync On
  trigger:
    platform: state
    entity_id: light.Classroom_Lights_East
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.Dooridor_Lights

- alias: Dooridor and Hall Lights Sync Off
  trigger:
    platform: state
    entity_id: light.Classroom_Lights_East
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.Dooridor_Lights

- alias: Classroom Lights Sync On
  trigger:
    platform: mqtt
    topic: cmnd/i3/inside/classroom/lights-east/POWER
    payload: 'TOGGLE'
  condition: 
    condition: state
    entity_id: light.classroom_lights_east
    state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.Classroom_Lights_West
    - service: light.turn_on
      entity_id: light.hallway_light

- alias: Classroom Lights Sync Off
  trigger:
    platform: mqtt
    topic: cmnd/i3/inside/classroom/lights-east/POWER
    payload: 'TOGGLE'
  condition: 
    condition: state
    entity_id: light.classroom_lights_east
    state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.Classroom_Lights_West
    - service: light.turn_off
      entity_id: light.hallway_light

- alias: Recycle Light On
  trigger:
    platform: state
    entity_id: sensor.recycle_day
    to: "Yes"
  action:
    service: switch.turn_on
    entity_id: switch.Recycle_Notification_Light

- alias: Recycle Light Off
  trigger:
    platform: state
    entity_id: sensor.recycle_day
    to: "No"
  action:
    service: switch.turn_off
    entity_id: switch.Recycle_Notification_Light

#- alias: Tweet photo from camera
#  initial_state: 'off'
#  trigger:
#    # this is just a temporary topic sent by the disco button
#    platform: mqtt
#    topic: info/i3/atari2600/pressed
#    payload: "pressed 2"
#  action:
#    - service: script.turn_on
#      entity_id: script.tweet_image
#    - service: automation.turn_off
#      entity_id: automation.tweet_photo_from_camera

- alias: Complain if genie not plugged inside
  trigger:
    platform: state
    entity_id: sensor.genie_charge_state
    to: "Not plugged in"
    for:
      hours: 6
  action:
   service: notify.slack_statusbots
   data:
     message: "The genie has been unplugged for over 6 hours"

- alias: Small bathroom lights sync ON A
  trigger:
    - platform: state
      entity_id: light.small_bathroom_light
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: light.small_bathroom_shower_light
    state: 'off'
    for:
      seconds: 2
  action:
    - service: light.turn_on
      entity_id: light.small_bathroom_shower_light

- alias: Small bathroom lights sync OFF A
  trigger:
    - platform: state
      entity_id: light.small_bathroom_light
      from: 'on'
      to: 'off'
  condition:
    condition: state
    entity_id: light.small_bathroom_shower_light
    state: 'on'
    for:
      seconds: 2
  action:
    - service: light.turn_off
      entity_id: light.small_bathroom_shower_light

- alias: Small bathroom lights sync ON B
  trigger:
    - platform: state
      entity_id: light.small_bathroom_shower_light
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: light.small_bathroom_light
    state: 'off'
    for:
      seconds: 2
  action:
    - service: light.turn_on
      entity_id: light.small_bathroom_light

- alias: Small bathroom lights sync OFF B
  trigger:
    - platform: state
      entity_id: light.small_bathroom_shower_light
      from: 'on'
      to: 'off'
  condition:
    condition: state
    entity_id: light.small_bathroom_light
    state: 'on'
    for:
      seconds: 2
  action:
    - service: light.turn_off
      entity_id: light.small_bathroom_light

- alias: Small Bathroom Fan Timeout 
  trigger:
    platform: state
    entity_id: switch.small_bathroom_vent_fan
    to: 'on'
    for:
      minutes: 30
  action:
    - service: switch.turn_off
      entity_id: light.small_bathroom_vent_fan

- alias: Exhaust Fan Auto On
  trigger:
    platform: numeric_state
    entity_id: sensor.ceiling_outside_temp_diff
    above: 1
    for:
      minutes: 15
  condition:
    condition: state
    entity_id: input_select.winter_or_summer
    state: 'Summer'
  action:
    - service: fan.turn_on
      entity_id: fan.CNCCeilingExhaust
    - service: fan.turn_on
      entity_id: fan.SouthCeilingExhaust

- alias: Input_text to LED matrix
  trigger:
    platform: state
    entity_id: input_text.led_matrix_input
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/i3/inside/commons/led-matrix/display"
        payload_template: "^S{{states('input_text.led_matrix_input')}}"

