- alias: B Side Office Lights Motion ON 
  trigger:
    - platform: state
      entity_id: binary_sensor.b_side_office_motion
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: light.b_side_office_light
    state: 'off'
    for:
      seconds: 10
  action:
    - service: light.turn_on
      entity_id: light.b_side_office_light

- alias: B Side Office Lights Motion OFF 
  trigger:
    - platform: state
      entity_id: binary_sensor.b_side_office_motion
      to: 'off'
      for:
        minutes: 10
  action:
    - service: light.turn_off
      entity_id: light.B_Side_Office_Light

- alias: B Side Lights Button ON
  trigger:
    - platform: state
      entity_id: binary_sensor.b_side_lightswitch_on
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: group.b_side_lights

- alias: B Side Lights Button OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.b_side_lightswitch_off
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: group.b_side_lights
