- alias: B Side Office Lights Motion ON 
  trigger:
    - platform: state
      entity_id: binary_sensor.b_side_office_motion
      to: 'on'
  condition:
    condition: state
    entity_id: light.b_side_office_light
    state: 'off'
    for:
      seconds: 10
  action:
    - service: light.turn_on
      entity_id: light.b_side_office_light

- alias: B Side Office Lights Motion OFF 
  trigger:
    - platform: state
      entity_id: binary_sensor.b_side_office_motion
      to: 'off'
      for:
        minutes: 10
  action:
    - service: light.turn_off
      entity_id: light.B_Side_Office_Light
