- alias: Front door lock open timer start
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_lock
      to: 'open'
  action:
    - service: timer.start
      entity_id: timer.front_door_lock

- alias: Front door lock
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.front_door_lock
  condition:
    condition: state
    entity_id: binary_sensor.front_door_lock
    state: 'open'
  action:
  - service: notify.slack_statusbots
    data:
      message: "Front door has been left open for the past 5 minutes."
  - service: timer.start
    entity_id: timer.front_door_lock

- alias: Front door lock closed
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_lock
      to: 'closed'
  condition:
    condition: state
    entity_id: timer.front_door_lock
    state: 'active'
  action:
  - service: notify.slack_statusbots
    data:
      message: "Front door is closed again."