- alias: MQTT echo test
  trigger:
  - platform: mqtt
    topic: "stat/i3/inside/machine-shop/motion-sensor/motion"
  - platform: mqtt
    topic: "stat/i3/inside/large-bathroom/motion-sensor/motion"
  - platform: mqtt
    topic: "stat/i3/inside/small-bathroom/motion-sensor/motion"
  action:
    service: mqtt.publish
    data:
      topic: "hass/test/mqtt-echo-test"
      payload_template: "{\"motion\": {\"large_bath\": \"{{ states.binary_sensor.large_bathroom_motion_sensor.state }}\", \"small_bath\": \"{{ states.binary_sensor.small_bathroom_motion_sensor.state }}\", \"machine_shop\": \"{{ states.binary_sensor.machine_shop_motion_sensor.state}}\"}}"
