- alias: Shutdown the whole space
  trigger:
    platform: mqtt
    topic: cmnd/i3/automation/shutdown
    payload: 'DOWNSHUT'
  action:
    - service: mqtt.publish
      data:
        topic: "stat/i3/automation/hass"
        payload: "Space shutdown triggered"
    - service: homeassistant.turn_off
      entity_id: group.shutdown
    - service: script.turn_on
      entity_id: script.warehouse_lights_out
