# Publish 'clear' to the shutdown button topic to prevent accidental triggering
- alias: Reset shutdown button mqtt
  trigger:
    platform: state
    entity_id: sensor.Shutdown_button
    to: 'DOWNSHUT'
    for:
      seconds: 5
  action:
    service: mqtt.publish
    data:
      topic: "cmnd/i3/automation/shutdown"
      payload: "clear"

- alias: Shutdown the whole space
  trigger:
    platform: state
    entity_id: sensor.Shutdown_button
    to: 'DOWNSHUT'
  action:
    - service: mqtt.publish
      data:
        topic: "stat/i3/automation/hass"
        payload: "Space shutdown triggered"
    - service: homeassistant.turn_off
      entity_id: group.shutdown
