# logging breaks sonoff basics magically
logger:
  level: INFO

ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  version: 3
  auth:
    username: esphome
    password: !secret ota_password
    type: digest # remove/optional after 2027.1.0
  include_internal: True

esphome:
  friendly_name: "${pretty_name}"

api:
  encryption:
    key: !secret api_encryption_key

packages:
  wifi: !include wifi.yaml
  wifi_signal: !include wifi_signal.yaml
  uptime: !include uptime.yaml

button:
  - platform: restart
    name: "Restart"
