# captive_portal:

# logging breaks sonoff basics magically
logger:
  level: INFO

ota:
  platform: esphome

web_server:
  port: 80

api:

packages:
  wifi: !include wifi.yaml
  wifi_signal: !include wifi_signal.yaml
  uptime: !include uptime.yaml

switch:
  - platform: restart
    name: "${pretty_name} Restart"
