wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  min_auth_mode: WPA2
  use_address: "${ip_address}"
  reboot_timeout: 12h
  ap:
    ssid: "${pretty_name}"
    password: !secret wifi_password
    ap_timeout: 5min

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    bssid:
      name: "Connected BSSID"
    mac_address:
      name: "MAC Address"
