wifi:
  networks:
    - ssid: !secret wifi_ssid_i3
      password: !secret wifi_pass_i3
#  use_address: "${ip_address}"
#  INSTEAD OF ip_address in the top level device config, just do the merge config thing like this:
#wifi:
#  use_address: "10.13.107.251"
  reboot_timeout: 12h
  ap:
    ssid: "${pretty_name}"
    password: !secret wifi_pass_i3
    ap_timeout: 5min

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${pretty_name} Address"
    ssid:
      name: "${pretty_name} Connected SSID"
    bssid:
      name: "${pretty_name} Connected BSSID"
    mac_address:
      name: "${pretty_name} Mac Wifi Address"
