packages:
  package: !include common/button_box_6_long_press.yaml

substitutions:
  device_name: "a-side-switch-east-3"
  pretty_name: "A-Side Switch East 3"
  target_1: "light.row_1_lights"
  target_2: "light.row_2_lights"
  target_3: "light.row_3_lights"
  ip_address: "10.13.107.25"
