packages:
  package: !include common/sonoff_sv.yaml

substitutions:
  device_name: "a-side-main-keypad-watchdog"
  pretty_name: "A-Side Main Keypad Watchdog"
  ui_name: "${pretty_name}"
  icon: "mdi:dog-side"
  ip_address: !secret a_side_kp_watchdog_ip
