# Linknode D1
packages: 
  board: !include common/packages/board_d1_mini.yaml
  base_components: !include common/packages/esp_home_components.yaml

substitutions:
  device_name: "air-compressor"
  pretty_name: "Air Compressor"

web_server:
  include_internal: true

binary_sensor:
  - name: "Relay State"
    id: relay_input
    platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: true
    internal: true

switch:
  - name: "Relay"
    id: relay
    platform: template
    lambda: |-
      return id(relay_input).state;
    turn_on_action:
      - switch.turn_on: button_on
      - delay: 350ms
      - switch.turn_off: button_on
    turn_off_action:
      - switch.turn_on: button_off
      - delay: 350ms
      - switch.turn_off: button_off
  - name: "Power On"
    id: button_on
    platform: gpio
    pin:
      number: 4
      inverted: false
    internal: true
  - name: "Power Off"
    id: button_off
    platform: gpio
    pin:
      number: 5
      inverted: false
    internal: true
