packages:
  package: !include common/sonoff_sv.yaml

substitutions:
  device_name: "b-side-office-keypad-watchdog"
  pretty_name: "B-Side Office Keypad Watchdog"
  ui_name: "${pretty_name}"
  icon: "mdi:dog-side"
  ip_address: !secret b_side_kp_watchdog_ip
