packages:
  package: !include common/treatlife_3way_light.yaml

substitutions:
  device_name: "b-side-office-west-switch"
  pretty_name: "B-Side Office West Switch"
  ui_name: "Lights"
  icon: "mdi:lightbulb"
