packages:
  package: !include common/sonoff_sv.yaml
  
substitutions:
  device_name: "chandelier-02"
  pretty_name: "Chandelier 02"
  ui_name: "${pretty_name}"
  icon: "mdi:chandelier"
  ip_address: 10.13.107.27
