packages:
  package: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "classroom-west-switch"
  pretty_name: "Classroom West Switch"
  ui_name: "Lights"
  icon: "mdi:lightbulb"
