packages:
  package: !include common/treatlife_ss01s_fan.yaml


substitutions:
  device_name: "commons_ceiling_fan_lightswitch"
  pretty_name: "Commons Ceiling Fan Switch"
  ui_name: "Commons Ceiling Fan"
  icon: "mdi:fan"
  ip_address: 10.13.107.180