packages:
  package: !include common/treatlife_ss01s_fan.yaml

substitutions:
  device_name: "commons-ceiling-fan-switch"
  pretty_name: "Commons Ceiling Fan Switch"
  ui_name: "Fans"
  icon: "mdi:fan"
