esphome:
  name: commons-led-matrix
  friendly_name: commons-led-matrix

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0MuSv8gUbxzY/Uw6KokEfbqy5Ku9ErNUThtXJGssp94="

ota:
  password: "207a53a01a4edcbeb7f18fca5fc5b85e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Commons-Led-Matrix"
    password: "RhXHIqBJsfgH"

captive_portal:
    