# See https://www.i3detroit.org/wiki/Dust_Collector_Automation

packages: 
  board: !include common/packages/board_d1_mini.yaml
  base_components: !include common/packages/esp_home_components.yaml

substitutions:
  button_num: "02"
  device_name: "dc-buttons-${button_num}"
  pretty_name: "Dust Collector Buttons ${button_num}"
  target_1_on: "esphome.dust_collector_controller_dc_on"
  target_1_off: "esphome.dust_collector_controller_dc_off"
  ip_address: "10.13.107.195"

binary_sensor:
  - name: "${pretty_name} Button 1"
    platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - homeassistant.service:
          service: ${target_1_on}
  - name: "${pretty_name} Button 2"
    platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - homeassistant.service:
          service: ${target_1_off}
