packages:
  package: !include common/treatlife_ss01s_light.yaml


substitutions:
  device_name: "elab_lightswitch"
  pretty_name: "Elab Lightswitch"
  ui_name: "Elab Lights"
  icon: "mdi:lightbulb"
  ip_address: "10.13.107.189"