<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "elab_lightswitch"
  pretty_name: "Elab Lightswitch"
  ui_name: "Elab Lights"
  icon: "mdi:lightbulb"