packages:
  package: !include common/sonoff_basic_switch.yaml
  
substitutions:
  device_name: fab-lab-vent-fan
  pretty_name: "Fab Lab Vent Fan"
  ui_name: "${pretty_name}"
  icon: "mdi:fan"
  ip_address: 10.13.107.256
