packages:
  package: !include common/treatlife_ss01s_no_relay.yaml

substitutions:
  device_name: "hallway-alt-switch"
  pretty_name: "Hallway Alt Switch"
  ui_name: "Hallway Alt Switch"
  target_1: "light.classroom_lights"
