packages:
  package: !include common/d1_pir_sensor.yaml
  
substitutions:
  device_name: "large-bathroom-motion-sensor"
  pretty_name: "Large Bathroom Motion Sensor"
  ui_name: "Motion"
  icon: "mdi:motion-sensor"
