packages:
  package: !include common/treatlife_ss01s_fan.yaml


substitutions:
  device_name: "laser_ceiling_fan_lightswitch"
  pretty_name: "Laser Zone Ceiling Fan Switch"
  ui_name: "Laser Zone Ceiling Fan"
  icon: "mdi:fan"
