packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_102"
  pretty_name: "Light 102"
  ui_name: "Light 102"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.66
