packages:
  package: !include common/button_box_4_long_press.yaml


substitutions:
  device_name: "a_side_lightswitch_west_02"
  pretty_name: "A-Side Lightswitch West 02"
  target_1: "group.row_4_lights"
  target_2: "group.row_5_lights"
  ip_address: 10.13.107.123
