packages:
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "light_030"
  pretty_name: "Light 030"
  ui_name: "Light 030"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.216
