<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_022"
  pretty_name: "Light 022"
  ui_name: "Light 022"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.172
