packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_020"
  pretty_name: "Light 020"
  ui_name: "Light 020"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.50
