packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_023"
  pretty_name: "Light 023"
  ui_name: "Light 023"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.235
