packages:
  package: !include common/ct-065w.yaml


substitutions:
  device_name: "light_015"
  pretty_name: "Light 015"
  ui_name: "Light 015"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.84
