<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_074"
  pretty_name: "Light 074"
  ui_name: "Light 074"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.256
