packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_025"
  pretty_name: "Light 025"
  ui_name: "Light 025"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.13
