packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_106"
  pretty_name: "Light 106"
  ui_name: "Light 106"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.171
