<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_003"
  pretty_name: "Light 003"
  ui_name: "Light 003"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.104
