<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_056"
  pretty_name: "Light 056"
  ui_name: "Light 056"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.101
