packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_103"
  pretty_name: "Light 103"
  ui_name: "Light 103"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.186
