packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_053"
  pretty_name: "Light 053"
  ui_name: "Light 053"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.229
