packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_094"
  pretty_name: "Light 094"
  ui_name: "Light 094"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.202
