<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_005"
  pretty_name: "Light 005"
  ui_name: "Light 005"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.117
