packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_071"
  pretty_name: "Light 071"
  ui_name: "Light 071"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.54
