<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_052"
  pretty_name: "Light 052"
  ui_name: "Light 052"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.190
