packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_033"
  pretty_name: "Light 033"
  ui_name: "Light 033"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.168
