<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_043"
  pretty_name: "Light 043"
  ui_name: "Light 043"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.50
