<<: !include common/ct-065w.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_012"
  pretty_name: "Light 012"
  ui_name: "Light 012"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.237
