<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_042"
  pretty_name: "Light 042"
  ui_name: "Light 042"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.107
