<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_021"
  pretty_name: "Light 021"
  ui_name: "Light 021"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.141
