<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_041"
  pretty_name: "Light 041"
  ui_name: "Light 041"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.159
