<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "treehouse_light"
  pretty_name: "Treehouse Light"
  ui_name: "Treehouse Light"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.230
