packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_007"
  pretty_name: "Light 007"
  ui_name: "Light 007"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.193
