packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_034"
  pretty_name: "Light 034"
  ui_name: "Light 034"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.198
