packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_046"
  pretty_name: "Light 046"
  ui_name: "Light 046"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.226
