packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_058"
  pretty_name: "Light 058"
  ui_name: "Light 058"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.256
