packages:
  package: !include common/button_box_6_long_press.yaml


substitutions:
  device_name: "b_side_lightswitch_02"
  pretty_name: "B-Side Lightswitch 02"
  target_1: "group.b_side_lights"
  target_2: "group.wood_shop_lights"
  target_3: "group.kiln_jewelry_lights"
  ip_address: 10.13.107.156
