<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_047"
  pretty_name: "Light 047"
  ui_name: "Light 047"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.157
