packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_010"
  pretty_name: "Light 010"
  ui_name: "Light 010"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.130
