<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_024"
  pretty_name: "Light 024"
  ui_name: "Light 024"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.210
