<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_001"
  pretty_name: "Light 001"
  ui_name: "Light 001"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.133
