<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_031"
  pretty_name: "Light 031"
  ui_name: "Light 031"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.105
