<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_029"
  pretty_name: "Light 029"
  ui_name: "Light 029"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.42
