<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_045"
  pretty_name: "Light 045"
  ui_name: "Light 045"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.191
