packages:
# is electrodragon

  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_018"
  pretty_name: "Light 018"
  ui_name: "Light 018"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.201
