<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_065"
  pretty_name: "Light 065"
  ui_name: "Light 065"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.256
