<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_104"
  pretty_name: "Light 104"
  ui_name: "Light 104"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.179
