packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_100"
  pretty_name: "Light 100"
  ui_name: "Light 100"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.21
