<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_090"
  pretty_name: "Light 090"
  ui_name: "Light 090"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.11
