packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_002"
  pretty_name: "Light 002"
  ui_name: "Light 002"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.78
