<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_044"
  pretty_name: "Light 044"
  ui_name: "Light 044"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.93
