packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_057"
  pretty_name: "Light 057"
  ui_name: "Light 057"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.256
