<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_011"
  pretty_name: "Light 011"
  ui_name: "Light 011"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.98
