packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_008"
  pretty_name: "Light 008"
  ui_name: "Light 008"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.154
