<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_019"
  pretty_name: "Light 019"
  ui_name: "Light 019"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.107
