packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_064"
  pretty_name: "Light 064"
  ui_name: "Light 064"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.32
