packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_049"
  pretty_name: "Light 049"
  ui_name: "Light 049"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.165
