packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_054"
  pretty_name: "Light 054"
  ui_name: "Light 054"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.41
