<<: !include common/ct-065w.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_013"
  pretty_name: "Light 013"
  ui_name: "Light 013"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.144
