packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_050"
  pretty_name: "Light 050"
  ui_name: "Light 050"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.192
