packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_032"
  pretty_name: "Light 032"
  ui_name: "Light 032"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.148
