packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_076"
  pretty_name: "Light 076"
  ui_name: "Light 076"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.47
