packages:
  package: !include common/sonoff_basic_light.yaml


substitutions:
  device_name: "light_026"
  pretty_name: "Light 026"
  ui_name: "Light 026"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.158
