packages:
  package: !include common/ct-065w


substitutions:
  device_name: "light_017"
  pretty_name: "Light 017"
  ui_name: "Light 017"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.127
