<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "light_006"
  pretty_name: "Light 006"
  ui_name: "Light 006"
  icon: "mdi:lightbulb"
  ip_address: 10.13.107.93
