packages:
  package: !include common/sonoff_basic_switch.yaml
  
substitutions:
  device_name: machine-shop-ceiling-fan
  pretty_name: "Machine Shop Ceiling Fan"
  ui_name: "${pretty_name}"
  icon: "mdi:fan"
  ip_address: 10.13.107.256
  