<<: !include common/treatlife_ss01s_fan.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "machine_shop_exhaust_fan_lightswitch"
  pretty_name: "Machine Shop Exhaust Fan Switch"
  ui_name: "Machine Shop Exhaust Fan"
  icon: "mdi:fan"
  ip_address: "10.13.107.218"