packages: 
  base_components: !include common/packages/esp_home_components.yaml

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: nodemcuv2
  build_path: "./build/${device_name}"

substitutions:
  device_name: "machine-sho-light-switch-02"
  pretty_name: "Machine Shop Light Switch 02"
  ui_name: "${pretty_name}"
  ip_address: "10.13.107.256"
  target_1: "group.machine_shop_lights"
  target_2: "switch.machine_shoo_ceiling_fan"

binary_sensor:
  - name: "${pretty_name} Button 1"
    platform: gpio
    pin:
      number: 4
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - homeassistant.service:
          service: homeassistant.turn_on
          data:
            entity_id: "${target_1}"
  - name: "${pretty_name} Button 2"
    platform: gpio
    pin:
      number: 5
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - homeassistant.service:
          service: homeassistant.turn_off
          data:
            entity_id: "${target_1}"
  - name: "${pretty_name} Button 3"
    platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - homeassistant.service:
          service: homeassistant.turn_on
          data:
            entity_id: "${target_2}"
  - name: "${pretty_name} Button 4"
    platform: gpio
    pin:
      number: 2
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - homeassistant.service:
          service: homeassistant.turn_off
          data: 
            entity_id: "${target_2}"
