packages:
  package: !include common/treatlife_ss01s_light.yaml


substitutions:
  device_name: "media_lab_lightswitch"
  pretty_name: "Media Lab Lightswitch"
  ui_name: "Media Lab Lights"
  icon: "mdi:lightbulb"
