<<: !include common/treatlife_3way_ss02.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "media_lab_south_lightswitch"
  pretty_name: "Media Lab South Lightswitch"
  ui_name: "Media Lab Lights"
  icon: "mdi:lightbulb"
