packages:
  package: !include common/treatlife_3way_ss02.yaml


substitutions:
  device_name: "media_lab_south_lightswitch"
  pretty_name: "Media Lab South Lightswitch"
  ui_name: "Media Lab Lights"
  icon: "mdi:lightbulb"
