packages:
  package: !include common/treatlife_3way_ss02.yaml


substitutions:
  device_name: "media_lab_north_lightswitch"
  pretty_name: "Media Lab North Lightswitch"
  ui_name: "Media Lab North Lightswitch"
  icon: "mdi:lightbulb"
