packages:
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "overhead-light-93"
  pretty_name: "Overhead Light 93"
  ui_name: "Light"
  icon: "mdi:lightbulb"
  ip_address: "10.13.107.10"
