packages:
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "overhead-light-56"
  pretty_name: "Emergency Light 56"
  ui_name: "Emergency Light 56"
  icon: "mdi:lightbulb"
