packages:
  package: !include common/airgradient_indoor.yaml

substitutions:
  device_name: "paint-zone-airgradient"
  pretty_name: "Paint Zone AirGradient"
  # https://www.airgradient.com/documentation/kb/pm-batch-correction-factors
  # PMS5003-2025072003646
  pm_2_5_scaling_factor: "0.004629"
  pm_2_5_intercept: "true"
  co2_offset: "40"
