packages:
  package: !include common/button_box_4.yaml

substitutions:
  device_name: "paint-zone-switch"
  pretty_name: "Paint Zone Switch"
  target_1: "light.paint_zone_lights"
  target_2: "light.paint_zone_lights"
  ip_address: "10.13.107.251"
