packages:
  package: !include common/button_box_2.yaml

substitutions:
  device_name: "sewing-zone-north-main-switch"
  pretty_name: "Sewing Zone North Main Switch"
  target_1: "light.sewing_zone_main_lights_lights"
  ip_address: "10.13.107.150"
