packages:
  package: !include common/treatlife_3way_light.yaml

substitutions:
  device_name: "sewing-zone-fitting-room-light"
  pretty_name: "Sewing Zone Fitting Room Light"
  ui_name: "Light"
  icon: "mdi:lightbulb"
