packages:
  package: !include common/button_box_2.yaml

substitutions:
  device_name: "sewing-zone-south-main-switch"
  pretty_name: "Sewing Zone South Main Switch"
  target_1: "light.sewing_zone_main_lights_lights"
