packages:
  package: !include common/button_box_2.yaml

substitutions:
  device_name: "sewing-zone-south-accent-switch"
  pretty_name: "Sewing Zone South Accent Switch"
  target_1: "light.sewing_zone_accent_lights_lights"
