packages:
    etekcity: !include common/etekcity_switch.yaml

substitutions:
  device_name: "shear-lamp"
  pretty_name: "Shear Lamp"
  ui_name: "Lamp"
  icon: "mdi:lamp"
  ip_address: "10.13.107.152"
