packages:
  package: !include common/treatlife_ss01s_fan.yaml


substitutions:
  device_name: "small_bathroom_exhaust_fan_lightswitch"
  pretty_name: "Small Bathroom Exhaust Fan Switch"
  ui_name: "Small Bathroom Exhaust Fan"
  icon: "mdi:fan"
  ip_address: "10.13.107.28"