packages:
  package: !include common/treatlife_ss01s_fan.yaml

substitutions:
  device_name: "small-bathroom-exhaust-switch"
  pretty_name: "Small Bathroom Exhaust Switch"
  ui_name: "Fan"
  icon: "mdi:fan"
  ip_address: "10.13.107.28"
