<<: !include common/treatlife_ss01s_fan.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "small_bathroom_exhaust_fan_lightswitch"
  pretty_name: "Small Bathroom Exhaust Fan Switch"
  ui_name: "Small Bathroom Exhaust Fan"
  icon: "mdi:fan"
