packages:
  package: !include common/sonoff_basic_switch.yaml
  
substitutions:
  device_name: wolverine-chiller
  pretty_name: "Wolverine Chiller"
  ui_name: "${pretty_name}"
  icon: "mdi:power"
  ip_address: 10.13.107.256
  